### ISSUE TITLE
Execution failed for task :react-native update:compileReleaseNdk

### ISSUE THREAD

**Issue by zhangyezeng** [reactnativecn/react-native-pushy#103]
com.android.ide.common.process.ProcessException: Error while executing 'C:\android-ndk-r10e\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SC.....
同志们，有谁遇到这样的问题吗？

**Comment by sunnylqm** [comment]
https://github.com/reactnativecn/react-native-pushy/issues/64#issuecomment-287967742

**Comment by zhangyezeng** [comment]
刚刚尝试。。。还真是路径的问题，崩溃。。。十分感谢
