### ISSUE TITLE
发布了新的包和基于新包的版本，为什么应用检测不到需要更新呢？

### ISSUE THREAD

**Issue by zk6859** [reactnativecn/react-native-pushy#104]
如题，检查更新，仍然提示“您的应用版本已是最新”。

**Comment by tonylinyy** [comment]
这个我帮你回答一下:
1.如果是更新了本地代码,需要再热更新的后台把对应平台的旧版本ipa或者apk删除掉,这样子热更新才会把info.expired设置为true,才会检测到更新
2..如果只是更新jsbundle的代码,你用pushy bundle --platform ios或者pushy bundle --platform android应该就可以自动检测到更新

**Comment by zk6859** [comment]
@tonylinyy closed，多谢

**Comment by shareven** [comment]
在这删除，这是教程https://zhuanlan.zhihu.com/p/106468918
