### ISSUE TITLE
更新了原生代码，如何触发下载新的apk版本

### ISSUE THREAD

**Issue by tomorrowshine** [reactnativecn/react-native-pushy#106]
热更新不支持原生修改。如下需求场景：
更新了原生和js代码，如何设置让用户跳转到下载页面？
目前发现，在网页上删除最新版本，然后设置下载地址可以使用户去下载，还有其它方法触发下载吗？

**Comment by sunnylqm** [comment]
还可以通过metainfo来自行判断

**Comment by tomorrowshine** [comment]
可以，不过是 metaInfo
