### ISSUE TITLE
混合应用加载react-naive模块时报错

### ISSUE THREAD

**Issue by realicing** [reactnativecn/react-native-pushy#107]
我的应用是原生与react-native混合应用，打包安装后，尝试加载react-native模块时，直接报错：Attempt to invoke virtual method 'boolean java.lang.String.startWith(java.lang.String)' on a null object reference

**Comment by sunnylqm** [comment]
https://github.com/reactnativecn/react-native-pushy/issues/103

**Comment by zhumoyong** [comment]
各位不好意思，由于我这个版本是在只是在react-native-pushy上面做了一些更新，实用于自己的公司的一套逻辑，解读了一下@sunnylqm 的源码做了iOS部分的修改，支持多个RN实例。今天把android同步过来了。有什么问题大家可以互相讨论一下，我是一名iOS的程序猿。谢谢拉
