### ISSUE TITLE
更新原生包后的bundle加载策略

### ISSUE THREAD

**Issue by swb2016** [reactnativecn/react-native-pushy#108]
因为使用了热更新插件，所以在执行热更新后，插件会把现在的版本hash等一些信息记录到本地缓存中，也就是sharepreference记录下来的那些信息，但是现在我想替换安装这个应用，但是替换安装又不会把本地缓存清空，所以在发生替换安装后，打开应用显示的仍然是上一个版本的内容，请问我该怎样在不清除缓存的前提下实现替换安装新的安装包?

**Comment by sunnylqm** [comment]
只要版本名称不一样(versionName)，替换安装后会清空热更新的记录
