### ISSUE TITLE
我是iOS混合开发 pod引入RN 加入pushy后报错找不到RCTHotUpdate.h文件等

### ISSUE THREAD

**Issue by leeshuangai** [reactnativecn/react-native-pushy#109]
我是iOS混合开发 pod引入RN 加入pushy后报错找不到RCTHotUpdate.h文件等

**Comment by TrustTheBoy** [comment]
一方面，可能是Xcode缓存造成，可能需要重新手动引入一次模块；另一种尝试是，这么写下试试"RCTHotUpdate/RCTHotUpdate.h"，但正常情况下不是这么引入

**Comment by SunMichael** [comment]
我也是，楼主解决了吗？

**Comment by leeshuangai** [comment]
解决了 是因为手动link不好使 我后来用的cocopods链接的

**Comment by SunMichael** [comment]
cocopods 文件你是怎么写的 ？ 我写在react 中会报找不到库

**Comment by SunMichael** [comment]
pod search RCTHotUpdate 也没有

**Comment by leeshuangai** [comment]
你看下我博客写的 http://www.jianshu.com/p/5b7d3d93a8f4

**Comment by SunMichael** [comment]
好的，我看下

**Comment by SunMichael** [comment]
多谢  按你的方法没问题

**Comment by SunMichael** [comment]
你有遇到加入了react native update 在终端打包会报错吗？ Cannot find module 'jest-haste-map'
