### ISSUE TITLE
Android原生混编，热更新失败

### ISSUE THREAD

**Issue by laznrbfe** [reactnativecn/react-native-pushy#110]
1.纯RN项目iOS和Android均可使用热更新
2.iOS原生混编热更新可以使用，Android原生混编使用热更新时，提示更新，下载成功后，点击立即重启/下次重启生效，均未能成功。(使用方法均是按照文档，稍作修改)
3.下载的bundle路径为`/data/data/包名/files/_update/Flvyk1To1K5lMiuEmlWSQUkAR-rh/index.bundlejs`。此路径，纯RN与混编的一致。但未能成功实现热更新。

**Comment by laznrbfe** [comment]
"react": "15.3.2",
"react-native": "0.37.0",
"react-native-update": "^4.0.0",

其中，对markSuccess方法已经做出修改

**Comment by sunnylqm** [comment]
你的混编android能正常打出离线包吗
不能的话，怀疑buildConfig有问题

**Comment by tdzl2003** [comment]
"react-native-update": "^4.0.0",

这个版本可能过时，但不知道你本地安装的是哪个版本，建议升级一下看看

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
