### ISSUE TITLE
iOS出禁热更新通告，以后这个应该不能用了吧？

### ISSUE THREAD

**Issue by 452MJ** [reactnativecn/react-native-pushy#111]
https://mp.weixin.qq.com/s?__biz=MzI0MzE0NTA3Mg==&mid=2651108378&idx=1&sn=5145efc7e5555a6fb1819d08b1bd9921&chksm=f2819405c5f61d133cde379d43c3a7f3396ed05935ed1cffdf9f32851a184becffb4fcb2d0f8&mpshare=1&scene=23&srcid=06012SkGyILP6pHzkpvvs3PU#rd

**Comment by sunnylqm** [comment]
跟三月的警告没有区别，RN和RN的热更新都不受影响

**Comment by kr531236112** [comment]
。。。
