### ISSUE TITLE
execute pushy bundle --platform ios  show some errors..

### ISSUE THREAD

**Issue by shiios** [reactnativecn/react-native-pushy#115]
Bundling with React Native version:  0.44.0
Loading dependency graph, done.
Error
at DependencyGraph._getAbsolutePath 
at DependencyGraph.getDependencies 
at Resolver.getDependencies 
at _resolverPromise.then.resolver 
at process._tickCallback   (internal/process/next_tick.js:109:7)

**Comment by sunnylqm** [comment]
need more details

**Comment by stlemon** [comment]
same here!

**Comment by sunnylqm** [comment]
历史问题，如新版本有问题请重开issue
