### ISSUE TITLE
安卓检测更新太慢了，要一分钟左右

### ISSUE THREAD

**Issue by banli17** [reactnativecn/react-native-pushy#116]
按照这个修改了，还是一样。https://segmentfault.com/a/1190000008005637

**Comment by tdzl2003** [comment]
doUpdate之前 delete info.pdiffUrl 试试

**Comment by longmingfeng** [comment]
如果只是改这个，倒没什么问题，只不过，要费些流量

**Comment by banli17** [comment]
@longmingfeng  你的可以？ 我后来用的`code push`，自建服务器，用`code-push-server`

**Comment by tdzl2003** [comment]
Android 由于图片较多而导致更新很慢的问题在最新版本解决了，可以关注一下。
