### ISSUE TITLE
pushy login 输入密码后卡住

### ISSUE THREAD

**Issue by klaus01** [reactnativecn/react-native-pushy#117]
执行`npm install -g react-native-update-cli rnpm`后，执行`pushy login`输入邮箱和密码，回车后就一直没反应，按`control + c`也退不了。不知什么情况！

![image](https://user-images.githubusercontent.com/338228/27363900-bc7fe59e-5669-11e7-9daa-d305c4edfe52.png)

**Comment by klaus01** [comment]
```
➜  pushy -v
react-native-update-cli: 0.1.0
react-native-update: 4.0.5
```

**Comment by tdzl2003** [comment]
@klaus01 密码输入是无回显的，直接正常输入完毕按回车就好了，注意全角和半角。

**Comment by tonylinyy** [comment]
我们这边这几天也是出现了同样的情况,确认了全角和半角,也把后台的node进程杀掉,重新输入,还是一样的卡住没有反应

**Comment by tdzl2003** [comment]
@tonylinyy 注意看看是否设置了代理等，能否在网页端正常打开[http://update.reactnative.cn/](http://update.reactnative.cn/)

**Comment by klaus01** [comment]
@tdzl2003 
按了很多次回车，没反应，确认没有全角半角问题。
代理也检查了，命令行中可以访问 http://update.reactnative.cn/ （浏览器中也能正常访问）
![image](https://user-images.githubusercontent.com/338228/27999215-3f1ad0a8-654d-11e7-8564-bbca8080632d.png)

**Comment by afusy** [comment]
这个问题解决了吗？我的也是卡住了，没响应
![image](https://user-images.githubusercontent.com/7971551/35610580-c86647e8-069c-11e8-97e9-d9d76258ed1d.png)

**Comment by sunnylqm** [comment]
请尝试新版本，如果还有问题请重开issue
