### ISSUE TITLE
pushy bundle --platform android  报错

### ISSUE THREAD

**Issue by flyjennyetn** [reactnativecn/react-native-pushy#118]
E:\rnupdate>pushy bundle --platform android
Bundling with React Native version:  0.42.0
'yarn' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
Error: Cannot find module 'E:\rnupdate\node_modules\react-native\local-cli\defau
lt.config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\rnupdate\node_modules\react-native-update\local-cl
i\lib\bundle.js:446:89)
    at next (native)
    at step (E:\rnupdate\node_modules\react-native-update\local-cli\lib\bundle.j
s:310:191)
    at E:\rnupdate\node_modules\react-native-update\local-cli\lib\bundle.js:310:
361

**Comment by sunnylqm** [comment]
pushy -v

**Comment by leeshuangai** [comment]
我也是报错 你解决的吗 跟你报错一样

**Comment by HateTomatoes** [comment]
我也遇到同样的问题了，找不到解决办法
Bundling with React Native version:  0.46.4
react-native-update-cli: 0.1.0
react-native-update: 5.0.0

**Comment by xinwanggit** [comment]
将\node_modules\react-native-update\local-cli\lib\bundle.js中439行的'metro-bundler/src/babelRegisterOnly'改为'metro-bundler/build/babelRegisterOnly'，原因是因为在metro-bundler引用的路径错了

**Comment by xinwanggit** [comment]
@HateTomatoes 将\node_modules\react-native-update\local-cli\lib\bundle.js中439行的'metro-bundler/src/babelRegisterOnly'改为'metro-bundler/build/babelRegisterOnly'，原因是因为在metro-bundler引用的路径错了

**Comment by Geek-ch** [comment]
> 将\node_modules\react-native-update\local-cli\lib\bundle.js中439行的'metro-bundler/src/babelRegisterOnly'改为'metro-bundler/build/babelRegisterOnly'，原因是因为在metro-bundler引用的路径错了

亲测有效

**Comment by temple002** [comment]
在最新的版本中，路径又改了，把\node_modules\react-native-update\local-cli\lib\bundle.js中439行的'metro-bundler/src/babelRegisterOnly'改为'require('metro/src/babelRegisterOnly');'

**Comment by Deain** [comment]
rn>=0.56 ，\node_modules\react-native-update\local-cli\lib\bundle.js中439行判断中添加
[引用](https://github.com/ds300/react-native-typescript-transformer/blob/master/index.js#L20)
```
if (minor >= 56) {
          require('metro/src/reactNativeTransformer')
        }
```
