### ISSUE TITLE
RCTHotUpdate.h' file not found

### ISSUE THREAD

**Issue by SunMichael** [reactnativecn/react-native-pushy#119]
按文档来操作之后  也link 了 react - native -update  但还是报错 ？

**Comment by leeshuangai** [comment]
应该是link不好使 我是cocopods 弄的

**Comment by chenqingxiao007** [comment]
我也有这个问题

**Comment by tdzl2003** [comment]
您的RN版本和react-native-update版本分别是多少？ 出现这个错误往往是版本不匹配造成的，请仔细阅读文档中的相关部分。

**Comment by jacobcyl** [comment]
我的RN是0.42.0，react-native-update是^4.0.5，也是这个问题，请问怎么解决

**Comment by SunMichael** [comment]
我现在用code-push了，你可以按这个教程试试，2楼的方法 http://www.jianshu.com/p/5b7d3d93a8f4
