### ISSUE TITLE
ios install react-native-update fail

### ISSUE THREAD

**Issue by jjkke88** [reactnativecn/react-native-pushy#12]
510 verbose stack Error: node-bsdiff@0.1.4 install: `node-gyp rebuild`
510 verbose stack Exit status 1
510 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
510 verbose stack     at emitTwo (events.js:100:13)
510 verbose stack     at EventEmitter.emit (events.js:185:7)
510 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
510 verbose stack     at emitTwo (events.js:100:13)
510 verbose stack     at ChildProcess.emit (events.js:185:7)
510 verbose stack     at maybeClose (internal/child_process.js:850:16)
510 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
511 verbose pkgid node-bsdiff@0.1.4
512 verbose cwd /Users/wuyupei/Desktop/medicine
513 error Darwin 15.3.0
514 error argv "/usr/local/Cellar/node/5.8.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native-update"
515 error node v5.8.0
516 error npm  v3.7.3
517 error code ELIFECYCLE
518 error node-bsdiff@0.1.4 install: `node-gyp rebuild`
518 error Exit status 1
519 error Failed at the node-bsdiff@0.1.4 install script 'node-gyp rebuild'.
519 error Make sure you have the latest version of node.js and npm installed.
519 error If you do, this is most likely a problem with the node-bsdiff package,
519 error not with npm itself.
519 error Tell the author that this fails on your system:
519 error     node-gyp rebuild
519 error You can get information on how to open an issue for this project with:
519 error     npm bugs node-bsdiff
519 error Or if that isn't available, you can get their info via:
519 error     npm owner ls node-bsdiff
519 error There is likely additional logging output above.
520 verbose exit [ 1, true ]

**Comment by sunnylqm** [comment]
有更换淘宝源吗

**Comment by jjkke88** [comment]
是淘宝源
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.8.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native-update"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! node-bsdiff@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-bsdiff@0.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-bsdiff package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-bsdiff
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-bsdiff
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wuyupei/Desktop/medicine/npm-debug.log

**Comment by tdzl2003** [comment]
这是依赖库构建失败了。 你是否缺少C++环境？或者看一下安装日志里是否还有更详细的错误信息。

**Comment by liugangfeng** [comment]
我这边也报错了。

**Comment by liugangfeng** [comment]
> node-bsdiff@0.1.4 install /Users/apple/reactNativeProject/baseProject/node_modules/node-bsdiff
> node-gyp rebuild

2016-05-19 10:51:59.160 xcodebuild[9781:876355] Build settings from command line:
2016-05-19 10:51:59.161 xcodebuild[9781:876355]     ENABLE_BITCODE = NO
2016-05-19 10:51:59.161 xcodebuild[9781:876355]     SWIFT_DISABLE_REQUIRED_ARCLITE = YES
2016-05-19 10:51:59.161 xcodebuild[9781:876355]     SWIFT_LINK_OBJC_RUNTIME = YES
2016-05-19 10:51:59.161 xcodebuild[9781:876355]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-05-19 10:51:59.161 xcodebuild[9781:876355]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
  CXX(target) Release/obj.target/bsdiff/src/main.o
  CC(target) Release/obj.target/bsdiff/src/bsdiff/bsdiff.o
  CC(target) Release/obj.target/bsdiff/src/bzlib/bzlib.o
  CC(target) Release/obj.target/bsdiff/src/bzlib/compress.o
  CC(target) Release/obj.target/bsdiff/src/bzlib/crctable.o
  CC(target) Release/obj.target/bsdiff/src/bzlib/randtable.o
  CC(target) Release/obj.target/bsdiff/src/bzlib/blocksort.o
  CC(target) Release/obj.target/bsdiff/src/bzlib/huffman.o
  CC(target) Release/obj.target/bsdiff/src/bzlib/decompress.o
  SOLINK_MODULE(target) Release/bsdiff.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bsdiff.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/apple/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Users/apple/.nvm/versions/node/v5.10.1/bin/node" "/Users/apple/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/apple/reactNativeProject/baseProject/node_modules/node-bsdiff
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
baseProject@0.0.1 /Users/apple/reactNativeProject/baseProject
├── react-native-contacts@0.2.5  extraneous
├── react-native-side-menu@0.18.0  extraneous
└── UNMET PEER DEPENDENCY react-native-system-notification@0.1.9

npm WARN react-native-gcm-android@0.1.9 requires a peer of react-native-system-notification@^0.0.8 but none was installed.
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/apple/.nvm/versions/node/v5.10.1/bin/node" "/Users/apple/.nvm/versions/node/v5.10.1/bin/npm" "install" "--save" "react-native-update"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! node-bsdiff@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-bsdiff@0.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-bsdiff package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-bsdiff
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-bsdiff
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/reactNativeProject/baseProject/npm-debug.log

**Comment by sunnylqm** [comment]
ld: library not found for -lgcc_s.10.5

升级xcode，然后打开xcode运行一次后再试试

**Comment by tdzl2003** [comment]
这个报错之前遇到过几次，貌似重启一下就好了。是node的mac版和Xcode之间的问题。
