### ISSUE TITLE
热更新服务坏了？更新包上传不上去

### ISSUE THREAD

**Issue by forrest23** [reactnativecn/react-native-pushy#121]
安卓、苹果的更新包都上传不上去，是不是服务坏了？这个地址58.220.6.152:80 telnet 不通
Bundled saved to: build/output/ios.1499440398747.ppk
Would you like to publish it?(Y/N) y
  Uploading [====                                                                                                         ] 4% 0.0s
Error: connect ETIMEDOUT 58.220.6.152:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

@sunnylqm @lvbingru @geniuslinchao @walter211 @tdzl2003

**Comment by forrest23** [comment]
有人遇到嘛？应该不会就我一个人这样吧？

**Comment by tdzl2003** [comment]
@forrest23 经测试我们的服务正常运行，请检查您的本地网络，以及是否设置了网络代理

**Comment by forrest23** [comment]
@tdzl2003  感谢您的回复。我检查了我并没有设置代理，家里的网络，公司的网络，电信4g,联通4g都无法上传。我测试了检测更新和下载更新是正常的。如果服务正常的话，那可能是我电脑哪里的配置有问题了，明天用同事电脑试下，看是不是有这个问题。

**Comment by forrest23** [comment]
@tdzl2003  在查看了源码之后，终于找到不能上传的原因了。原来你们也是用的七牛云，文件是上传到七牛云上的。之前我用过fir.im，fir.im也是用的七牛云。因为上传慢，fir.im给了一个寻找最快ip的命令，所以我找了一个ip，然后改了hosts文件。现在这个ip不能用了，所以就无法上传了。再次感谢tdzl2003！
