### ISSUE TITLE
android差异包大小问题

### ISSUE THREAD

**Issue by KentFeng** [reactnativecn/react-native-pushy#122]
在两台电脑上生成差异包，这里叫A和B，A包比较小只有2kb，改成压缩文件解压后发现diff.json中有很多图片资源多替换路径（key-value），没有图片资源；B包比较大，有1M左右，是因为里面有一些图片资源，但是diff.json中需要替换的资源比较少了。这样就造成一种现象，A包下载快，但是解压和复制图片资源的时间比较长，B包整个过程只需要3-5秒左右。不知道这种现象是什么原因造成的？

**Comment by sunnylqm** [comment]
应该在5.1.x版本中解决了
