### ISSUE TITLE
Cannot read property "id" of null checkUpdate

### ISSUE THREAD

**Issue by chimumao** [reactnativecn/react-native-pushy#127]
编译和Link都没问题，运行出现警告：
Possible unhandled Promise Rejection(id:0)；
Cannot read property "id" of null checkUpdate

**Comment by chimumao** [comment]
已解决，引用问题

**Comment by Dirmond** [comment]
楼主怎么解决的啊，我也出现了这个问题了

**Comment by Smart-XiaoLeiGe** [comment]
@chimumao 这个怎么解决的？能说一下嘛？
