### ISSUE TITLE
[Android]关于新增图片热更新不成功

### ISSUE THREAD

**Issue by mjwWell** [reactnativecn/react-native-pushy#128]
##### 操作

* 在`src/views/images`文件夹中添加`bg_hot_status.png`图片
* 在`src/views/abc/Xyz.js`文件中引用图片`<Image source={require("../images/bg_hot_status.png")} style={styles.icon}/>`
* 发布热更新`pushy bundle --platform android`
* 安卓热更新后,图片对应的位置显示空白
* .ppk文件中搜索发现`bg_hot_status.png`

##### 个人结论

* .js文件修改热更新成功
* RN图片资源未能热更新

##### package.json

```
{
  ...
  "dependencies": {
    ...
    "react": "15.3.2",
    "react-native": "0.37.0",
    "react-native-update": "^4.0.0",
    ...
  },
  ...
}
```

**Comment by wufeng3** [comment]
楼主，我也遇到这个问题，请问你解决了吗

**Comment by sunnylqm** [comment]
请尝试新版本，如果还有问题请重开issue
