### ISSUE TITLE
 报错：cannot locate symbol "stderr" referenced by "librnupdate.so"，RN版本0.43，NDK版本r15

### ISSUE THREAD

**Issue by chenchen1008** [reactnativecn/react-native-pushy#131]
#4813 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "librnupdate.so"...
-- | -- | -- | -- | -- | --
#4814 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at java.lang.Runtime.loadLibrary(Runtime.java:371)
#4815 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at java.lang.System.loadLibrary(System.java:989)
#4816 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at cn.reactnative.modules.update.DownloadTask.(DownloadTask.java:46)
#4817 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at cn.reactnative.modules.update.UpdateContext.clearUp(UpdateContext.java:213)
#4818 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at cn.reactnative.modules.update.UpdateContext.(UpdateContext.java:38)
#4819 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at cn.reactnative.modules.update.UpdateContext.getBundleUrl(UpdateContext.java:154)
#4820 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at com.jiuyi.credit.nengdai.MainApplication$1.getJSBundleFile(MainApplication.java:30)
#4821 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:78)
#4822 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
#4823 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111)
#4824 | 09-20 10:13:51.489 | 11635 | E | AndroidRuntime | at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDe

**Comment by midas-gufei** [comment]
https://github.com/midas-gufei/react-native-pushy
