### ISSUE TITLE
 程序包com.facebook.react.cxxbridge不存在

### ISSUE THREAD

**Issue by wangpengzong** [reactnativecn/react-native-pushy#134]
我使用了
1、首先尝试删除掉 android/build android/app/build node_modules/react-native-update/android/build 三个文件夹再重试
2、再尝试更换NDK版本到r10e再重试
这两种办法都不可以，还是报这个错误
版本：
"react-native": "~0.46.4",
"react-native-update": "^4.0.6",
ndk  r10e (64-bit)

电脑系统：windows

`:react-native-update:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\Ylsdai.App\node_modules\react-native-update\android\src\main\java\cn\reactnative\modules\update\UpdateModule.java:16: 错误: 程序包com.facebook.react.cxxbridge不存在
import com.facebook.react.cxxbridge.JSBundleLoader;
                                   ^
D:\Ylsdai.App\node_modules\react-native-update\android\src\main\java\cn\reactnative\modules\update\UpdateModule.java:132: 错误: 找不到符号
                        JSBundleLoader loader = JSBundleLoader.createFileLoader(UpdateContext.getBundleUrl(application));
                        ^
  符号: 类 JSBundleLoader
D:\Ylsdai.App\node_modules\react-native-update\android\src\main\java\cn\reactnative\modules\update\UpdateModule.java:132: 错误: 找不到符号
                        JSBundleLoader loader = JSBundleLoader.createFileLoader(UpdateContext.getBundleUrl(application));
                                                ^
  符号: 变量 JSBundleLoader
3 个错误
:react-native-update:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-update:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

**Comment by wangpengzong** [comment]
找到原因了，在\node_modules\react-native\ReactAndroid\src\main\java\com\facebook\react\bridge\JSBundleLoader.java中的命名空间是package com.facebook.react.bridge，所以文档里面的com.facebook.react.cxxbridge.JSBundleLoader程序包引用是错的，手工改成com.facebook.react.bridge.JSBundleLoader就好了，好坑呀

**Comment by sunnylqm** [comment]
已在5.x版本中修复
