### ISSUE TITLE
建议对文档‘iOS的ATS例外配置’处说明进行修改

### ISSUE THREAD

**Issue by wlfcss** [reactnativecn/react-native-pushy#138]
react-native 0.49.3 版本中的Info.plist文件，本就存在对于localhost的配置
![qq20171020-203327](https://user-images.githubusercontent.com/12138285/31821336-68c484d6-b56a-11e7-84af-be86e1042410.png)

如果直接将文档中的以下代码加入并不会生效，访问接口直接提示 type network request failed
`<key>NSAppTransportSecurity</key>`
`<dict>`
    `<key>NSExceptionDomains</key>`
    `<dict>`
        `<key>reactnative.cn</key>`
       ` <dict>`
           ` <key>NSIncludesSubdomains</key>`
           `<true/>`
         ` <key>NSExceptionAllowsInsecureHTTPLoads</key>`
          `<true/>`
      `</dict>`
   `</dict>`
`</dict>`

下方为可生效的写法

![7134bdbf-9e32-4830-8f13-ec785a25befa](https://user-images.githubusercontent.com/12138285/31821438-bb75a49e-b56a-11e7-8d3c-0ec8cf9f6f96.png)

建议对文档稍作修改，或可对新手更加友好一些

**Comment by sunnylqm** [comment]
那么如果别人这里还有其他域名的配置，又当如何说明？

**Comment by wlfcss** [comment]
有其他域名配置的人本来就懂，就不必在意了~
我建议可以提一句，如Info.plist 本来就存在‘NSAppTransportSecurity’的配置项，则直接在配置项中添加
```
<key>reactnative.cn</key>
<dict>
<key>NSIncludesSubdomains</key>
<true/>
<key>NSExceptionAllowsInsecureHTTPLoads</key>
<true/>
</dict>
```
即可

**Comment by sunnylqm** [comment]
这种看似对新手友好的做法并没有什么意义。如果这样的配置不理解，后面的几乎可以都不用看了。

**Comment by wlfcss** [comment]
还是非常感谢你的回复，谢谢你们的项目
