### ISSUE TITLE
com.facebook.react.cxxbridge doesn't exit () 

### ISSUE THREAD

**Issue by lanjinglingxx** [reactnativecn/react-native-pushy#139]
Information:(75, 9) include the header <string.h> or explicitly provide a declaration for 'memcmp'
1 warning generated.

:react-native-update:compileLint
:react-native-update:copyReleaseLint UP-TO-DATE
:react-native-update:compileReleaseRenderscript
:react-native-update:generateReleaseBuildConfig
:react-native-update:generateReleaseResValues
:react-native-update:generateReleaseResources
:react-native-update:mergeReleaseResources
:react-native-update:processReleaseManifest
:react-native-update:processReleaseResources
:react-native-update:generateReleaseSources
:react-native-update:incrementalReleaseJavaCompilationSafeguard
:react-native-update:javaPreCompileRelease
:react-native-update:compileReleaseJavaWithJavac
:react-native-update:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

/Users/li/Documents/doctorSystem/ios/doctor/DoctorApp/node_modules/react-native-update/android/src/main/java/cn/reactnative/modules/update/UpdateModule.java:15: 错误: 程序包com.facebook.react.cxxbridge doesn't exit

**Comment by sunnylqm** [comment]
rn版本和pushy的版本

**Comment by lanjinglingxx** [comment]
react-native": "0.47.1","react-native-update": "^4.0.6",

**Comment by sunnylqm** [comment]
0.46以上对应pushy 5.x版本

**Comment by lanjinglingxx** [comment]
Information:(75, 9) include the header <string.h> or explicitly provide a declaration for 'memcmp'
1 warning generated.


:react-native-update:compileLint UP-TO-DATE
:react-native-update:copyReleaseLint UP-TO-DATE
:react-native-update:compileReleaseRenderscript UP-TO-DATE
:react-native-update:generateReleaseBuildConfig
:react-native-update:generateReleaseResValues UP-TO-DATE
:react-native-update:generateReleaseResources UP-TO-DATE
:react-native-update:mergeReleaseResources
:react-native-update:processReleaseManifest UP-TO-DATE
:react-native-update:processReleaseResources
:react-native-update:generateReleaseSources
:react-native-update:incrementalReleaseJavaCompilationSafeguard
:react-native-update:javaPreCompileRelease
:react-native-update:compileReleaseJavaWithJavac
:react-native-update:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:react-native-update:extractReleaseAnnotations
:react-native-update:mergeReleaseShaders UP-TO-DATE
:react-native-update:compileReleaseShaders UP-TO-DATE
:react-native-update:generateReleaseAssets UP-TO-DATE
:react-native-update:mergeReleaseAssets UP-TO-DATE
:react-native-update:mergeReleaseProguardFiles UP-TO-DATE
:react-native-update:packageReleaseRenderscript UP-TO-DATE
:react-native-update:packageReleaseResources UP-TO-DATE
:react-native-update:processReleaseJavaRes UP-TO-DATE
:react-native-update:transformResourcesWithMergeJavaResForRelease
:react-native-update:transformClassesAndResourcesWithSyncLibJarsForRelease
:react-native-update:mergeReleaseJniLibFolders
:react-native-update:transformNativeLibsWithMergeJniLibsForRelease
:react-native-update:transformNativeLibsWithStripDebugSymbolForRelease
:react-native-update:transformNativeLibsWithSyncJniLibsForRelease
:react-native-update:bundleRelease
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

/Users/li/Documents/doctorSystem/ios/doctor/DoctorApp/android/app/src/main/java/com/doctorapp/MainApplication.java:25: 错误: 找不到符号
符号: 变量 UpdateContext

**Comment by lanjinglingxx** [comment]
"react-native-update": "^5.0.0",

**Comment by lanjinglingxx** [comment]
已经搞定 谢谢
