### ISSUE TITLE
修改图片的话 用这个可以吗

### ISSUE THREAD

**Issue by zhongjie-chen** [reactnativecn/react-native-pushy#14]
图片是不是会转换成base64 到js bundle里面

**Comment by tdzl2003** [comment]
通过require引用的图片会被打到ppk里，因此可以通过热更新来更新。但不是base64，那样太占用内存了。

**Comment by zhongjie-chen** [comment]
react-native-pushy
 是能够对图片进行热更新！可以这样理解吗

**Comment by sunnylqm** [comment]
是的
