### ISSUE TITLE
不支持Android Studio 3编译

### ISSUE THREAD

**Issue by sofwu** [reactnativecn/react-native-pushy#141]
不支持Android Studio 3编译

Error:Execution failed for task ':react-native-update:compileDebugNdk'.
> Error: Flag android.useDeprecatedNdk is no longer supported and will be removed in the next version of Android Studio.  Please switch to a supported build system.
  Consider using CMake or ndk-build integration. For more information, go to:
   https://d.android.com/r/studio-ui/add-native-code.html#ndkCompile
   To get started, you can use the sample ndk-build script the Android
   plugin generated for you at:
   /Users/duguying/code/opsapp/node_modules/react-native-update/android/build/intermediates/ndk/debug/Android.mk
  Alternatively, you can use the experimental plugin:
   https://developer.android.com/r/tools/experimental-plugin.html
  To continue using the deprecated NDK compile for another 60 days, set 
  android.deprecatedNdkCompileLease=1509345866453 in gradle.properties

**Comment by midas-gufei** [comment]
https://github.com/midas-gufei/react-native-pushy，已经更新CMakeLists.txt，支持as3.0.
