### ISSUE TITLE
ios下载更新时报错(交流群加不进去，无法及时沟通)

### ISSUE THREAD

**Issue by stlemon** [reactnativecn/react-native-pushy#142]
我在执行下载更新版本时报错
Error: bsdiff error
    at createErrorFromErrorData (NativeModules.js:115)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:296)
    at MessageQueue.js:120
    at MessageQueue.__guard (MessageQueue.js:218)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:119)
    at debuggerWorker.js:71
xcode也进行配置了
![default](https://user-images.githubusercontent.com/21324615/32430879-25711f1e-c30c-11e7-9d2d-b8c2d72f509b.png)
platform:ios
RN version :0.44.3
react-native-update version: 4.0.6.
再就是为啥添加QQ交流群时提示管理员拒绝呢？我输入reactnative.cn也拒绝。可否提供一个及时交流的途径？非常感谢！

**Comment by stlemon** [comment]
没有人维护更新了吗？

**Comment by tdzl2003** [comment]
您好。
出现这个错误绝大部分情况都是uploadIpa所上传的ipa和实际执行的不是同一个包。

如果在开发环境测试，请先在手机上运行应用，然后使用itunes导出ipa，再用uploadIpa上传。测试完毕后，务必从网页端删除对应的包版本。

实际发布时，应当Export出ipa来，使用Application Loader上传TestFlight并安装到手机，同时uploadIpa上传同一个文件。如果发现版本有问题，务必重新执行两个步骤再进行更新测试。测试完毕之后，再将对应版本提交审核（注意提交审核的时候不要有任何“更新”字眼的提示，否则会被拒绝。）。

**Comment by stlemon** [comment]
感谢回答！
