### ISSUE TITLE
pushy uploadIpa xxx.ipa error

### ISSUE THREAD

**Issue by afinal** [reactnativecn/react-native-pushy#143]
Error: Validation error
    at /Users/xicui/Work/Git/xicui_rn/node_modules/react-native-update/local-cli/lib/api.js:8:27
    at next (native)
    at step (/Users/xicui/Work/Git/xicui_rn/node_modules/react-native-update/local-cli/lib/api.js:82:191)
    at /Users/xicui/Work/Git/xicui_rn/node_modules/react-native-update/local-cli/lib/api.js:82:361
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by sunnylqm** [comment]
你已经上传过同样版本号的ipa

**Comment by afinal** [comment]
@sunnylqm 是的，我把之前的东西删掉就好了，估计应该是版本号重复了

**Comment by mynameislizhifei** [comment]
android 怎么修改版本号呢 在build.gradle中修改versionName么 我修改了 但是没反应啊。上传还是报这个错，而且这个版本号怎么是1.0 我要怎么修改上传的版本号 @sunnylqm

**Comment by sunnylqm** [comment]
@mynameislizhifei https://www.cnblogs.com/maxiaodoubao/p/4466609.html

**Comment by mynameislizhifei** [comment]
我修改了versionCode 和 versionName提高一个版本 但是没用啊 @sunnylqm

**Comment by sunnylqm** [comment]
@mynameislizhifei 有重新编译吗

**Comment by mynameislizhifei** [comment]
有啊，我重新编译过 @sunnylqm

**Comment by mynameislizhifei** [comment]
而且我上传的包的名字命名如果不跟别名一致,就一直报错提示Invaild filename 文件名无效

**Comment by mynameislizhifei** [comment]
@sunnylqm

**Comment by sunnylqm** [comment]
截图另开issue

**Comment by mynameislizhifei** [comment]
好的
