### ISSUE TITLE
[android]更新完之后退出app，然后清空缓存，再进app，就是原来的版本了！！！

### ISSUE THREAD

**Issue by lhhhhhhhhh** [reactnativecn/react-native-pushy#144]

**Comment by sunnylqm** [comment]
正常啊

**Comment by lhhhhhhhhh** [comment]
一般android用户都习惯手动清手机缓存，然后再进app又得重新下载更新？循环操作？显得热更新是一次性的一样。

**Comment by lhhhhhhhhh** [comment]
android用户比较习惯手动清空缓存，那不是app下载更新后，清空缓存，再进app又显示有新的版本下载更新。。。死循环！那这个热更新不相当于一次性的了？

**Comment by tdzl2003** [comment]
1. 用户清空缓存不应该是一个经常性的动作。你的应用应该提供“清理缓存”这样的功能来帮助用户。
2. 检查更新应该在应用启动的时候，可以考虑设置成静默更新，这样用户再次打开应用，不需要任何提示就可以完成更新。

**Comment by lhhhhhhhhh** [comment]
感谢你们回复。不好意思，可能我描述的有误。我是说app下载更新后，退出app，清空手机里app的进程，然后再进app，此时app是上一个版本的，然后又会提示有更新。

**Comment by sunnylqm** [comment]
那多半是你没有执行markSuccess
