### ISSUE TITLE
配置Bundle URL(Android),按照教程报错

### ISSUE THREAD

**Issue by unionTime** [reactnativecn/react-native-pushy#149]
版本：
`"react-native-update": "^5.0.0"`
在配置好之后，react-native run-android 报错如下：
`
/Users/union/Documents/workspace/smart-city/phone/smartphone/android/app/src/main/java/com/smartphone/MainApplication.java:41: 错误: 已在类 MainApplication中定义了变量 mReactNativeHost
 private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                               ^
/Users/union/Documents/workspace/smart-city/phone/smartphone/android/app/src/main/java/com/smartphone/MainApplication.java:41: 错误: <匿名com.smartphone.MainApplication$2>不是抽象的, 并且未覆盖ReactNativeHost中的抽象方法getPackages()
 private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                                            ^
2 个错误
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
`
我在MainApplication文件中把教程中增加的代码注释掉后，编译成功！

请问是否是真的成功？

**Comment by sunnylqm** [comment]
看报错提示应该是你配置错了。请注意阅读和观察，不要机械性的复制粘贴。

**Comment by brusyy** [comment]
link应该可以自动加入代码和配置文件。我的0.44.0的就是自动link的。你重新开始试试。看到active里面有update就不要手动改代码。应该可以自动link成功。
