### ISSUE TITLE
RN引入react-native-update之后出现cannot read property downloadRootDir of undefined

### ISSUE THREAD

**Issue by sixcx** [reactnativecn/react-native-pushy#150]

**Comment by sunnylqm** [comment]
没有执行link或link后没有编译

**Comment by sixcx** [comment]
多谢 @sunnylqm 是我的配置原因

**Comment by zdhgithub** [comment]
请问怎么解决的，我也遇到这个问题

**Comment by zdhgithub** [comment]
![image](https://user-images.githubusercontent.com/18691917/39173390-31b4ccbc-47d7-11e8-8e13-bfd24d151ef9.png)

**Comment by tdzl2003** [comment]
@zdhgithub 

react-native link react-native-update
然后重新编译&打包。
