### ISSUE TITLE
android sdk问题

### ISSUE THREAD

**Issue by DaiYz** [reactnativecn/react-native-pushy#155]
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-update'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-update'. Minimum required is 25.0.0

请教下大家有没有遇到这样的问题

**Comment by tdzl2003** [comment]
5.1.0更新了SDK revision
