### ISSUE TITLE
现有iOS项目添加pushy后 'React/RCTDefines.h' file not found错误

### ISSUE THREAD

**Issue by iriswe** [reactnativecn/react-native-pushy#156]
把react-native 嵌入原有项目，用CocoaPods按照文档 导入React库，命令行link了 RCTUpdate.xcodeproj的.a库，Build Phases加了 libRCTUpdate.a库，但是报 'React/RCTDefines.h' file not found错误
尝试过0.44.3 版本对应的4.x和0.50.0版本对应的5.x一样的错误，参考了这个https://github.com/reactnativecn/react-native-pushy/issues/93 但不知道怎么改不对

**Comment by XcqRomance** [comment]
我最近也遇到了这个问题，原生项目集成RN后，需要使用热更新按照文档配置，Build Phases加了 libRCTUpdate.a库就会报错'React/RCTDefines.h' file not found，使用的RN是"react-native": "0.51",
    "react-native-update": "^5.0.0"版本。现在在这里卡住了

**Comment by liyanfei1004774105** [comment]
有人解决了么,我的同上

**Comment by XcqRomance** [comment]
@liyanfei1004774105 我解决了，会滚到0.50版本是好的

**Comment by iriswe** [comment]
看到邮件给个网上的链接
http://blog.csdn.net/leeshuangai/article/details/72844363

**Comment by huangzhifei** [comment]
我快要疯了，当初遇到这个问题，我以为是React Native版本问题，一怒之下升级到最新，各种问题，各种坑，好不容易解决完了，还是遇到这个问题，这会告诉我要回滚到0.50，磨刀去~

**Comment by huangzhifei** [comment]
@iriswe 这篇文章解救了我
