### ISSUE TITLE
Could not invoke RCTHotUpdate.downloadPatchFromPackage null

### ISSUE THREAD

**Issue by lailibo8** [reactnativecn/react-native-pushy#157]
Could not invoke RCTHotUpdate.downloadPatchFromPackage null
![04d58a1892d645fa8d1c31e564fb338a](https://user-images.githubusercontent.com/13062763/33813031-7932189a-de5c-11e7-8a8b-99cfb4c3a0d4.jpg)

**Comment by YeomanYe** [comment]
我也遇到这个问题同求

**Comment by ghyzx** [comment]
这几天在集成Android的热更新，下载更新时也弹出这个错误，同求解答。

更多信息：
原生与RN混合的工程（原生为主，RN只涉及1个模块），参照官网的快速指南操作，
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-update": "^5.0.0"

**Comment by ghyzx** [comment]
类比着iOS端的集成过程，应该是要在
mReactInstanceManager = ReactInstanceManager.builder()
            .setApplication(getActivity().getApplication())
            .setBundleAssetName("index.bundle")
            .setJSMainModulePath("index")
            .setJSBundleFile(UpdateContext.getBundleUrl(getActivity()))
            .addPackages(Arrays.<ReactPackage>asList(new MainReactPackage(), new UpdatePackage()))
            .setUseDeveloperSupport(BuildConfig.DEBUG)
            .setInitialLifecycleState(LifecycleState.RESUMED)
            .build();
中加入 .setJSBundleFile(UpdateContext.getBundleUrl(getActivity()))，但实际运行发现 UpdateContext.getBundleUrl(getActivity())返回的是null，问题是不是出在这里？

**Comment by lailibo8** [comment]
@ghyzx 你现在解决了这个更新问题了吗，怎么解决的

**Comment by ghyzx** [comment]
@lailibo8  还没解决，同求解决方案

**Comment by lailibo8** [comment]
我现在是release版本被回滚，debug更新失败

**Comment by libb1993** [comment]
这个坑什么时候可以填满

**Comment by lailibo8** [comment]
@libb1993 这个坑估计是插件本身就有问题

**Comment by ghyzx** [comment]
@lailibo8   请问你是怎么解决“Could not invoke RCTHotUpdate.downloadPatchFromPackage”这个问题，走到  “我现在是release版本被回滚，debug更新失败” 这一步的了？

**Comment by lailibo8** [comment]
@ghyzx 目前我的iOS版本的DEBUG和release版本已经可以正常更新，安卓的现在正在尝试中

**Comment by ghyzx** [comment]
@lailibo8 我的也是iOS ok了，Android的卡在“Could not invoke RCTHotUpdate.downloadPatchFromPackage”

**Comment by lailibo8** [comment]
@ghyzx 我的打包总是不理想

**Comment by r4ggj** [comment]
报同样的错误，求解决

**Comment by LiuTing0403** [comment]
报同样的错误，求解决

**Comment by xingliang152** [comment]
Could not invoke RCTHotUpdate.downloadPatchFromPackage null,这个到底是什么问题，有哪位大神知道的 @ @lailibo8

**Comment by abraham1912** [comment]
我是重新运行了一遍这两个就好了。npm i -g react-native-update-cli  然后 npm i react-native-update@具体版本

**Comment by sunnylqm** [comment]
请尝试新版本，如果还有问题请重开issue
