### ISSUE TITLE
Android 更新成功，但是界面没有变化

### ISSUE THREAD

**Issue by Yangzhuren** [reactnativecn/react-native-pushy#158]
项目添加热更新之后，Android打包，安装，命令行 ‘pushy bundle --platform android’，然后更新成功，重启之后提示已是最新版本。（react-native 版本0.50.3，react-native-update版本^5.0.0）
        问题：1，界面还是上一个版本的界面；
                   2，虽然已经调用过markSuccess函数，但是每次启动的时候，isFirstTime参数还是true

代码如下：
componentWillMount() {
    if (isFirstTime) {
      markSuccess()
      Toast.show('Marked')
    }
    if (isRolledBack) {
      Toast.show('roll back')
    }
  }

  componentDidMount() {
    const { appKey } = _updateConfig[Platform.OS]
    checkUpdate(appKey)
      .then((info) => {
        if (info.expired) {
          Toast.show('请前往应用市场下载新的版本')
        } else if (info.update) {
          downloadUpdate(info)
            .then((hash) => {
              switchVersion(hash)
              Toast.show('更新成功')
            })
        } else if (info.upToDate) {
          Toast.show('已是最新版')
        }
      })
      .catch((error) => {
        Toast.show(`更新失败：${error.message}`)
      })
  }

**Comment by 18705320883** [comment]
我也遇到这个问题，根本就没更新啊

**Comment by 18705320883** [comment]
http://blog.csdn.net/u014175342/article/details/73823904
我找到解决方法了，必须在android项目里新建assets目录，然后
react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
指定bundle文件的生成位置，这样在assets目录下就能看到bundle文件，
然后编译出release版本发布，
之后再按这个pushy的文档就能够更新成功了

很多人都遇到这个问题，文档里最好说明一下

**Comment by sunnylqm** [comment]
@18705320883 编译release版本是会自动执行bundle的，所以我不明白你解决了什么问题

**Comment by 18705320883** [comment]
@sunnylqm 问题就是release版本没有执行bundle，需要手动执行

**Comment by sunnylqm** [comment]
@18705320883 那只能说明你的操作有问题。你可以试试你的"release"版本能不能摇出开发者菜单？能的话就是100%配置不对。

**Comment by 18705320883** [comment]
@sunnylqm  菜单是能摇出来，但不知道配置什么，网上有些源码android目录下连asset文件夹都没有，打出的release包没有bundle

**Comment by sunnylqm** [comment]
@18705320883 配置什么当然是看文档啊 https://reactnative.cn/docs/0.51/signed-apk-android.html#content
assets目录本来就是没有的

**Comment by budiga** [comment]
@18705320883   你是用android studio打包吧，才需要创建asset文件并生成bundle文件
