### ISSUE TITLE
当uploadIpa/uploadApk包与运行的包不一致的时候

### ISSUE THREAD

**Issue by tdzl2003** [reactnativecn/react-native-pushy#16]
目前策略：
- 存在差异更新的情况下，强制走差异更新，最后导致闪退

期望策略：
- 提供main.bundlejs的CRC码用于验证，避免不正确的差异更新
- 差异更新后进行CRC验证，如果失败，尝试进行全量更新
- 第一次全量更新以后，后续更新依然可以通过差异更新进行

**Comment by hkcmly** [comment]
IPA可以检测到差异，但是apk好像不可以

**Comment by phonebird** [comment]
@tdzl2003 请问这种是什么情况啊
1.本地安装A版本
2.用pushy uploadApk刚刚上传了A（确认手机上装的和上传的是同一个apk）
3.用pushy bundle更新一个版本关联至A
4.检查更新报{ expired: true, downloadUrl: null, ok: 1 }

**Comment by sunnylqm** [comment]
已通过编译时间戳解决
