### ISSUE TITLE
iOS-更新后js文件仍然是旧版

### ISSUE THREAD

**Issue by ghyzx** [reactnativecn/react-native-pushy#164]
背景：原生与RN混合的工程（原生为主，RN只涉及2个模块），
参照官网的快速指南操作，测试过程如下：
1.Archive后Export出adhoc的ipa包，通过蒲公英（https://www.pgyer.com/）发布一个基础版本；
2.修改js文件后，再Archive-->Export出adhoc的ipa包，上传到pushy，并发布一个热更新版本；
3.从蒲公英上下载并安装基础版本，提示有更新，下载完成后，无论是 现在重启应用以更新，还是 下次启动时，都有“您的应用版本已是最新”的提示，但 实际上js修改的内容并未更新；
不知哪里出了问题，恳请指点/协助，谢谢。

**Comment by ghyzx** [comment]
附：
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-update": "^5.0.0"

**Comment by sunnylqm** [comment]
修改js后不应该archive，应该通过pushy bundle

**Comment by ghyzx** [comment]
@sunnylqm  的确如此，问题解决了，非常感谢。

再请教另外一个问题，测试时，我都是Archive-->Export出adhoc的ipa包，上传pushy的，已经测试ok； 现在我要通过App Store发布了，（用来上传pushy的做比对的）Export出ipa包时选哪一种方式了，App Store？（再用adhoc好像不对了）

**Comment by sunnylqm** [comment]
选择对应的用途

**Comment by ghyzx** [comment]
按照正常的发布流程打包.ipa文件(Xcode中运行设备选真机或Generic iOS Device，然后菜单中选择Product-Archive)，然后运行如下命令
$ pushy uploadIpa <your-package.ipa>
即可上传ipa以供后续版本比对之用。
---------------
按照文档的说法，发布到App Store的，Export时应该是选择App Store的method了，只是这种方式暂时无法验证，所以向你确认一下，感谢回答。（初次使用，尚在摸索阶段，谢谢）

**Comment by xtianhe** [comment]
只是用来做版本比较而已,所以哪种方式无所谓 只要ipa的版本号没问题
