### ISSUE TITLE
iOS-switchVersionLater(hash)有时无效

### ISSUE THREAD

**Issue by ghyzx** [reactnativecn/react-native-pushy#165]
背景：原生与RN混合的工程（原生为主，RN只涉及2个模块），
参照官网的快速指南操作，测试过程如下：
1.下载完毕后，如果使用switchVersion(hash)，js文件正常更新（应用好像并没有重启--没有自动退出，还是说这里的重启用户感知不到？）；
2.下载完毕后，如果使用switchVersionLater(hash)，并且不进入RN编写相关的模块/页面，手动杀掉App重启后， js文件也正常更新；
3.下载完毕后，如果使用switchVersionLater(hash)，并且故意进入RN编写相关的模块/页面，第一次进入RN页面， js文件也正常更新，但是 手动杀掉App重启后，提示更新失败，已回滚，进入RN页面，确实已恢复成更新前的样子；
4.下载完毕后，如果使用switchVersionLater(hash)，并且故意进入RN编写相关的模块/页面，第一次进入RN页面， js文件也正常更新，第二次及以后进入，发现js文件已恢复成更新前的样子，手动杀掉App重启后，提示有更新；

不知哪里出了问题，恳请指点/协助，谢谢。

**Comment by ghyzx** [comment]
附：
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-update": "^5.0.0"

**Comment by huailiang** [comment]
这个怎么拒收啊。天天发 受不了了

发自我的 iPad

**Comment by ghyzx** [comment]
@huailiang  试试 右边的Unsubscribe 和 上边的Unwatch

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
