### ISSUE TITLE
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。

### ISSUE THREAD

**Issue by vip365** [reactnativecn/react-native-pushy#167]
在安装react-native-update时报了如下错误，怎么回事儿？
E:\InitProject>npm install --save react-native-update@5.x
npm WARN deprecated fs-promise@0.4.1: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> weak@1.0.1 install E:\InitProject\node_modules\weak
> node-gyp rebuild

E:\InitProject\node_modules\weak>if not defined npm_config_node_gyp (node "D:\nodejs\nodejs6.12.2\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\nodejs\nodejs6.12.2\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "D:\\nodejs\\nodejs6.12.2\\node.exe" "D:\\nodejs\\nodejs6.12.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\InitProject\node_modules\weak
gyp ERR! node -v v6.12.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
InitProject@0.0.1 E:\InitProject
`-- react-native-update@5.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.1 (node_modules\sane\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
在安装react-native-update时报了如下错误，怎么回事儿？

**Comment by sunnylqm** [comment]
这个报错不影响

**Comment by vip365** [comment]
OK
