### ISSUE TITLE
react-native 0.43.2 android下载差异化更新极慢

### ISSUE THREAD

**Issue by leeshare** [reactnativecn/react-native-pushy#168]
react-native 0.43.2 android下载差异化更新极慢
一个测试android app（react-native 0.43.2， react-native-update 4.0.6），就一个app.js，修改一行，提交后，在客户端检测到有新版，下载的 .pdiff文件大小是2K，
在更新时，差不多需要5秒。
而我一个正式app（也是 react-native 0.43.2），差异化文件 （.pdiff）文件大小是800K，在更新时跟踪了一下（原生代码），对于下载的文件，在本地比较时，一共要对460个文件进行比较（大部分都是 drawable-hdpi/** 等资源图片），每个文件需要4～5秒，一共算下来差不多要半小时。
难怪我每次执行下载，就没反应了，没有返回成功，也没有抛异常。

**Comment by leeshare** [comment]
我又对测试了一下目前最新版 react-native 0.51 
新建一个android测试app，就没有 0.43.2的文件，下载完差异文件几乎瞬间就回调成功了。

**Comment by onreadystatechange** [comment]
@leeshare 你好 我也遇到这个问题  请问你解决了吗

**Comment by sunnylqm** [comment]
已在5.1.x版本中优化
