### ISSUE TITLE
使用热更新示例，APP崩溃

### ISSUE THREAD

**Issue by icnz** [reactnativecn/react-native-pushy#169]
使用热更新提供的示例，其他都没有问题，就是在点击“点击这里更新”后，弹出提示框“检测到新的版本XXX，是否下载？”，然后点击“是”，APP就崩溃，直接退出了。
然后把调用代码注释掉之后，还是一样的问题。这是怎么回事儿？
checkUpdate = () => {
    checkUpdate(appKey).then(info => {
      if (info.expired) {
        Alert.alert('提示', '您的应用版本已更新,请前往应用商店下载新的版本', [
          {text: '确定', onPress: ()=>{info.downloadUrl && Linking.openURL(info.downloadUrl)}},
        ]);
      } else if (info.upToDate) {
        Alert.alert('提示', '您的应用版本已是最新.');
      } else {
        Alert.alert('提示', '检查到新的版本'+info.name+',是否下载?\n'+ info.description, [
          **{text: '是', onPress: ()=>{/*this.doUpdate(info)*/}}, //这里注掉了**
          {text: '否',},
        ]);
      }
    }).catch(err => { 
      Alert.alert('提示', '更新失败.');
    });
  };

**Comment by vip365** [comment]
又试着把更新提示的代码注掉，发现还是有提示，这是怎么回事儿？
checkUpdate = () => {
    checkUpdate(appKey).then(info => {
      if (info.expired) {
        Alert.alert('提示', '您的应用版本已更新,请前往应用商店下载新的版本', [
          {text: '确定', onPress: ()=>{info.downloadUrl && Linking.openURL(info.downloadUrl)}},
        ]);
      } else if (info.upToDate) {
        Alert.alert('提示', '您的应用版本已是最新.');
      } else {
        **//Alert.alert('提示', '检查到新的版本'+info.name+',是否下载?\n'+ info.description, [
          //{text: '是', onPress: ()=>{this.doUpdate(info)}},
          //{text: '否',},
        //]);
        # this.doUpdate(info);**
      }
    }).catch(err => { 
      Alert.alert('提示', '更新失败.');
    });
  };

**Comment by vip365** [comment]
将更新部分代码修改后，不崩溃了，但是什么事件都没有了，即点击没有任何效果。
checkUpdate = () => {
    checkUpdate(appKey).then(info => {
      if (info.expired) {
        Alert.alert('提示', '您的应用版本已更新,请前往应用商店下载新的版本', [
          {text: '确定', onPress: ()=>{info.downloadUrl && Linking.openURL(info.downloadUrl)}},
        ]);
      } else if (info.upToDate) {
        Alert.alert('提示', '您的应用版本已是最新.');
      } else {
        **Alert.alert('提示','react-native-pushy热更新');
        downloadUpdate(info).then(hash => {
          Alert.alert('提示hash', hash);
          switchVersion(hash);
        }).catch(err => { 
          Alert.alert('提示', '更新失败.');
        });**
      }
    }).catch(err => {
      Alert.alert('提示', '更新失败.');
    });
  };

**Comment by brusyy** [comment]
我都直接报更新失败。。。这个怎么会这样啊。 @vip365  你有遇到过吗？

**Comment by lailibo8** [comment]
@brusyy 我的是debug模式下，提示更新失败，release模式下，重新启动，版本被回滚

**Comment by chengxuwang** [comment]
@lailibo8 你好，你的回滚问题解决了吗，我也遇到了，安卓和ios都是退出任务后就被版本回滚

**Comment by lailibo8** [comment]
@chengxuwang  https://www.jianshu.com/p/9037e6344e92

**Comment by budiga** [comment]
我这也是，资源下载完成后就奔溃退出，提示‘app停止运行’。请问怎么解决

**Comment by sunnylqm** [comment]
历史问题，如新版本有问题请重开issue
