### ISSUE TITLE
apk版本都同一个  不同渠道包 如何初始化问题   

### ISSUE THREAD

**Issue by 52myu** [reactnativecn/react-native-pushy#17]
问题描述：
比如现在我有一个apk 1.0.0
     对应渠道  index    ----》 android.xml  ->   channelId='index'
     
                     index2     ----》 android.xml  ->   channelId='index2'
这会热更新如果一推   那么  则有其中一个渠道包   一直提示更新
这个怎么解决

**Comment by tdzl2003** [comment]
近期版本的packager貌似不能保证每次打出的bundle完全相同了。因此使用相同代码多次assembleRelease会导致问题。这一点我们还在寻找原因和准备pull-request。临时的四种解决方法（选择任意一种即可）：

A、不要使用react.gradle自动生成bundle包了，使用react-native bundle命令手动生成相同的jsbundle并打渠道包。这样可以保证多个渠道bundlejs一致，就可以共同完成热更新了。

B、如果渠道数较少，可以考虑为每个渠道创建一个应用，分别管理每个渠道的版本更新。

C、仅进行一次assembleRelease 通过APKTools反编译，修改manifest并重新签名的方式打包。可以写批处理脚本，也可以使用一些第三方工具。主流的多渠道打包工具大都是这样做的，这样也会比每个渠道分别打包快很多。

D、http://www.cnblogs.com/jhj117/p/4862282.html 这篇文章后面介绍了一种免签名添加渠道包的方案，原理是利用META-INF文件夹http://blog.csdn.net/shanjianxiliulc/article/details/51068297 这里有相应的实践代码。此方案应当也可以使用，不过有被第三方伪造渠道包的可能性。
