### ISSUE TITLE
IOS 更新成功但是退出整个APP重启还是旧版

### ISSUE THREAD

**Issue by a728384698** [reactnativecn/react-native-pushy#170]
当前更新更新成功，完全退出APP之后重新打开还是原来旧版。
![948fe1fc-44ee-436a-9555-fc6ca222698f](https://user-images.githubusercontent.com/7380874/34714072-3791d56a-f563-11e7-9fbe-cb617a47c25f.png)

**Comment by lailibo8** [comment]
@a728384698 同问此问题，你的解决没有，重新打开还是刚刚更新失败，版本被回滚

**Comment by a728384698** [comment]
我这边是用个人证书打包上传了IPA，企业证书改了签名发布，下载发布版之后2证书 不一样导致这个问题

**Comment by a728384698** [comment]
@lailibo8 我这边是用个人证书打包上传了IPA，企业证书改了签名发布，下载发布版之后2证书 不一样导致这个问题

**Comment by lailibo8** [comment]
@a728384698现在是debug模式更新没问题，就是release下走jsCodeLocation=[RCTHotUpdate bundleURL]，会更新失败，不知道如何才能正常

**Comment by basilbai** [comment]
同样的问题，请问有解决的办法吗

**Comment by lailibo8** [comment]
@basilbai 你的问题是什么

**Comment by kobexyq** [comment]
根据文档，是没有执行到markSuccess()方法，你看看你的代码的componentWillMount()方法有没有执行得到

**Comment by piaotiejun** [comment]
ios应用内给出提示更新信息，ios审核能过吗。。

**Comment by HeMa321** [comment]
这个问题解决了吗?怎么解决的

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
