### ISSUE TITLE
更新成功但是退出整个APP重启还是旧版

### ISSUE THREAD

**Issue by limintao** [reactnativecn/react-native-pushy#171]
进入APP是更新成功，想更新的东西也出来了，但是下次重启就又变回原来的了！

**Comment by sunnylqm** [comment]
1、不要使用debug版本
2、记住调用markSuccess

**Comment by limintao** [comment]
我是发布到应用商店的APP，不是debug版本； 而且我也调用了markSuccess；
![image](https://user-images.githubusercontent.com/24197663/34925118-42ce31d4-f9e2-11e7-812a-d7e94909e75b.png)

**Comment by sunnylqm** [comment]
具体rn和pushy版本？

**Comment by limintao** [comment]
"react-native": "0.44.1"；
"react-native-update": "^4.0.6",

**Comment by limintao** [comment]
@sunnylqm 
我在入口文件判断是否回滚也没有执行，但是更改的内容确实是变回原来的了！

我的"react-native": "0.44.1"；
"react-native-update": "^4.0.6"；

![image](https://user-images.githubusercontent.com/24197663/34970005-d0d01dba-faac-11e7-8e56-f49ce05604e3.png)

**Comment by sunnylqm** [comment]
看一下你的bundle url的配置

**Comment by limintao** [comment]
![image](https://user-images.githubusercontent.com/24197663/34970797-567f8eba-fab1-11e7-8a4e-0f44ae1199a1.png)

这些都是根据文档复制的
