### ISSUE TITLE
编译报错：找不到变量！

### ISSUE THREAD

**Issue by luoxiaodan0425** [reactnativecn/react-native-pushy#172]
@sunnylqm 
我根据文档一步一步走下来，结果在编译时报错！
![image](https://user-images.githubusercontent.com/24807591/34976389-65f573bc-fad1-11e7-9188-f4cd09544be7.png)
代码如下：
1.settings.gradle
![image](https://user-images.githubusercontent.com/24807591/34976432-95ae68c0-fad1-11e7-9b10-de0b1e34ba6b.png)
2.build.gradle
![image](https://user-images.githubusercontent.com/24807591/34976457-b238100e-fad1-11e7-9523-285e58b974fa.png)
3.MainApplication.java
![image](https://user-images.githubusercontent.com/24807591/34976529-f9cd5ece-fad1-11e7-9b10-a42f879676a4.png)

Rn 版本： 0.44.1
pushy：^4.0.6

**Comment by sunnylqm** [comment]
https://github.com/reactnativecn/react-native-pushy/blob/a9ffa4eefdf6ce287df19bec9944b5cc5112d0f7/docs/guide.md#配置bundle-urlandroid

**Comment by luoxiaodan0425** [comment]
![image](https://user-images.githubusercontent.com/24807591/34976690-a0e3660e-fad2-11e7-8fe2-208005e3377e.png)
我已经加入了bundleURl，就是因为加了这句话才报错的

**Comment by luoxiaodan0425** [comment]
@sunnylqm 
node版本v8.9.1

**Comment by sunnylqm** [comment]
你再仔细看看，加的不止一句话
