### ISSUE TITLE
混和APP热更新

### ISSUE THREAD

**Issue by xiebinJava** [reactnativecn/react-native-pushy#173]
请问下，RN与原生混合的APP能否用pushy进行热更新？

**Comment by ghyzx** [comment]
可以的，我的成功了

**Comment by xiebinJava** [comment]
请问下大神是怎么操作的？有没有demo啊？

**Comment by sunnylqm** [comment]
https://pushy.reactnative.cn/docs/api.html#android-%E6%96%B9%E6%B3%95
