### ISSUE TITLE
Android 更新失败。

### ISSUE THREAD

**Issue by brusyy** [reactnativecn/react-native-pushy#175]
RN0.44.0，RN-update 4.x，跟着教程下来，点击检查更新，提示，更新失败，log err，{“line”：333，“column”:45,"sourceURL":"index.android.bundle"}.这是为什么，也没有报错。就是检查不了更新，期间提示buildToolsVersion 太低，原来是23.0.1，我改为25.0.0了。可以打包，安装，但是就是不提示更新。 @sunnylqm

**Comment by sunnylqm** [comment]
历史问题，如新版本有问题请重开issue
