### ISSUE TITLE
pushy bundle --platform android

### ISSUE THREAD

**Issue by song6974272** [reactnativecn/react-native-pushy#179]
MacBook-Pro:FirstRN mi$ pushy bundle --platform android
Bundling with React Native version: 0.52.0
我降低版本至0.51.0后可以使用了 但是应用界面就变了 原来设置的圆角图标变形了 请问什么时候能够支持0.52.0？

**Comment by sunnylqm** [comment]
Fixed in https://github.com/reactnativecn/react-native-pushy/pull/205
