### ISSUE TITLE
小白求教，checkUpdate is read-only是什么问题呢？

### ISSUE THREAD

**Issue by lxc7923** [reactnativecn/react-native-pushy#18]
如题，有人知道吗？谢谢！
还有import cn.reactnative.modules.update.UpdateContext;
这个导包导不进来是为啥呢，前面的步骤都没有问题。

**Comment by tdzl2003** [comment]
能否贴下报错的详细截图（或调用栈）和对应的代码。

包“导不进来”也请贴下具体的报错。

**Comment by lxc7923** [comment]
请您看下这篇子，我把代码和错误都贴在里面了，谢谢了！
http://bbs.reactnative.cn/topic/2085/热更新js代码中只要导react-native-update包-运行时跳转rn界面就闪退

**Comment by tdzl2003** [comment]
RN 0.29+貌似不能被rnpm正确支持，这是rnpm的一个bug。近期会补充关于手动添加依赖的文档。

**Comment by sunnylqm** [comment]
@tdzl2003 现在rn自己也整合了rnpm，不知道react-native link能不能正确链接？
