### ISSUE TITLE
Xcode 手动添加了 libRCTHotUpdate.a 后就编译失败

### ISSUE THREAD

**Issue by liyanfei1004774105** [reactnativecn/react-native-pushy#180]

**Comment by liyanfei1004774105** [comment]
Xcode 版本9.2  "react": "^16.0.0-alpha.12",
    "react-native": "^0.46.0"

**Comment by ytt123** [comment]
#import <RCTHotUpdate/RCTHotUpdate.h>

**Comment by tdzl2003** [comment]
编译失败的报错信息是什么？

**Comment by Fyus1201** [comment]
添加libRCTHotUpdate.a之后报错Linker command failed with exit code 1 (use -v to see invocation)

**Comment by Fyus1201** [comment]
看报错似乎是重复引用，不引用可能也可以起来

**Comment by sunnylqm** [comment]
请尝试新版本，如果还有问题请重开issue
