### ISSUE TITLE
热更新，下载太慢

### ISSUE THREAD

**Issue by longmingfeng** [reactnativecn/react-native-pushy#181]
既然是热更新，每次更新也就是几KB的事儿，为什么从下载到下载完毕，需要那么长时间？至少2分钟。。。
![default](https://user-images.githubusercontent.com/26614867/35965531-1efc9a12-0cf6-11e8-851e-af152936a4c1.png)

**Comment by qzw631486894** [comment]
下载半天没反应，也看不到进度

**Comment by erichua23** [comment]
抓包看一下访问的地址，然后查一下网络情况呢

**Comment by longmingfeng** [comment]
调试，把对应的三个URL,，单独去浏览器打开下载，非常快，不到1S就下载完了。。。但在应用中，就要很久，至少三分钟。。。

**Comment by sunnylqm** [comment]
https://github.com/reactnativecn/react-native-pushy/issues/116

**Comment by longmingfeng** [comment]
#116，按这个来，修改默认下载的前后顺序，是可以很快，不过这样，客户就需要更多的流量了

**Comment by tdzl2003** [comment]
Android 由于图片较多而导致更新很慢的问题在最新版本解决了，可以关注一下。
