### ISSUE TITLE
ios 混合开发,昨天晚上测试成功的ipa 今天调到 Rn 界面就闪退,谁能提示一下什么原因?

### ISSUE THREAD

**Issue by liyanfei1004774105** [reactnativecn/react-native-pushy#183]
我的流程是这样,
1,react-native bundle --entry-file ./index.js --bundle-output ./ios/bundle/index.jsbundle --platform ios --assets-dest ./ios/bundle --dev false   打离线包
2,将离线包添加到远程应用,
3,打包

  jsCodeLocation=[RCTHotUpdate bundleURL];

昨晚打了好几个包都可以,今天怎么试都不行

**Comment by LiuYuHangNB** [comment]
@liyanfei1004774105 兄弟能问一下2,将离线包添加到远程应用,是什么操作么?

**Comment by sunnylqm** [comment]
请按文档流程操作
