### ISSUE TITLE
使用了react-native-navigation后，如何继承热更新

### ISSUE THREAD

**Issue by chenyao6134** [reactnativecn/react-native-pushy#187]
项目使用了[react-native-navigation](https://wix.github.io/react-native-navigation/#/)后，如何继承这个热更新。

**Comment by solaronke** [comment]
请问一下，你解决了这个问题了吗？我也是使用react-native-navigation，然后用pushy就提示undefined is not an object(evaluating HotUpdate.downloadRootDir)这个错误

**Comment by chenyao6134** [comment]
不用这个热更新了，你可以继承微软的code-PUSH

**Comment by tdzl2003** [comment]
没有什么特殊的地方，按文档集成即可

**Comment by tdzl2003** [comment]
https://github.com/reactnativecn/react-native-pushy/issues/207 可以参考#207
