### ISSUE TITLE
Android打包报错

### ISSUE THREAD

**Issue by zhuchaoming** [reactnativecn/react-native-pushy#188]
Android打包报错:

Execution failed for task ':react-native-update:compileReleaseNdk'.
> com.android.ide.common.process.ProcessException: Error while executing 'E:\Android\android-ndk-r10e\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=E:\code\ReactNative\demo\node_modules\react-native-update\android\build\intermediates\ndk\release\Android.mk APP_PLATFORM=android-23
NDK_OUT=E:\code\ReactNative\demo\node_modules\react-native-update\android\build\intermediates\ndk\release\obj NDK_LIBS_OUT=E:\code\ReactNative\demo\node_modules\react-native-update\android\build\intermediates\ndk\release\lib APP_ABI=armeabi-v7a,x86}

**Comment by roy2651** [comment]
找到ndk路径，写到local.properties

**Comment by zhuchaoming** [comment]
写了，没用。我在另一台电脑上配置就没问题。然后再把代码拷贝的这台电脑上，还是这样的错误。

**Comment by roy2651** [comment]
https://github.com/reactnativecn/react-native-pushy/blob/master/docs/faq_advance.md @zhuchaoming
