### ISSUE TITLE
packageVersion 这个api为什么每次都不更新

### ISSUE THREAD

**Issue by roy2651** [reactnativecn/react-native-pushy#189]
我每次更新完了以后packageVersion这个还是之前的版本的名称，并没有更新到最新的版本名称，是不是只有在checkupdate info里面的info.name @sunnylqm  大神能帮忙看一下

**Comment by zhuiye** [comment]
同样的问题..

**Comment by roy2651** [comment]
packageVersion读取的是build.gradle这个里面的versionName，不知道是不是，可以测试一下 @zhuiye
