### ISSUE TITLE
如何下载1.0.x版本？

### ISSUE THREAD

**Issue by lesliesam** [reactnativecn/react-native-pushy#19]
你好，
说明文档里面提到：“因为React Native调整了okhttp的依赖，对于0.27以上版本的React Native，请安装1.1.x版本，对于0.26及以前版本，请安装1.0.x版本。”

我在package.json里面写1.0.5仍然下载了1.1.2版本，请问如何下载到1.0.x的版本？

谢谢！

**Comment by sunnylqm** [comment]
npm install react-native-update@1.0.x --save

**Comment by lesliesam** [comment]
重新加你们的控件是可以的，但是一旦写到package.json里面之后，第二个人同步之后再运行npm install就会去下载1.1.2版本。
我们team好几个人，这个问题怎么解决？

**Comment by sunnylqm** [comment]
@tdzl2003 应该用大版本隔开
@lesliesam 在package.json中去掉^符号

**Comment by lesliesam** [comment]
问题解决了，谢谢！
