### ISSUE TITLE
热更新发布，包版本序号为空

### ISSUE THREAD

**Issue by ChrisDowney1996** [reactnativecn/react-native-pushy#192]
你好，我发布新的热更新版本的时候，packageId为空，没有文档上说的列表。
λ pushy bundle --platform android
Bundling with React Native version:  0.55.3
Scanning folders for symlinks in D:\idea-workspace\react-native\HelloWorld\node_modules (56ms)
Loading dependency graph, done.
bundle: Writing bundle output to: D:\idea-workspace\react-native\HelloWorld\build\intermedia\android\index.bundlejs
bundle: Done writing bundle output
bundle: Copying 10 asset files
bundle: Done copying assets
Packing
Bundled saved to: build/output/android.1524741088743.ppk
Would you like to publish it?(Y/N) y
  Uploading [================================================================================] 100% 0.0sEnter version name: 1.0.0
Enter description: TEST
Enter meta info: {"ok":1}
Version published: 35112
Would you like to bind packages to this version?(Y/N) y

Total 0 packages.
Enter packageId:

**Comment by sunnylqm** [comment]
uploadApk first

**Comment by ChrisDowney1996** [comment]
好的。谢谢
