### ISSUE TITLE
我的 react native 版本 0.55。安卓js热更新，下次更新无效。立即重启更新，当时更新成功，杀掉app重新打开，更新失效了

### ISSUE THREAD

**Issue by xiaogaofudao** [reactnativecn/react-native-pushy#194]
我的 react native 版本 0.55。安卓js热更新，下次更新无效。立即重启更新，当时更新成功，杀掉app重新打开，更新失效了。并且不能再次检测到新版本

**Comment by hellosuperX** [comment]
同样的效果。请问解决了吗

**Comment by xiaogaofudao** [comment]
解决了，react native link 之后，需要手动添加点代码。具体看这篇文档 https://github.com/reactnativecn/react-native-pushy/blob/master/docs/guide.md
里面的 配置 bundle url

**Comment by xiaogaofudao** [comment]
@hellosuperX 
配置Bundle URL(iOS)
在工程target的Build Phases->Link Binary with Libraries中加入libz.tbd、libbz2.1.0.tbd

在你的AppDelegate.m文件中增加如下代码：

// ... 其它代码

#import "RCTHotUpdate.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if DEBUG
  // 原来的jsCodeLocation保留在这里
  jsCodeLocation = ..........
#else
  // 非DEBUG情况下启用热更新
  jsCodeLocation=[RCTHotUpdate bundleURL];
#endif
  // ... 其它代码
}
配置Bundle URL(Android)
0.29及以后版本：在你的MainApplication中增加如下代码：

// ... 其它代码

import cn.reactnative.modules.update.UpdateContext;
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected String getJSBundleFile() {
        return UpdateContext.getBundleUrl(MainApplication.this);
    }
    // ... 其它代码
  }
}

**Comment by xinwanggit** [comment]
更新后,打开app,需要用markSuccess标记,
    componentWillMount(){
        if (isFirstTime) {
           markSuccess()
        } else if (isRolledBack) {
            Alert.alert('提示', '刚刚更新失败了,版本被回滚.');
        }
    }
