### ISSUE TITLE
react-native-pushy@5.x和react-native-firebase集成之后的BUG

### ISSUE THREAD

**Issue by hnliyuan** [reactnativecn/react-native-pushy#195]
经过充分的测试
react-native-pushy和react-native-firebase3.3 && react-native-firebase4.0.6
热更新下载完文件成功，开始switchVersion的时候会报错崩溃。
"react": "16.0.0",
"react-native": "0.51.0",
"react-native-pushy":5.x
react-native-firebase3.3
react-native-firebase4.0.6
原谅我不会原生无法定位，作者如果有时间请帮忙解决一下，

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue，最好附上崩溃前后的adb logcat输出
