### ISSUE TITLE
安卓 pushy 原生包更新问题，js bundle 热更新没问题，原生包如何更新

### ISSUE THREAD

**Issue by xiaogaofudao** [reactnativecn/react-native-pushy#197]
初始原生包，版本 1.0， version code 1。 uploadApk 一个新包，版本为 1.1 version code 2 。新包上传成功。1.0和1.1 两个版本同时存在，打开 1.0 的app 不提示升级。pushy后台删除 1.0 的安装包。进入1.0的app返回 info.expired true。但是 downloadUrl 为 null。问题出在什么地方，求助大神

**Comment by sunnylqm** [comment]
downloadUrl是在网站上设定的

**Comment by xiaogaofudao** [comment]
@sunnylqm 额刚发现隐藏有点深。多谢了

**Comment by lhjzzu** [comment]
你好，根据你的案例，假如我不把1.0的包删除，那么是不是我手机上装的1.0的包永远都就不会返回info.expried为true。即使我已经上传了1.1版本的包?

**Comment by littleseven007** [comment]
> downloadUrl是在网站上设定的

哪个网站啊？ 没找到呢

**Comment by shareven** [comment]
藏的太深了，我搞了好久才找到，这是教程https://zhuanlan.zhihu.com/p/106468918

**Comment by shareven** [comment]
下载地址在这设置
<img width="775" alt="屏幕快照 2020-02-12 下午4 53 37" src="https://user-images.githubusercontent.com/25793040/74318506-5f838f00-4db8-11ea-8c34-7da9e4de56dc.png">
