### ISSUE TITLE
android 4.4报错   dlopen failed: cannot locate symbol "stderr" referenced by "librnupdate.so" ...

### ISSUE THREAD

**Issue by phomel** [reactnativecn/react-native-pushy#198]
有人知道怎么解决么 .  给点建议  谢谢了

**Comment by xiaogaofudao** [comment]
同问，Android 5.1 同样报这个错误，找不到 librnupdate.so。检查热更新的代码注释掉，就可以运行

**Comment by xiaogaofudao** [comment]
Android 6.0 及以上 没问题， 求大神解答

**Comment by midas-gufei** [comment]
低版本没有试过，目前产品都是基于高版本去开发的。

**Comment by xiaogaofudao** [comment]
找到原因，ndk 版本太高导致。ndkr10e 这个版本即可。亲测，4.4 及以上版本都支持。ndk17 6.0及以上支持。 ndk16 5.0 及以上支持

**Comment by midas-gufei** [comment]
我当初的编译环境就是r10

**Comment by phomel** [comment]
为什么换低版本ndk编译后  我的更新走了不止一次 应用不断重启多次(4.4问题) .  感觉好坑 @xiaogaofudao

**Comment by tdzl2003** [comment]
@phomel 可能是因为运行的apk和uploadApk上传的不是同一个

**Comment by tdzl2003** [comment]
@phomel 设备上运行的apk，和之前用uploadApk上传的apk，精确的是同一个文件吗？
