### ISSUE TITLE
pushy upload apk 错误

### ISSUE THREAD

**Issue by kobexyq** [reactnativecn/react-native-pushy#199]
when I run the command as 'pushy uploadApk android/app/build/outputs/apk/app-release.apk'.
and when it upload finishing,it shows this error to me, and annoys me:

Error: Validation error:
at E:\xxxxxx\TestProject\node_modules\react-native-update\local-cli\lib\api.js:8:27
    at Generator.next (<anonymous>)
    at step (E:\xxxxxx\TestProject\node_modules\react-native-update\local-cli\lib\api.js:82:191)
    at E:\xxxxxx\TestProject\node_modules\react-native-update\local-cli\lib\api.js:82:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

And I want to know why will append this error? what is the problem ? 
And now I hope someone can give me a hand.........

**Comment by sunnylqm** [comment]
https://github.com/reactnativecn/react-native-pushy/issues/31
