### ISSUE TITLE
pushy diff

### ISSUE THREAD

**Issue by fimbit** [reactnativecn/react-native-pushy#20]
请问pushy diff怎么使用
pushy diff origin-path next-path --output output-path
通过上面的格式出错，出现信息：
/Users/git/Documents/react-native/RNDF/node_modules/yazl/index.js:350
  metadataPath = metadataPath.replace(/\\/g, "/");
                             ^

TypeError: Cannot read property 'replace' of null
    at validateMetadataPath (/.../node_modules/yazl/index.js:350:30)

**Comment by tdzl2003** [comment]
能否看一下/Users/git/Documents/react-native/RNDF/node_modules/yazl/package.json的版本？ 可能是此插件在npm上更新了一个不兼容但没有正确修改版本号的更新

**Comment by tdzl2003** [comment]
npm install yazl@2.3.0 --save-exact 试试，可能是yazl更新了一个不兼容的版本。

**Comment by tdzl2003** [comment]
稍后我也会修改下pushy的package.json来避免这个问题

**Comment by fimbit** [comment]
试过了npm install yazl@2.3.0 --save-exact，还是出现一样的错误，
我输入的命令是：
pushy diff "./build/output/ios/release/rndf-1.0-1.ppk" "./build/output/ios/release/rndf-1.0-2.ppk" --output ./build/output/ios/release/patch/rndf.patch

**Comment by tdzl2003** [comment]
你好，可否提供下你的完整package.json？我尽量在一样的环境下去做测试。

**Comment by tdzl2003** [comment]
还有确定下，您的Node.js及npm版本

**Comment by fimbit** [comment]
mac上：
node:v5.3.0
npm:3.9.2
package.json：
[
[package.json.zip](https://github.com/reactnativecn/react-native-pushy/files/417571/package.json.zip)

](url)
麻烦了，我也试下其他电脑。

**Comment by fimbit** [comment]
试过另外一台mac,也出现一样的错误。
rn版本：0.30

**Comment by sunnylqm** [comment]
@fimbit 请尝试最新版本看是否已修复
