### ISSUE TITLE
React Native 打出来的离线包名字有要求吗？

### ISSUE THREAD

**Issue by huangzhifei** [reactnativecn/react-native-pushy#206]
离线包名字一定要是main.bundle这个吗？

**Comment by sunnylqm** [comment]
和原生代码里一致

**Comment by huangzhifei** [comment]
@sunnylqm 原生代码是通过 jsCodeLocation = [RCTHotUpdate bundleURL] 这样来加载的，并没有明确指出名字，查看里面的具体代码，最后会可能会返回main.jsbundle，但是前面有一个逻辑是有可能返回一个动态拼接的bundleURL，所以不是很确定。

**Comment by huangzhifei** [comment]
问题已经解决，index.jsbundle
