### ISSUE TITLE
上传ipa发生错误

### ISSUE THREAD

**Issue by chenzhenhu** [reactnativecn/react-native-pushy#210]
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:140:9)
    at Object.fs.exists (fs.js:218:3)

**Comment by tdzl2003** [comment]
您好，请完善一下信息：

1. 您的node版本、npm版本、react-native版本、react-native-update版本
2. 具体执行的命令和完整的输出

**Comment by sunnylqm** [comment]
cert-downloader在node10下的兼容问题，按照文档使用yarn安装可以绕过这个问题
