### ISSUE TITLE
热更新完后APP自动重启是否可以？

### ISSUE THREAD

**Issue by icnz** [reactnativecn/react-native-pushy#211]
热更新完后APP能够自动重启？codePush有一个reatartApp（），据说是可以的。
咱们程序是否可以？
还是说根本是不能实现的？

**Comment by tdzl2003** [comment]
switchVersion会切换版本并自动重启。

**Comment by yangsamuellu** [comment]
switchVersion会切换版本并自动重启。 ---现在的版本又不会自动重启了啊。
"react": "16.6.3",
"react-mixin": "^4.0.0",
"react-native": "^0.58.4",
"react-native-update": "^5.1.6",
又重现了啊。。。  @tdzl2003

**Comment by tdzl2003** [comment]
@yangsamuellu 平台是iOS还是Android？

**Comment by yangsamuellu** [comment]
@tdzl2003 android的，并且，debug 是好的，release 有问题。

**Comment by huqiangqaq** [comment]
> release

我也遇到这个问题，请问你解决了吗

**Comment by huqiangqaq** [comment]
@tdzl2003 @yangsamuellu

**Comment by luohaoxin** [comment]
我也碰到了，没法自动重启，rn:0.52.0    pushy:5.1.8

**Comment by 007jerry** [comment]
这个问题还是没有解决方案吗？

**Comment by sunnylqm** [comment]
试下5.2.8版本，应该解决了重启的问题

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
