### ISSUE TITLE
IOS运行pushy uploadIpa上传基础版本时报错

### ISSUE THREAD

**Issue by Code4GL** [reactnativecn/react-native-pushy#212]
在集成好Android热更新之后，并能正常使用了；接着集成IOS，配置好之后打包上传第一步就报错了，不知道什么原因，求助！
版本：
"react-native": "0.52.2",
"react-native-update": "^5.0.0"

运行：pushy uploadIpa /Users/xxx/Desktop/app/xxx.ipa
报错：
Error: Command failed: openssl smime -in /var/folders/w6/9m914c_15zq6dqppprjcldq80000gn/T/1531462684097.7786/Payload/xxx.app/embedded.mobileprovision -inform der -verify -CAfile /var/folders/w6/9m914c_15zq6dqppprjcldq80000gn/T/AppleIncRootCertificate.pem
Verification failure
140735815533448:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/rsa/rsa_pk1.c:105:
140735815533448:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/rsa/rsa_eay.c:707:
140735815533448:error:21071069:PKCS7 routines:PKCS7_signatureVerify:signature failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/pkcs7/pk7_doit.c:1117:
140735815533448:error:21075069:PKCS7 routines:PKCS7_verify:signature failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/pkcs7/pk7_smime.c:412:

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by sunnylqm** [comment]
请尝试新版本，如果还有问题请重开issue
