### ISSUE TITLE
ios 上传更新包packageID填什么?

### ISSUE THREAD

**Issue by LiuYuHangNB** [reactnativecn/react-native-pushy#215]
macdeiMac:RN5.5iOS mac$ pushy bundle --platform ios
Bundling with React Native version:  0.55.4
Scanning folders for symlinks in /Users/mac/Desktop/RN5.5iOS/node_modules (35ms)
Loading dependency graph, done.
bundle: Writing bundle output to: /Users/mac/Desktop/RN5.5iOS/build/intermedia/ios/index.bundlejs
bundle: Done writing bundle output
Packing
Bundled saved to: build/output/ios.1533803524436.ppk
Would you like to publish it?(Y/N) y
  Uploading [==========================================================================================] 100% 0.0s
Enter version name: 1.0.3
Enter description: 测试1.0.3
Enter meta info: {"ok":1}
Version published: 41012
Would you like to bind packages to this version?(Y/N) Y
20634) 1.0.2(normal) (newest)

Total 1 packages.
Enter packageId: uploadIpa first
Enter packageId: uploadApk first
Enter packageId: uploadppk first
Enter packageId:

**Comment by sunnylqm** [comment]
`20634)` 1.0.2(normal) (newest)
