### ISSUE TITLE
真机release模式下一运行就crash在这个地方

### ISSUE THREAD

**Issue by yuhangjob** [reactnativecn/react-native-pushy#217]
![2018-08-10 1 56 03](https://user-images.githubusercontent.com/16233156/43941069-375b78d2-9ca5-11e8-882b-d3f605a03424.png)

##### Appdelegate中这样写的
#if DEBUG
    jsCodeLocation = [NSURL
                    URLWithString:@"http://localhost:8081/index.bundle?platform=ios"];
#else
//    jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"index" withExtension:@"jsbundle"];
    jsCodeLocation=[RCTHotUpdate bundleURL];
#endif

改成
#if DEBUG
    jsCodeLocation = [NSURL
                    URLWithString:@"http://localhost:8081/index.bundle?platform=ios"];
#else
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"index" withExtension:@"jsbundle"];
#endif
就不会报错

**Comment by sunnylqm** [comment]
请先尝试新版本，还有问题的话请重开issue
