### ISSUE TITLE
pushy login 无法执行

### ISSUE THREAD

**Issue by tairuichen** [reactnativecn/react-native-pushy#22]
装了react-native-update  但是在当前项目下打 
pushy login
没有找到命令
-bash: pushy: command not found

**Comment by sunnylqm** [comment]
没有安装react-native-update-cli

**Comment by coldsmalltwo** [comment]
➜  PPM git:(master) ✗ pushy login
zsh: command not found: pushy
➜  PPM git:(master) ✗ npm list -g --depth 0
/usr/local/Cellar/node/9.11.1/lib
├── react-native-cli@2.0.1
├── react-native-update-cli@0.1.0
└── yarn@1.9.4

@sunnylqm

**Comment by sunnylqm** [comment]
@coldsmalltwo 默认全局模块应该是装在/usr/local 而且这个路径是在PATH中的
用npm config list 检查配置文件里的prefix是不是修改过了
无论改成什么路径，总之路径应该写到PATH中
