### ISSUE TITLE
markSuccess何时调用

### ISSUE THREAD

**Issue by qingjiaowochengzd** [reactnativecn/react-native-pushy#220]
在每次更新完毕后的首次启动时，isFirstTime常量会为true。 你必须在应用退出前合适的任何时机，调用markSuccess，否则应用下一次启动的时候将会进行回滚操作。 这一机制称作“反触发”，这样当你应用启动初期即遭遇问题的时候，也能在下一次启动时恢复运作。

我应该在什么时候调用markSuccess，目前是我应用一更新，release版本就闪退，之后一直进不去，debug版本没问题。
我在app.js文件中

componentWillMount(){
    console.log(isFirstTime)
    if (isFirstTime) {
       markSuccess()
    } else if (isRolledBack) {
      Alert.alert('提示', '刚刚更新失败了,版本被回滚.');
    }
  }

**Comment by FokingGit** [comment]
遇到同样的问题，以下是报错日志
java.lang.RuntimeException:com.facebook.react.devsupport.JSException: Unexpected token ':'. Expected a parameter pattern or a ')' in parameter list. (/data/user/0/com.xiaoxianmanager/files/_update/FqEQqxU2kcFXHCTnWr8bn4or8ZMd/index.bundlejs:306)

**Comment by FokingGit** [comment]
> > 遇到同样的问题，以下是报错日志
> > java.lang.RuntimeException：com.facebook.react.devsupport.JSException：意外的标记'：'。预期参数列表中的参数模式或'）'。（/data/user/0/com.xiaoxianmanager/files/_update/FqEQqxU2kcFXHCTnWr8bn4or8ZMd/index.bundlejs:306）
> 
> 请问您问题怎么解决的呢？

问题已经解决了
解决方式：保证pushy上的apk和安装的apk是同一个
