### ISSUE TITLE
[RN 0.56.0] `requiresMainQueueSetup` needed for main queue setup, with constantsToExport

### ISSUE THREAD

**Issue by steven-ma** [reactnativecn/react-native-pushy#225]
- 操作系统： mac
- 平台：ios
- 集成后启动应用会有以下warinning
Module RCTHotUpdate requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by Mikelulu** [comment]
+1

**Comment by liuxiaofan** [comment]
+1

**Comment by Amos729** [comment]
The same issue to me, how does it solve?

**Comment by Amos729** [comment]
> +1

Add `requiresMainQueueSetup` in `RCTHotUpdate.m` may work for you
