### ISSUE TITLE
hot-update successfully,but the icon and image of the project is blurred。why？

### ISSUE THREAD

**Issue by yutianhaijiao** [reactnativecn/react-native-pushy#227]

**Comment by yutianhaijiao** [comment]
maybe， I found the reason ，the  resizeMode default value is 'cover'.but mine project react-native version is 0.54 ,so the value of the resizeMode what I set is 'center', when update successfull, it is become 'cover'.so, what Can i do?

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
