### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by YufengHu123** [reactnativecn/react-native-pushy#228]
![image](https://user-images.githubusercontent.com/16814072/48000353-25045e80-e140-11e8-8f38-7689547fdfb6.png)
who can help me?thx

**Comment by runnin86** [comment]
> ![image](https://user-images.githubusercontent.com/16814072/48000353-25045e80-e140-11e8-8f38-7689547fdfb6.png)
> who can help me?thx

资源文件不要有中文名就好了
