### ISSUE TITLE
引入热更新后报错 undefined is not an object(evaluating HotUpdate 'HotUpdate.downloadRootDir')

### ISSUE THREAD

**Issue by tianyewai** [reactnativecn/react-native-pushy#232]
我的版本是：
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-update": "^5.1.3",

看过issues/74 的安卓兄弟的问题，他手动link解决了，我手动link并且重新编译还是这样。求解答啊！

**Comment by sunnylqm** [comment]
请试用最新版本，并再对照文档检查，如果还有问题请重开issue
