### ISSUE TITLE
无法找到模块“react-native-update”的声明文件。

### ISSUE THREAD

**Issue by Dorisfeng** [reactnativecn/react-native-pushy#235]
依赖
"react-native": "0.57.7",
  "react-native-update": "^5.1.4"
按照步骤来的，其他都没问题，就是最后使用的时候
import { checkUpdate}  from 'react-native-update'
提示
![image](https://user-images.githubusercontent.com/31895359/49717171-17874a80-fc91-11e8-97db-9350c0466871.png)

**Comment by sunnylqm** [comment]
https://bbs.reactnative.cn/topic/6164/%E5%BC%95%E5%85%A5%E7%83%AD%E6%9B%B4%E6%96%B0%E7%9A%84js%E4%BB%A3%E7%A0%81-%E6%8A%A5%E9%94%99/2
