### ISSUE TITLE
下载的index.bundlejs 文件里面有问题

### ISSUE THREAD

**Issue by Smart-XiaoLeiGe** [reactnativecn/react-native-pushy#236]
![snip20181215_37](https://user-images.githubusercontent.com/1797012/50039541-167a6280-006f-11e9-8da6-5e99852befd5.png)
![img_0360](https://user-images.githubusercontent.com/1797012/50039550-36118b00-006f-11e9-9982-9abe4a08fd47.PNG)

感觉是pushy bundle --platform 这个命令的问题

**Comment by Smart-XiaoLeiGe** [comment]
@sunnylqm @lvbingru @Abreto @geniuslinchao 
各位大神，下周就要给团队share，能否看一下这个问题？

**Comment by Smart-XiaoLeiGe** [comment]
@All

**Comment by sunnylqm** [comment]
debug版本是不能使用热更新的

**Comment by Smart-XiaoLeiGe** [comment]
好的，我试一下release的
