### ISSUE TITLE
热更新之后启动应用崩溃  release包

### ISSUE THREAD

**Issue by Txiaomo** [reactnativecn/react-native-pushy#237]
报错如下------   求解....
com.facebook.react.devsupport.JSException: Unexpected token '}'. Expected ')' to end a argument list. (/data/user/0/com.hotupdatedemo/files/_update/FunQGXAKCin5-BOwdUowKVxZTgTw/index.bundlejs:339)

**Comment by a1005342094** [comment]
问题解决了吗，我也遇到过

**Comment by lihao410** [comment]
+1

**Comment by lihao410** [comment]
我的直接提示应用终止运行

**Comment by Txiaomo** [comment]
> 问题解决了吗，我也遇到过

还没有解决~ 用了reactnative中文网的热更新了

**Comment by sunfan1** [comment]
怎么解决的。。。。。

**Comment by sunfan1** [comment]
这个热更新问题太多了。。时不时遇到一些问题！！

**Comment by sunnylqm** [comment]
请先尝试新版本，还有问题的话请重开issue
