### ISSUE TITLE
热更新图片无法显示

### ISSUE THREAD

**Issue by horou-dsk** [reactnativecn/react-native-pushy#239]
热更新后不带@2x 和@3x后缀的图片不显示

**Comment by tdzl2003** [comment]
平台是iOS还是Android?

Android近期修复了一个可能导致存在重复图片文件时图片有时候图片显示不出来的问题，可以尝试看一下5.1.6版本（需要重新打原生包）

**Comment by sunnylqm** [comment]
历史问题，如新版本有问题请重开issue
