### ISSUE TITLE
运行npm install --save react-native-update失败

### ISSUE THREAD

**Issue by phonebird** [reactnativecn/react-native-pushy#24]
你好，我每次运行上面这个命令都失败，报错如下，请问是什么原因？该怎么解决？
D:\ASProject\phonebird\trunk\phonebird>npm config set registry https://registry.
npm.taobao.org --global
D:\ASProject\phonebird\trunk\phonebird>npm config set disturl https://npm.taobao
.org/dist --global
D:\ASProject\phonebird\trunk\phonebird>npm install --save react-native-update

> node-bsdiff@0.1.4 install D:\ASProject\phonebird\trunk\phonebird\node_modules\
node-bsdiff
> node-gyp rebuild
D:\ASProject\phonebird\trunk\phonebird\node_modules\node-bsdiff>if not defined n
pm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-
bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebui
ld )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  main.cc
..\src\main.cc(111): warning C4267: “=”: 从“size_t”转换到“unsigned int”，
可能丢失数据 [D:\
ASProject\phonebird\trunk\phonebird\node_modules\node-bsdiff\build\bsdiff.vcxpr
oj]
  bsdiff.c
  bzlib.c
  compress.c
  crctable.c
  randtable.c
..\src\bzlib\compress.c(205): warning C4244: “=”: 从“__int64”转换到“Int32”
，可能丢失数据 [
D:\ASProject\phonebird\trunk\phonebird\node_modules\node-bsdiff\build\bsdiff.vc
xproj]
  blocksort.c
  huffman.c
  decompress.c
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_lo
ad_hook.c(34): error C2373: “__pfnDliNotifyHook2”: 重定义；不同的类型修饰符 [D
:\ASProject\p
honebird\trunk\phonebird\node_modules\node-bsdiff\build\bsdiff.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: 参见“__pfnDliNotifyHook2”的声明
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\ASProject\phonebird\trunk\phonebird\node_modules\node-bsdiff
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native-update"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! node-bsdiff@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-bsdiff@0.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-bsdiff package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-bsdiff
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-bsdiff
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ASProject\phonebird\trunk\phonebird\npm-debug.log

**Comment by sunnylqm** [comment]
你需要安装visual studio

**Comment by phonebird** [comment]
你好，我已经安装了visual studio2015了，是因为node-gyp版本不对吗？ @sunnylqm

**Comment by sunnylqm** [comment]
有运行这个吗
npm config set msvs_version 2015 --global

**Comment by phonebird** [comment]
已经运行了，电脑也重启过了

**Comment by sunnylqm** [comment]
vs中确认安装了windows sdk吗（8.1和10两个版本都要装）

**Comment by phonebird** [comment]
也都安装了，还是不行

**Comment by sunnylqm** [comment]
抱歉拖了这么久。可以尝试下目前的最新版本  npm i https://github.com/reactnativecn/react-native-pushy.git --save @phonebird

**Comment by xiaoqian9** [comment]
@sunnylqm 你好，我也遇到了和楼主相同的问题，安装你说的，安装了最新的版本，现在允许 react-native run-android 的时候提示 No such file or directory。
请问该怎么解决。。。
详细错误提示：
D:\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\src\main\jni\DownloadTask.c:107:1 : opening dependency file D:\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\build\intermediates\ndk\release\obj/local/armeabi-v7a/objs/rnupdate/D_\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\src\main\jni\DownloadTask.o.d: No such file or directory
Unknown source file : compilation terminated.
Unknown source file : make.exe: *** [D:\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\build\intermediates\ndk\release\obj/local/armeabi-v7a/objs/rnupdate/D_\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\src\main\jni\DownloadTask.o] Error 1

**Comment by sunnylqm** [comment]
@xiaoqian9 嗯，github的版本有个预编译的过程跳过了，所以不能正常运行。@tdzl2003 尽快发到npm上？

**Comment by xiaoqian9** [comment]
@tdzl2003 拜托了，邓大大~~

**Comment by wuxingjiang** [comment]
楼主问题解决了么？

**Comment by phonebird** [comment]
我把node-gyp版本升级了就好了 @wuxingjiang

**Comment by xiaoqian9** [comment]
@phonebird 升级的语句可以共享下么。。。
我执行 `npm install -g node-gyp` 不管用呢。。

**Comment by xiaoqian9** [comment]
升级node-gyp之后，提示 No such file or directory
错误详细：
`:react-native-update:compileReleaseNdk
D:\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\src\main\jni\DownloadTask.c:107:1 : opening dependency file D:\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\build\intermediates\ndk\release\obj/local/armeabi-v7a/objs/rnupdate/D_\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\src\main\jni\DownloadTask.o.d: No such file or directory
Unknown source file : compilation terminated.
Unknown source file : make.exe: *** [D:\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\build\intermediates\ndk\release\obj/local/armeabi-v7a/objs/rnupdate/D_\app-develop\kdys-web\employeesmanager\node_modules\react-native-update\android\src\main\jni\DownloadTask.o] Error 1

:react-native-update:compileReleaseNdk FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-update:compileReleaseNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android-ndk\ndk-build.cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 34.482 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html`
