### ISSUE TITLE
更新完成之后闪退了,重新打开应用更新完成,之后退出整个应用再进入还是之前的旧版

### ISSUE THREAD

**Issue by HeMa321** [reactnativecn/react-native-pushy#240]
更新完成之后闪退了,重新打开应用更新完成,之后退出整个应用再进入还是之前的旧版
  "react": "^16.3.1",
    "react-native": "^0.55.4",
 "react-native-update": "^5.1.4",

在闪屏页进行检测更新
componentWillMount() {
        this.checkUpdate();
        if (isFirstTime){
            markSuccess();
        } else if (isRolledBack) {
            toastShort('刚刚更新失败了,版本被回滚.');
        }
    }

    doUpdate = info => {
        downloadUpdate(info).then(hash => {
            switchVersion(hash);
        }).catch(err => {
            toastShort('更新失败.');
            this.goToLogin();
        });
    };

    checkUpdate = () => {
        // Alert.alert('提示',packageVersion + "-----" + currentVersion+'===='+isFirstTime);
        checkUpdate(appKey).then(info => {
            // console.warn(info.expired + '， upToDate ： ' + info.upToDate + '，checkUpdate:' + JSON.stringify(info));
            // Alert.alert('提示', info.expired + '， upToDate ： ' + info.upToDate + '，checkUpdate:' + JSON.stringify(info));
            if (info.expired) {//该应用包(原生部分)已过期，需要前往应用市场下载新的版本
                if (Constant.ANDROID) {
                    Alert.alert('提示', '您的应用版本有更新,请前往应用商店下载新的版本', [
                        {
                            text: '确定', onPress: () => {
                                info.downloadUrl && Linking.openURL(info.downloadUrl);
                            }
                        },
                    ], {cancelable: false});
                } else {
                    info.downloadUrl && Linking.openURL(info.downloadUrl);
                }
            } else if (info.upToDate) {
                markSuccess();
                this.goToLogin();//跳到登陆页
            } else {
                if (Constant.ANDROID) {
                    Alert.alert('版本检测', '检查到新的版本' + info.name + ',是否下载?\n' + info.description, [
                        {
                            text: '是', onPress: () => {
                                this.doUpdate(info);
                            }
                        },
                    ], {cancelable: false});
                } else {
                    this.doUpdate(info);
                }
            }
        }).catch(err => {
            toastShort('更新失败.');
            this.goToLogin();
        });
    };

**Comment by HeMa321** [comment]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  [AMapServices sharedServices].apiKey = @"e60f3453ab75286bdf3a7bc8fdd33698";
  
 
在AppDelegate.m也进行了更改
 NSURL *jsCodeLocation;
  
//  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"bundle/index.ios" withExtension:@"jsbundle"];
  #if DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  #else
    jsCodeLocation=[RCTHotUpdate bundleURL];
  #endif
....


在info.plist也进行了如下配置
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
			<key>reactnative.cn</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>

**Comment by HeMa321** [comment]
![image](https://user-images.githubusercontent.com/22217495/51991323-d1f33b00-24e5-11e9-9f18-4703bc982527.png)

**Comment by liuxiaofan** [comment]
我也是
"react": "16.6.3",
"react-native": "0.57.8",
"react-native-update": "^5.1.4",

**Comment by shangnanyy** [comment]
@liuxiaofan 我就是写在componentWillMount中的，但是还会进入之前的旧版，请问你是写在哪个文件中的？谢谢

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
