### ISSUE TITLE
缺少 arm64-v8a 支持

### ISSUE THREAD

**Issue by vance-liu** [reactnativecn/react-native-pushy#244]
打包apk后发现，在arm64-v8a文件中缺少librnupdate.so，导致手机报错，请问怎么解决呢？

**Comment by sunnylqm** [comment]
https://www.zhihu.com/question/36893314/answer/78467097

**Comment by vance-liu** [comment]
关键是引入第三方包，打包apk会有arm64-v8a的文件夹，请问这时候怎么解决?谢谢

**Comment by sunnylqm** [comment]
上面的文章不是已经解释了吗？

**Comment by sunnylqm** [comment]
通过gradle去限制

**Comment by vance-liu** [comment]
非常感谢，添加以下代码解决了。

`defaultConfig {
        //...

        ndk {
            abiFilters "x86"
            abiFilters "armeabi-v7a"
        }
    }`

打包apk后，libs下只有x86和armeabi-v7a文件夹。可以关闭了。
