### ISSUE TITLE
react Native 0.59版本兼容问题，Error: Cannot find module '/Users/jack/Documents/reacNative/RnTest/node_modules/react-native/local-cli/util/Config'

### ISSUE THREAD

**Issue by q273255702** [reactnativecn/react-native-pushy#245]
最新的0.59版本执行 pushy bundle --plaform ios错误：
Error: Cannot find module '/Users/jack/Documents/reacNative/RnTest/node_modules/react-native/local-cli/util/Config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/jack/Documents/reacNative/RnTest/node_modules/react-native-update/local-cli/lib/bundle.js:454:22)
    at Generator.next (<anonymous>)
    at step (/Users/jack/Documents/reacNative/RnTest/node_modules/react-native-update/local-cli/lib/bundle.js:310:191)
    at /Users/jack/Documents/reacNative/RnTest/node_modules/react-native-update/local-cli/lib/bundle.js:310:361

这个怎么修复？？

**Comment by sunnylqm** [comment]
暂时还不支持0.59

**Comment by callcter** [comment]
#### 出错原因
react-native 0.59.x 版本命令行工具改为社区版（@react-native-community/cli），而不是他自己的，所以调用路径发生改变，按照原来的调用方式就会找不到文件

#### 解决方案
1、用 react-native bundle 自己生成 离线包
2、注释 /node_modules/react-native-update/lib/bundle.js 中需要调用 bundle 的部分，保留 pack
3、执行 pushy bundle --platform ios 就不会出问题了

这是我觉着最简单的解决方案，不用去深入理解他的源码

**Comment by ghyzx** [comment]
@sunnylqm  请问大神：大概什么时候会支持0.59.x 的版本，可有计划？

**Comment by fanlilinSaber** [comment]
@callcter 
2、注释 /node_modules/react-native-update/lib/bundle.js 中需要调用 bundle 的部分，保留 pack;

这个步骤是否有 bundle.js 可用的代码；因为修改了还是报错，不知道其中哪一步出错了 

谢谢

**Comment by callcter** [comment]
@fanlilinSaber 这是我注册的
![](https://raw.githubusercontent.com/callcter/image_host/master/WX20190409-145624@2x.png)

**Comment by fanlilinSaber** [comment]
@callcter 好的谢谢，我知道了

**Comment by sunnylqm** [comment]
请试下最新的5.1.7版本

**Comment by GreatAuk** [comment]
> @fanlilinSaber 这是我注释的，但是这个组件一直报 **bsdiff error**，所以我已经换成了react-native-code-push
> ![](https://raw.githubusercontent.com/callcter/image_host/master/WX20190409-145624@2x.png)
你好，请问下， 如果安装了原生插件，无法使用热更新，用现在这个库也可以提示去应用商店下载，但是react-native-code-push 好像没有这个功能，你是怎么解决的？

**Comment by callcter** [comment]
@GreatAuk 热更新只是更新bundle包，别的不行
