### ISSUE TITLE
pushy bundle --platform ios 报错

### ISSUE THREAD

**Issue by fanlilinSaber** [reactnativecn/react-native-pushy#249]
fanlilindeMacBook-Pro-2:ReactNativeDemo fanlilin$ pushy bundle --platform ios
Bundling with React Native version:  0.59.2
Packing
Bundled saved to: build/output/ios.1554803930309.ppk
Would you like to publish it?(Y/N) y
  Uploading [======================] 100% 0.0s
Enter version name: 2.0b5
Enter description: ceisi56
Enter meta info: 
Error: Validation error
    at /Users/fanlilin/Desktop/ReactNativeDemo/node_modules/react-native-update/local-cli/lib/api.js:8:27
    at Generator.next (<anonymous>)
    at step (/Users/fanlilin/Desktop/ReactNativeDemo/node_modules/react-native-update/local-cli/lib/api.js:82:191)
    at /Users/fanlilin/Desktop/ReactNativeDemo/node_modules/react-native-update/local-cli/lib/api.js:82:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
fanlilindeMacBook-Pro-2:ReactNativeDemo fanlilin$

**Comment by sunnylqm** [comment]
Validation error表示已经传过相同的版本了
