### ISSUE TITLE
安卓 build.gradle':react-native-update' could not be found in project ':app'. 

### ISSUE THREAD

**Issue by miaoyinjun** [reactnativecn/react-native-pushy#25]
请问如何解决

**Comment by miaoyinjun** [comment]
解决了，发现是同时使用codepush的问题导致

**Comment by laowood** [comment]
我也遇到了,但不是用codepush的原因... 好发愁.

**Comment by laowood** [comment]
* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':react-native-update' could not be found in project ':app'.

**Comment by miaoyinjun** [comment]
试下Android Studio
菜单/Build/Make Module react-native-update
