### ISSUE TITLE
应用更新后重新打开仍提示有更新，更新代码已执行

### ISSUE THREAD

**Issue by coder-weed-Xu** [reactnativecn/react-native-pushy#253]
![image](https://user-images.githubusercontent.com/31840482/56267910-bc73d180-6122-11e9-855c-8fd8d7b91712.png)，markSuccess已经调用

**Comment by coder-weed-Xu** [comment]
RN版本0.59.3    抓包数据：
![image](https://user-images.githubusercontent.com/31840482/56268240-694e4e80-6123-11e9-84ff-fc5ea0777058.png)
![image](https://user-images.githubusercontent.com/31840482/56268259-73704d00-6123-11e9-9fa0-e8f2d564479c.png)
另： 更新后重新打开isFirstTime判断也进入了

**Comment by coder-weed-Xu** [comment]
测试了ios原生代码，发现刷新页面代码先于存储版本hash值

**Comment by Arvinnnnma** [comment]
![1559284849129](https://user-images.githubusercontent.com/12131813/58686759-42399c80-83b2-11e9-97c0-010fbd03022f.jpg)

把这行代码注释下试试，好像新版RN改机制了。

**Comment by Gd362660870** [comment]
RN:0.59.3 同遇上这个问题
@Arvinnnnma 完美解决

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
