### ISSUE TITLE
android热更新完重启应用后，使用的react-native-sound组件不能播放语音，单独安装没问题

### ISSUE THREAD

**Issue by wangrenhai** [reactnativecn/react-native-pushy#255]
android热更新完重启应用后，使用的react-native-sound组件不能播放语音，单独安装一应用没问题

**Comment by sunnylqm** [comment]
原版尚不支持file:// 协议  https://github.com/zmxv/react-native-sound/pull/528
建议自己fork一个

**Comment by RocWangPeng** [comment]
how i shoud to do,anybody can tell me?

**Comment by sunnylqm** [comment]
照着上面的link自己改就行了
