### ISSUE TITLE
switchVersion(hash)安卓环境下，并不会重启

### ISSUE THREAD

**Issue by huqiangqaq** [reactnativecn/react-native-pushy#264]
"react-native-update": "^5.2.0"  版本如下，点击更新没有重启，而且热更新也没有生效

**Comment by ydbwwhq** [comment]
的确是额，我现在 使用"react-native-update": "^5.2.1",热更新下载完成以后，app都无法启动了。

**Comment by sunnylqm** [comment]
可否提供能重现问题的repo？

**Comment by sunnylqm** [comment]
试下5.2.8版本，应该解决了重启的问题
