### ISSUE TITLE
pushy bundle 生成的ppk文件只要1k，里面没有内容

### ISSUE THREAD

**Issue by ief820** [reactnativecn/react-native-pushy#265]
生成热更新包的时候，使用命令  pushy bundle --platform android

没有生成的过程，日志如下：
Packing
Bundled saved to: build/output/android.1564134805625.ppk

react-native-cli: 2.0.1
react-native: 0.57.6

 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 6.43 GB / 15.96 GB

**Comment by sunnylqm** [comment]
pushy版本多少

**Comment by ief820** [comment]
> pushy版本多少

react-native-update-cli: 0.1.0
react-native-update: n/a - not inside a React Native project directory


另外请问，pushy打包包含图片文件吗？

**Comment by sunnylqm** [comment]
你不知道怎么看版本就贴package.json文件吧
包含图片

**Comment by ief820** [comment]
非常感谢你的及时回复
"react-native-update": "^5.2.1",

**Comment by sunnylqm** [comment]
pushy bundle的过程可以截个图吗

**Comment by ief820** [comment]
大佬，我刚把pushy版本换成5.2.0和5.1.9打包都可以成功，有2M。   又试了一遍5.2.1还是不行，只有1k，空的。

**Comment by ief820** [comment]
正常打包
![image](https://user-images.githubusercontent.com/11845667/62030942-c7a5c580-b218-11e9-86d2-39c0ff7bccd8.png)

5.2.1打包只要1k
![image](https://user-images.githubusercontent.com/11845667/62030972-dbe9c280-b218-11e9-8cd9-03da81bf7f96.png)

**Comment by sunnylqm** [comment]
你node版本多少

**Comment by ief820** [comment]
> 你node版本多少

 node -v
v10.15.1

**Comment by sunnylqm** [comment]
试下命令行里运行
```
node
require('child_process').spawnSync('react-native bundle', {shell: true, stdio: 'inherit'});
```
截图看下

**Comment by ief820** [comment]
![image](https://user-images.githubusercontent.com/11845667/62032501-65e75a80-b21c-11e9-9659-935a2c56ab0c.png)

**Comment by sunnylqm** [comment]
```
require('child_process').spawnSync('react-native bundle --platform android --entry-file index.js --bundle-output build/intermedia/android --assets-dest build/intermedia/android', {shell: true, stdio: 'inherit'});
```

**Comment by ief820** [comment]
![image](https://user-images.githubusercontent.com/11845667/62033009-967bc400-b21d-11e9-83dc-afd3688e66cd.png)

**Comment by sunnylqm** [comment]
在项目目录执行，不在android目录

**Comment by ief820** [comment]
> 在项目目录执行，不在android目录
不好意思，这里没有通知，回复的慢了。
pushy 需要切回 5.2.1吗？mu'q目前pushy是5.2.0版本的

![image](https://user-images.githubusercontent.com/11845667/62033592-e3ac6580-b21e-11e9-8d94-1a8b3fcf740e.png)

**Comment by sunnylqm** [comment]
当然是测你有问题的版本啊 。。。

**Comment by ief820** [comment]
> 当然是测你有问题的版本啊 。。。

马上

**Comment by ief820** [comment]
pushy 5.2.1
![image](https://user-images.githubusercontent.com/11845667/62033780-574e7280-b21f-11e9-9229-ac04e7eface3.png)

**Comment by sunnylqm** [comment]
奇怪，看不出问题，我刚新建了个0.57.6的项目试了下也没碰到问题

**Comment by ief820** [comment]
> 奇怪，看不出问题，我刚新建了个0.57.6的项目试了下也没碰到问题

我先用5.2.0好了。  大佬请问一下 
updateUrl: 'http://update-packages.reactnative.cn/hash',
  pdiffUrl: 'http://update-packages.reactnative.cn/hash',
  diffUrl: 'http://update-packages.reactnative.cn/hash',

这3个url分别是对应什么版本，有什么区别？  文档里好像没找到介绍。  可以补充一下哦

**Comment by sunnylqm** [comment]
内部细节没必要列在文档里吧，就是完整包和差异包

**Comment by sunnylqm** [comment]
请尝试5.2.5版本，在bundle命令后请注意生成的ppk文件大小是否正常（不应该只有几k）
