### ISSUE TITLE
rn0.60版本android更新后出现闪退

### ISSUE THREAD

**Issue by lonson** [reactnativecn/react-native-pushy#266]
使用0.60.3版本的rn，集成pushy后，更新版本后闪退，清除内存后重新打开继续闪退。是不是目前pushy不支持0.60的安卓版本

**Comment by meow4world** [comment]
同上，ios没问题，安卓会闪退
"react-native": "^0.60.4"

**Comment by zkkg2018** [comment]
现在还会吗？

**Comment by sunnylqm** [comment]
请给出报错的日志

**Comment by sunnylqm** [comment]
请尝试5.2.5版本，在bundle命令后请注意生成的ppk文件大小是否正常（不应该只有几k）
