### ISSUE TITLE
RN 0.60.4  iOS版 switchVersion 安装失败

### ISSUE THREAD

**Issue by ghyzx** [reactnativecn/react-native-pushy#267]
最近从 0.58.5 升级到0.60.4 后，iOS版 switchVersion 总是失败，界面有重启，内容好像也更新了，但checkUpdate仍会再次检测到有更新，log如下：

安装更新失败，{"framesToPop":1,"code":"18446744073709551615","nativeStackIOS":["0   Delivery                            0x0000000106c469a7 RCTJSErrorFromCodeMessageAndNSError + 135","1   Delivery                            0x0000000106bd3923 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.129 + 179","2   Delivery                            0x0000000106ea4a3f __59-[RCTHotUpdate downloadPatchFromPackage:resolver:rejecter:]_block_invoke + 207","3   Delivery                            0x0000000106ea730a __49-[RCTHotUpdate patch:fromBundle:source:callback:]_block_invoke + 810","4   Delivery                            0x0000000106ea954a __83-[RCTHotUpdateManager bsdiffFileAtPath:fromOrigin:toDestination:completionHandler:]_block_invoke + 122","5   libdispatch.dylib                   0x000000010e0d4d7f _dispatch_call_block_and_release + 12","6   libdispatch.dylib                   0x000000010e0d5db5 _dispatch_client_callout + 8","7   libdispatch.dylib                   0x000000010e0dd225 _dispatch_lane_serial_drain + 778","8   libdispatch.dylib                   0x000000010e0dde9c _dispatch_lane_invoke + 425","9   libdispatch.dylib                   0x000000010e0e7ea3 _dispatch_workloop_worker_thread + 733","10  libsystem_pthread.dylib             0x000000010e4be611 _pthread_wqthread + 421","11  libsystem_pthread.dylib             0x000000010e4be3fd start_wqthread + 13"],"domain":"cn.reactnative.hotupdate","userInfo":{"NSLocalizedDescription":"bsdiff error"}}

从log看，好像是因为 bsdiff error ；

杀掉App重新打开，App还是旧版本的；

附：
switchVersionLater 可以正常工作（一次性更新成功，不再提示有更新）；

相关代码如下：
downloadUpdate(info).then(hash => {
            Alert.alert('安装更新', '下载完毕,是否重启应用以更新?', [
                {text: '立即重启', onPress: () => switchVersion(hash)},
                {text: '下次启动', onPress: () => switchVersionLater(hash)},
            ]);
        }).catch(err => {
            console.log('安装更新失败，' + JSON.stringify(err));
        });

相关环境如下：
"react": "16.8.6",
 "react-native": "0.60.4",
"react-native-update": "^5.2.1",

**Comment by sunnylqm** [comment]
试下新版本5.2.3

**Comment by ghyzx** [comment]
@sunnylqm  刚刚更新5.2.3，在自己手机上测了一下，已经ok，感谢大神。
