### ISSUE TITLE
ios 热更新失败 react ntaive版本0.60.4

### ISSUE THREAD

**Issue by lee-my** [reactnativecn/react-native-pushy#268]
按照教程点击更新，提示热更新成功。
然后选择手动重启，手动重启后，app打开闪退了一下，再次打开正常，但不是更新后的版本。

如此循环，每次更新成功后，仍然会出现一次闪退。

安卓可以正常热更新。

请问下插件是不兼容react-native 0.60.4  ios么？？

**Comment by sunnylqm** [comment]
试下新版本5.2.3

**Comment by qurbanliwayidin** [comment]
我遇到同样的错误，点击是，更新后，app自动退出，然后重新手动启动，可还是之前的版本，不是更新后的版本。

**Comment by qurbanliwayidin** [comment]
我也遇到类似的问题.楼主解决了没？

**Comment by sunnylqm** [comment]
可否提供能重现的repo？

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
