### ISSUE TITLE
#import "RCTHotUpdate.h"  file not found

### ISSUE THREAD

**Issue by xiangfengsu** [reactnativecn/react-native-pushy#27]
#import "RCTHotUpdate.h"  file not found

**Comment by sunnylqm** [comment]
这是链接不成功，请仔细阅读文档的link相关说明 https://github.com/reactnativecn/react-native-pushy/blob/master/docs/guide.md ，如果重试还不行，请尝试文档中的手动安装部分

**Comment by Nsir15** [comment]
我也遇到这个问题了，而且链接都成功了，但是还是现实file nto found

**Comment by peytonCK** [comment]
我也有这个问题，查看各个部分是正常的，但编译会出错
