### ISSUE TITLE
android热更新后重启出现闪退

### ISSUE THREAD

**Issue by lyichao** [reactnativecn/react-native-pushy#270]
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.crm/files/_update/FrBPPuj15D-jsWKYG1C7cv4ayrsz/index.bundlejs: No such file or directory
————————
"react-native-update": "^5.1.6",
"react-native": "0.48.1",

**Comment by sunnylqm** [comment]
请先尝试新版本，如果还有问题再开issue
