### ISSUE TITLE
Can not install using yarn

### ISSUE THREAD

**Issue by qurbanliwayidin** [reactnativecn/react-native-pushy#272]
I tried to install react-native-pushy using yarn,but it failed. Is there any way to intall this package using yarn?Thanks.By the way,I set up my yarn registry to Taobao.

**Comment by sunnylqm** [comment]
I use yarn all the time and didnt see any error

**Comment by qurbanliwayidin** [comment]
> I use yarn all the time and didnt see any error

Yep,it was caused by node version. This package requires higher version of node than the one installed on my computer.Thanks,and I am closing the issue.

**Comment by qurbanliwayidin** [comment]
ok.



---Original---
