### ISSUE TITLE
  "react-native-update": "^5.2.3",   react-native 0.57.5 ios热更新完成后再次打开app又要从新下载

### ISSUE THREAD

**Issue by chaorenluo** [reactnativecn/react-native-pushy#273]
#ifdef DEBUG
  //开发包
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  //离线包
  
//  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"bundle/index" withExtension:@"jsbundle"];
  // 非DEBUG情况下替换为热更新bundle
//  jsCodeLocation = [RCTHotUpdate bundleURL];
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main"withExtension:@"jsbundle"];
     jsCodeLocation = [RCTHotUpdate bundleURL];
#endif

**Comment by sunnylqm** [comment]
请尝试最新版本，如还有问题请重开issue
