### ISSUE TITLE
 "react-native-update": "^5.2.3", 安卓热更新完成以后闪退

### ISSUE THREAD

**Issue by spwuc** [reactnativecn/react-native-pushy#276]
"react-native": "0.59.9",
 "react-native-update": "^5.2.3",
热更新完成以后点击重启。然后就直接闪退！！！
是什么缘故？
重新打包没有任何问题

**Comment by sunnylqm** [comment]
请尝试5.2.5版本，在bundle命令后请注意生成的ppk文件大小是否正常（不应该只有几k）
