### ISSUE TITLE
switchVersion在安卓下不能切换，IOS可以成功切换

### ISSUE THREAD

**Issue by 007jerry** [reactnativecn/react-native-pushy#277]
"react-native-update": "5.2.4",
    "react-native-update-cli": "^0.1.0",
    "react-native": "^0.57.8"

版本如上，自动检测及安装更新包都是成功的，调用switchVersion(hash);进行版本切换的时候，
在安卓手机上不能立马切换新版本，必须关闭app再重启才可以；在IOS端是正常的，可以立马切换新版本。
请问是什么原因，多谢

**Comment by sunnylqm** [comment]
试下5.2.8版本

**Comment by 007jerry** [comment]
"react-native-update": "^5.2.8",
  "react-native-update-cli": "^0.1.0"
你好，依然不行

**Comment by sunnylqm** [comment]
可以贴一下执行switchVersion前后的adb logcat吗

**Comment by 007jerry** [comment]
您好，代码如下;
doUpdate = info => {
        console.log('info2=' + JSON.stringify(info));
        downloadUpdate(info).then(hash => {
            switchVersion(hash);
            console.log('info3=' + JSON.stringify(info));

            Alert.alert('提示', '下载完毕,请务必关闭并重启APP生效!');
        }).catch(() => {
            Alert.alert('提示', '更新失败,请删除APP重新下载');
        });
    };
    checkUpdateMy = (flag) => {
        checkUpdate(appKey).then(info => {
            console.log('info1=' + JSON.stringify(info));
            if (info.expired) {
                Alert.alert('提示', '您的应用版本已更新,请前往应用商店下载新的版本', [
                    { text: '确定', onPress: () => { info.downloadUrl && Linking.openURL(info.downloadUrl) } },
                ]);
            } else if (info.upToDate) {
                if (flag == '1') {
                    Alert.alert('提示', '恭喜，您的APP是最新版本，请登录使用.');
                }
            } else {
                Alert.alert('提示', '您好，有新版本发布,请务必下载最新版本.', [
                    { text: '确定', onPress: () => { this.doUpdate(info) } },
                    //{ text: '否', },
                ]);
            }
        }).catch(() => {
            Alert.alert('提示', '更新失败.');
        });
    };

日志如下：
09-17 22:23:05.117  9696  9740 I ReactNativeJS: info1={"update":true,"hash":"FnFL31-WmVz1vdfxR7u1jiL4kfAF","name":"2.3","description":"2.3","metaInfo":"{\"ok\":1}","updateUrl":"https://update-packages.reactnative.cn/FnFL31-WmVz1vdfxR7u1jiL4kfAF?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:KYebWnDdnfMFWjFkMD8Xi0Z9MHk=","pdiffUrl":"https://update-packages.reactnative.cn/ls-OCbqk4Ytz6MQmWPUzvqrPnata-FnFL31-WmVz1vdfxR7u1jiL4kfAF.pdiff?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:jt8oorXWHzkC4H_ySHJqzdaBHIk=","diffUrl":"https://update-packages.reactnative.cn/Fgxrhr8z8HC-V0McEYl-7Uui9AXh-FnFL31-WmVz1vdfxR7u1jiL4kfAF.diff?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:BnLnhL2d_ii5Zsmm3KAXSXBBdqY=","ok":1}

09-17 22:23:14.344  9696  9740 I ReactNativeJS: info2={"update":true,"hash":"FnFL31-WmVz1vdfxR7u1jiL4kfAF","name":"2.3","description":"2.3","metaInfo":"{\"ok\":1}","updateUrl":"https://update-packages.reactnative.cn/FnFL31-WmVz1vdfxR7u1jiL4kfAF?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:KYebWnDdnfMFWjFkMD8Xi0Z9MHk=","pdiffUrl":"https://update-packages.reactnative.cn/ls-OCbqk4Ytz6MQmWPUzvqrPnata-FnFL31-WmVz1vdfxR7u1jiL4kfAF.pdiff?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:jt8oorXWHzkC4H_ySHJqzdaBHIk=","diffUrl":"https://update-packages.reactnative.cn/Fgxrhr8z8HC-V0McEYl-7Uui9AXh-FnFL31-WmVz1vdfxR7u1jiL4kfAF.diff?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:BnLnhL2d_ii5Zsmm3KAXSXBBdqY=","ok":1}

09-17 22:23:14.925  9696  9740 I ReactNativeJS: info3={"update":true,"hash":"FnFL31-WmVz1vdfxR7u1jiL4kfAF","name":"2.3","description":"2.3","metaInfo":"{\"ok\":1}","updateUrl":"https://update-packages.reactnative.cn/FnFL31-WmVz1vdfxR7u1jiL4kfAF?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:KYebWnDdnfMFWjFkMD8Xi0Z9MHk=","pdiffUrl":"https://update-packages.reactnative.cn/ls-OCbqk4Ytz6MQmWPUzvqrPnata-FnFL31-WmVz1vdfxR7u1jiL4kfAF.pdiff?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:jt8oorXWHzkC4H_ySHJqzdaBHIk=","diffUrl":"https://update-packages.reactnative.cn/Fgxrhr8z8HC-V0McEYl-7Uui9AXh-FnFL31-WmVz1vdfxR7u1jiL4kfAF.diff?e=1568733785&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:BnLnhL2d_ii5Zsmm3KAXSXBBdqY=","ok":1}。

多谢

**Comment by sunnylqm** [comment]
adb logcat  不是仅仅rn的日志

**Comment by 007jerry** [comment]
您好，请帮看下。
09-18 17:50:06.117 10925 10925 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-18 17:50:06.119 10925 10925 V HiTouch_HiTouchSensor: User setup is finished.
09-18 17:50:06.233 10925 10925 V AudioManager: playSoundEffect   effectType: 0
09-18 17:50:06.233 10925 10925 V AudioManager: querySoundEffectsEnabled...
09-18 17:50:06.239 10925 10973 I ReactNativeJS: info2={"update":true,"hash":"Ftr1ZsNQM1EtErYi3Zi5wXPcIW5X","name":"2.2","description":"2.2","metaInfo":"{\"ok\":1}","updateUrl":"https://update-packages.reactnative.cn/Ftr1ZsNQM1EtErYi3Zi5wXPcIW5X?e=1568803802&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:29rW5yaSy4FJkmEHk2O6P3Ut2QI=","pdiffUrl":"https://update-packages.reactnative.cn/lkhBkloh5mnvdWEwAcji_-CrkFhd-Ftr1ZsNQM1EtErYi3Zi5wXPcIW5X.pdiff?e=1568803802&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:X_8Y7DiI9xKUY-e_vYC-H9lg4e0=","ok":1}
09-18 17:50:06.299 10925 10954 W libEGL  : EGLNativeWindowType 0xe49f7008 disconnect failed
09-18 17:50:06.300 10925 10954 D OpenGLRenderer: endAllActiveAnimators on 0xc1db1900 (RippleDrawable) with handle 0xc4de5cd0
09-18 17:50:06.337 10925 10925 V InputMethodManager: Reporting focus gain, without startInput
09-18 17:50:08.527 10925 10973 I ReactNativeJS: info3={"update":true,"hash":"Ftr1ZsNQM1EtErYi3Zi5wXPcIW5X","name":"2.2","description":"2.2","metaInfo":"{\"ok\":1}","updateUrl":"https://update-packages.reactnative.cn/Ftr1ZsNQM1EtErYi3Zi5wXPcIW5X?e=1568803802&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:29rW5yaSy4FJkmEHk2O6P3Ut2QI=","pdiffUrl":"https://update-packages.reactnative.cn/lkhBkloh5mnvdWEwAcji_-CrkFhd-Ftr1ZsNQM1EtErYi3Zi5wXPcIW5X.pdiff?e=1568803802&token=made75kGFhOozkiRfa7LK_E1xG1pLOnhW8fhbnev:X_8Y7DiI9xKUY-e_vYC-H9lg4e0=","ok":1}
09-18 17:50:08.531 10925 10925 E pushy   : Failed to restart application
09-18 17:50:08.531 10925 10925 E pushy   : java.lang.NoSuchFieldException: No field mBundleLoader in class Lcom/facebook/react/k; (declaration of 'com.facebook.react.k' appears in /data/app/com.bluefire.smartcy-z1oTn9OXMhT_f2txjLBZjw==/base.apk)
09-18 17:50:08.531 10925 10925 E pushy   : 	at java.lang.Class.getDeclaredField(Native Method)
09-18 17:50:08.531 10925 10925 E pushy   : 	at cn.reactnative.modules.update.UpdateModule$4.run(Unknown Source:66)
09-18 17:50:08.531 10925 10925 E pushy   : 	at android.os.Handler.handleCallback(Handler.java:907)
09-18 17:50:08.531 10925 10925 E pushy   : 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-18 17:50:08.531 10925 10925 E pushy   : 	at android.os.Looper.loop(Looper.java:216)
09-18 17:50:08.531 10925 10925 E pushy   : 	at android.app.ActivityThread.main(ActivityThread.java:7625)
09-18 17:50:08.531 10925 10925 E pushy   : 	at java.lang.reflect.Method.invoke(Native Method)
09-18 17:50:08.531 10925 10925 E pushy   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
09-18 17:50:08.531 10925 10925 E pushy   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
09-18 17:50:08.535 10925 10925 I HwPhoneWindow: updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=true, mIsFloating=true
09-18 17:50:08.541 10925 10925 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.541 10925 10925 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.541 10925 10925 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.541 10925 10925 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
09-18 17:50:08.541 10925 10925 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@ecc91a9,android.view.ContextThemeWrapper@331b32e
09-18 17:50:08.541 10925 10925 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
09-18 17:50:08.542 10925 10925 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.542 10925 10925 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.542 10925 10925 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.542 10925 10925 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
09-18 17:50:08.542 10925 10925 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@ba9d43a,android.view.ContextThemeWrapper@331b32e
09-18 17:50:08.542 10925 10925 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
09-18 17:50:08.545 10925 10925 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.545 10925 10925 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.545 10925 10925 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.545 10925 10925 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
09-18 17:50:08.545 10925 10925 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@e43cce1,android.view.ContextThemeWrapper@331b32e
09-18 17:50:08.545 10925 10925 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
09-18 17:50:08.546 10925 10925 I FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.546 10925 10925 I FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.546 10925 10925 D FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
09-18 17:50:08.546 10925 10925 D FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
09-18 17:50:08.546 10925 10925 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@f4c78c7,android.view.ContextThemeWrapper@331b32e
09-18 17:50:08.546 10925 10925 D HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
09-18 17:50:08.552 10925 10954 D OpenGLRenderer:   HWUI Binary is  enabled
09-18 17:50:08.552 10925 10954 D OpenGLRenderer: disableOutlineDraw is true
09-18 17:50:08.578 10925 11179 I HiTouch_HiTouchSensor: enabledInPad = false,isPcCastMode = false
09-18 17:50:08.578 10925 11179 D HiTouch_PressGestureDetector: onAttached, package=com.bluefire.smartcy, windowType=2, mHiTouchRestricted=false
09-18 17:50:08.616 10925 10954 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
09-18 17:50:08.617 10925 10954 D OpenGLRenderer:   HWUI Binary is  enabled
09-18 17:50:08.617 10925 10954 D OpenGLRenderer: disableOutlineDraw is true
09-18 17:50:08.637 10925 10925 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time

#########################################
#############切换之后，日志#################

09-18 17:50:11.074 10925 10925 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-18 17:50:11.074 10925 10925 V HiTouch_HiTouchSensor: User setup is finished.
09-18 17:50:11.202 10925 10925 V AudioManager: playSoundEffect   effectType: 0
09-18 17:50:11.202 10925 10925 V AudioManager: querySoundEffectsEnabled...
09-18 17:50:11.212 10925 10954 W libEGL  : EGLNativeWindowType 0xc1e91808 disconnect failed
09-18 17:50:11.212 10925 10954 D OpenGLRenderer: endAllActiveAnimators on 0xc1e3c400 (RippleDrawable) with handle 0xc4de5b60
09-18 17:50:11.242 10925 10925 V InputMethodManager: Reporting focus gain, without startInput

**Comment by sunnylqm** [comment]
收到，会尽快修复

**Comment by sunnylqm** [comment]
你是否有开启混淆，有的话可以看下混淆的配置吗

**Comment by sunnylqm** [comment]
@007jerry

**Comment by 007jerry** [comment]
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

**Comment by 007jerry** [comment]
```
你好，如下：
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}
```

**Comment by 007jerry** [comment]
太感谢了，关闭代码混淆即可。

**Comment by sunnylqm** [comment]
@007jerry 
```
-keepnames class cn.reactnative.modules.update.DownloadTask;
-keepnames class com.facebook.react.ReactInstanceManager;
```
可以麻烦你再开启混淆同时加上这两条规则再试试吗，谢谢

**Comment by sunnylqm** [comment]
5.2.9已添加混淆规则，应该可以支持开启混淆了
