### ISSUE TITLE
下载更新失败

### ISSUE THREAD

**Issue by hkwin** [reactnativecn/react-native-pushy#279]
运行pushy bundle 和 update 命令后，提示已经成功了

此时打开APP，检测更新也没问题，就是在下载更新的时候报同一个错，也没有改动图片啊，就想着改动几个文字测试测试
![image](https://user-images.githubusercontent.com/12762712/65304415-26514500-dbb3-11e9-8838-82f2e7b6a91c.png)

是什么原因？谢谢

"react-native": "0.59.9",
"react-native-update": "^5.3.0"

**Comment by sunnylqm** [comment]
图片是使用了中文文件名吗？

**Comment by hkwin** [comment]
后面自己猜测也是的，改回英文名就没问题了
