### ISSUE TITLE
pushy login报错

### ISSUE THREAD

**Issue by duanzonglong** [reactnativecn/react-native-pushy#28]
pushy login
{ [Error: Cannot find module './build/Release/bsdiff'] code: 'MODULE_NOT_FOUND' }
module.js:327
    throw err;

"react-native": "0.31.0", "react-native-update": "^3.0.1"

**Comment by tdzl2003** [comment]
npm rebuild试试，你的node依赖没有正确编译。

如果你是windows的话，需要安装C++环境如Visual Studio、cygwin等。
