### ISSUE TITLE
5.3.0 热更新启动图后闪退

### ISSUE THREAD

**Issue by iaminvictus1993** [reactnativecn/react-native-pushy#280]
更新后重启应用还是闪退
"react-native-update": "^5.3.0",
"react-native": "0.59.9",
用了react-native-splash-screen,若不改启动图图片，只修改文字，测试热更新没问题。修改启动图后就闪退

**Comment by sunnylqm** [comment]
启动图的修改算是原生修改了，不能通过热更新实现的
