### ISSUE TITLE
iOS 热更新[RCTHotUpdate bundleURL]获取的地址 为什么会是main.jsbundle

### ISSUE THREAD

**Issue by xhzth7091** [reactnativecn/react-native-pushy#282]
![Xnip2019-10-09_14-35-50](https://user-images.githubusercontent.com/13980546/66457107-1cc84800-eaa2-11e9-951b-ed5df8e7125c.jpg)
[RCTHotUpdate bundleURL]我获取的热更新的地址怎么是main.jsbundle，还有就是我是用npm run bundle-ios 配置的离线包。
#if DEBUG
  // 原来的jsCodeLocation保留在这里
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"bundle/index.ios" withExtension:@"jsbundle"];
#else
  // 非DEBUG情况下替换为热更新bundle
  jsCodeLocation = [RCTHotUpdate bundleURL];
#endif
这个还需要怎么配置?

**Comment by sunnylqm** [comment]
没有可用的热更新的情况下，就返回默认的main.jsbundle
当然如果你用了别的名字，这里确实会不匹配，我们目前没有考虑到这种情况

**Comment by xhzth7091** [comment]
我用npm run bundle-ios 配置的离线包 ，还需要配置main.jsbundle吗？
[image: 898482FE55F32D711D14ECBCF09BB0FF.png]

Sunny Luo <notifications@github.com> 于2019年10月9日周三 下午3:35写道：

**Comment by sunnylqm** [comment]
你所使用的bundle文件名（见截图28行）是你（或者你之前的开发者）自己配置的，不是默认文件名

包括npm run xxxx也是你（或者你之前的开发者）自己配置的（在package.json的scripts里），并不是标准命令

**Comment by xhzth7091** [comment]
是否需要修改成默认的main.jsbundle，才可以热更新？

Sunny Luo <notifications@github.com> 于2019年10月9日周三 下午3:56写道：

**Comment by sunnylqm** [comment]
是的，目前的逻辑没有考虑其他bundle文件名
