### ISSUE TITLE
提交审核的时候被拒绝，怎么办？

### ISSUE THREAD

**Issue by hkwin** [reactnativecn/react-native-pushy#285]
以下是苹果的拒绝原文：
Guideline 2.3.1 - Performance

We discovered that your app contains hidden features.

Specifically, your app includes hot update functionality that allows your app to download a new main.jsbundle anytime.￼

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Performance section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program.
- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.

Guideline 2.5.2 - Performance - Software Requirements

Your app, extension, or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with App Store Review Guideline 2.5.2 and section 3.3.2 of the Apple Developer Program License Agreement.

This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior and/or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Software Requirements section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program.
- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.

以下是我RN - App.js的部分代码（热更新部分）：
import {
  isFirstTime,
  isRolledBack,
  packageVersion,
  currentVersion,
  checkUpdate,
  downloadUpdate,
  switchVersion,
  switchVersionLater,
  markSuccess,
} from 'react-native-update';

import updateConfig from './update.json'
import { screenWidth, screenHeight, isHasLiuhai } from './app/utils/px2dp'

import RootScene from './app/RootScene'

class App extends Component<Props> {

  constructor (props) {
    super(props)

  }

  componentWillMount () {
    if (isFirstTime) {
      markSuccess()
    } else {
      checkUpdate(updateConfig[Platform.OS].appKey).then(info => {
        if (info.expired) {
          // Alert.alert('提示', '您的应用版本已更新,请前往应用商店下载新的版本', [
          //   {text: '确定', onPress: () => {info.downloadUrl && Linking.openURL(info.downloadUrl)}},
          // ]);
        } else if (info.upToDate) {
          // 目前版本是最新
        } else {
          this.doUpdate(info)
        }
      }).catch(err => {
        // Alert.alert('提示', '检查更新失败.' + err);
      });
    }
  }

  doUpdate (info) {
    downloadUpdate(info).then(hash => {
      switchVersionLater(hash)
    }).catch(err => {
      // Alert.alert('提示', '下载更新失败.' + err);
    });
  }

把弹窗提醒都注释了

另外，在网页端我也上传了要上传到 App Store 的 ipa 文件，情况就是这样了。

要怎么解决，谢谢！

**Comment by sunnylqm** [comment]
提审期间有发布热更新吗

**Comment by hkwin** [comment]
没有，就只进行了 uploadIpa 操作

**Comment by hkwin** [comment]
流程是这样的：
1、product --- Archive 之后，就首先 export 出来 ipa 文件，pushy uploadIpa 到网页
2、然后在选择 upload 到 App Store
3、然后就提交等待审核了

**Comment by hkwin** [comment]
那应该要怎么解决呢？谢谢。

是先不进行 uploadIpa 操作？

**Comment by sunnylqm** [comment]
之前还没有碰到过这种情况，你试着写信问问？

**Comment by Zefey** [comment]
![image](https://user-images.githubusercontent.com/19901561/67466842-555b4a80-f67a-11e9-8e57-fe66820407cd.png)

一样的被拒

**Comment by sunnylqm** [comment]
有2个猜测，一是代码扫描，二是网址嗅探
两位如果可以的话，试着把checkUpdate也注释掉再提交试试（当然这个可能导致审核时间延长）
我们评估下，后续可能考虑加上代码混淆

**Comment by sunnylqm** [comment]
已添加如何屏蔽ios端的说明
https://github.com/reactnativecn/react-native-pushy/blob/master/README.md

**Comment by hkwin** [comment]
> 已添加如何屏蔽ios端的说明
> https://github.com/reactnativecn/react-native-pushy/blob/master/README.md

第 2 点指的是不包括 Link 部分（我的 RN 版本为 0.59.9，采用的是不使用 CocoaPods），只需要把配置 BundleURL 部分删除掉吗？

**Comment by sunnylqm** [comment]
就是之前配置过的东西都撤销

**Comment by hkwin** [comment]
> 就是之前配置过的东西都撤销

那这样子的意思就是 iOS 端的热更新不就是不能用了？🤦‍♂️

**Comment by sunnylqm** [comment]
@hkwin 如果愿意尝试，可以试试先注释掉checkUpdate，如果急着上线那只能先不用了

**Comment by WangJiaJun8922** [comment]
我也遇到这个问题今天。我是是因为没有UploadIPA到网页，然后估计审核的时候，弹框了，被拒了。然后现在准备按照这个流程走一遍，再试试。
1、product --- Archive 之后，就首先 export 出来 ipa 文件，pushy uploadIpa 到网页
2、然后在选择 upload 到 App Store
3、然后就提交等待审核了

**Comment by changpk** [comment]
> 没有，就只进行了 uploadIpa 操作

那提到了main.jsbundle文件，RN正常打包不带热更也是生成了main.jsbundle文件，这是不让用RN开发的节奏了么

**Comment by hkwin** [comment]
@changpk 不带热更新的话应该风险不大，之前我们公司也已上架过两款 RN 的 APP了

**Comment by changpk** [comment]
@hkwin 我们现在项目中也是部分使用到了RN;那就是所有涉及到热更，比如自己搭建服务器进行热更也是有风险的是吧

**Comment by hkwin** [comment]
@changpk 这个就不清楚了，我们上架的两款都是纯 RN 的（就是用 RN 来创建项目的），然后一款是有用热更新的（code-push），一款是没用的。至于自己搭建服务器这个就只能看苹果那边怎么认为了，个人觉得应该没这么严吧。我们用了 code-push 的那款最初版本也是一年前的事了

**Comment by changpk** [comment]
@hkwin 感谢。 code-push 应该没问题，否则codepush的官网也应该有issue的。也不知道苹果这变幻莫测的审核规则😓

**Comment by lchenfox** [comment]
> @hkwin 如果愿意尝试，可以试试先注释掉checkUpdate，如果急着上线那只能先不用了

啊啊啊，一模一样的被拒的原因啊！24号提交到`App store connect`, 25号被拒！ 上两个版本也是用的`pushy`没有啥问题，这个版本也就增加了几个页面，没有增加其他东西，就被拒绝了！我开始感觉到莫名其妙，因为这次我部署了`jenkins + Fastlane`脚本打包，我还以为是这个原因，然后我把本地打包脚本删掉又重新打包上传了，26号提交，到现在30号了在显示`审核中`，版本信息如下：

```
"dependencies": {
    "antd-mobile-rn": "^2.3.3",
    "axios": "^0.18.0",
    "buffer": "^5.2.1",
    "i18n-js": "^3.2.2",
    "jcore-react-native": "^1.3.0",
    "jpush-react-native": "^2.4.0",
    "moment": "^2.22.2",
    "node-forge": "^0.7.6",
    "react": "^16.6.0-alpha.8af6728",
    "react-dom": "^16.6.0",
    "react-native": "0.57.4", // 这里~~~~~~~~~~~~~~~·
    "react-native-camera": "^1.9.1",
    "react-native-exit-app": "^1.0.0",
    "react-native-flexi-radio-button": "^0.2.2",
    "react-native-image-zoom-viewer": "^2.2.24",
    "react-native-localize": "^1.1.2",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-paper": "^2.3.0",
    "react-native-percentage-circle": "^1.0.7",
    "react-native-progress": "^3.5.0",
    "react-native-root-modal": "^3.1.1",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-sound": "^0.10.9",
    "react-native-splash-screen": "^3.2.0",
    "react-native-touch-id": "^4.4.1",
    "react-native-update": "^5.1.4",  // 这里~~~~~~~~~~~~~~~·
    "react-native-vector-icons": "4.6.0",
    "react-native-webview": "^5.7.0",
    "react-navigation": "^2.18.2",
    "react-navigation-material-bottom-tabs": "^0.4.0",
    "react-redux": "^5.1.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "rmc-date-picker": "^6.0.8"
  },
```
😔，一开始被拒我就觉得不对劲，今天顺便来看了下，难道真是热更的原因😭😭 那这样我是不是只能再撤回，去掉热更新了~~

**Comment by DevChenwei** [comment]
10月30号，我也因为热更新被拒了。JS端我是屏蔽了checkUpdate，估计是原生那边有代码扫描到了react-native-update

![image](https://user-images.githubusercontent.com/15886890/67822448-646b4e00-fafb-11e9-8e54-cc00ad8d2b4c.png)

![image](https://user-images.githubusercontent.com/15886890/67822467-751bc400-fafb-11e9-9f10-d7117494fc3d.png)

**Comment by changpk** [comment]
@lchenfox  
 我在code-push上提交了类似问题，有人说得看你热更的目的如果是修改bug或者改善用户体验是没事，但是搜索网页有人用code-push也曾被拒绝过😢；如果还想用热更的话，可以考虑code-push试一下，毕竟那个库现在还没有此类被拒的问题，但是风险肯定还是有的。

**Comment by lchenfox** [comment]
> @lchenfox
> 我在code-push上提交了类似问题，有人说得看你热更的目的如果是修改bug或者改善用户体验是没事（但是怎么判定呢，咱也不懂），但是搜索网页有人用code-push也曾被拒绝过😢；如果还想用热更的话，可以考虑code-push试一下，毕竟那个库现在还没有此类被拒的问题在下面提出，但是风险肯定还是有的。

唉，万恶的苹果爸爸，真的恶心！之前几个版本好好的，这次除了加了点页面，什么都没干，就被拒！ 另外，你说的`code-push`据说是国外比较慢吧，当时也是考虑到这些原因所以用的`pushy`，当然我也没用过`code-push`，不知道具体会怎样，我打算这个版本先把iOS的`pushy热更`直接删掉了，等有更好的解决方案再说吧。多谢~

**Comment by hkwin** [comment]
@changpk @lchenfox 目前我这款被拒的 APP 我当初首要考虑方案也是 code-push 的（因为我们先前的一款 APP 也是采用 code-push，所以优先考虑），但发现实际测试过程中，确实出现了更新很慢，只有第一次推送更新能成功，而且图片也给我整没了，后面的推送就死活更新不到了，所以才换成 pushy 的。

现在我也正打算先把 pushy 删掉了🤦‍♂️🤦‍♂️

**Comment by lchenfox** [comment]
> @changpk @lchenfox 目前我这款被拒的 APP 我当初首要考虑方案也是 code-push 的（因为我们先前的一款 APP 也是采用 code-push，所以优先考虑），但发现实际测试过程中，确实出现了更新很慢，只有第一次推送更新能成功，而且图片也给我整没了，后面的推送就死活更新不到了，所以才换成 pushy 的。
> 
> 现在我也正打算先把 pushy 删掉了🤦‍♂️🤦‍♂️

是的，就是墙比较坑，使用`pushy`在`4G`下本地打测试包，不管是`Android`还是`iOS`基本没怎么失败过，国内还是比较靠谱的，上线的版本有一次也有一个奔溃的`bug`也是通过热更修复的，还有一点就是`pushy作者`大佬一直在更新，`issue`回复也及时耐心，所以才选这个。先去掉，看看后期有没有什么具体的解决方案再说了~~`RN`感觉也是处处碰壁啊~~

**Comment by sunnylqm** [comment]
单独禁用ios端的方法  
https://github.com/reactnativecn/react-native-pushy/blob/master/README.md

**Comment by lchenfox** [comment]
> 单独禁用ios端的方法
> https://github.com/reactnativecn/react-native-pushy/blob/master/README.md

好的，多谢。期待后续有解决方案~

**Comment by lwxzks** [comment]
怎么这么多人中枪的

**Comment by sunnylqm** [comment]
@DevChenwei 谢谢，如果有用的话可以麻烦提交一个pr吗

**Comment by hkwin** [comment]
@DevChenwei 我也静等你的好消息。我现在已经先撤掉了，先上架先。

**Comment by DevChenwei** [comment]
> @DevChenwei 谢谢，如果有用的话可以麻烦提交一个pr吗

没问题的。

**Comment by lchenfox** [comment]
@hkwin @Zefey @WangJiaJun8922 @changpk @sunnylqm  

- 10月24日提交

- 10月25日被拒

- 10月26日去掉`jenkins+fastlane`自动化打包脚本（以为是这个原因，毕竟之前的版本使用热更新没有被拒）重新打包上传到`App Store Connect`

- 截止10月29日依然在审核中

- 10月29日晚上去掉`iOS`的热更新，并再次打包重新上传，去掉热更新的步骤：

**（1）: 修改AppDelegate为**

```
    NSURL *jsCodeLocation;
#if DEBUG
    // 原来的jsCodeLocation保留在这里
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
    // 非DEBUG情况下启用热更新
    jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
//    jsCodeLocation=[RCTHotUpdate bundleURL];  // 不要热更新
#endif
```

**（2）删除`Libraries -> RCTHotUpdate.xcodeproj`**

**（3）注释掉所有热更新的js检测代码**，如下：

```

/****************** hot update *********************/
/*
import {
    isFirstTime,
    isRolledBack,
    packageVersion,
    currentVersion,
    checkUpdate,
    downloadUpdate,
    switchVersion,
    switchVersionLater,
    markSuccess,
} from 'react-native-update';
**/

const {appKey} = _updateConfig[Platform.OS];

export default class rootApp extends Component {

    componentDidMount() {
        /*
            this._checkHotUpdateVersion();
         */
    };

    /**
    _checkHotUpdateVersion = (tryAgain = true) => {
        checkUpdate(appKey).then(info => {
            if (info.expired) {
                // do nothing!
            } else if (info.upToDate) {
                // 您的应用版本已是最新
                markSuccess();
            } else {
                this._doUpdate(info)
            }
        }).catch(() => {
            if (tryAgain) {
                this._checkHotUpdateVersion(false);
            }
        });
    };

    _doUpdate = (info, tryAgain = true) => {
        downloadUpdate(info).then(hash => {
            if (info.metaInfo) {
                try {
                    const metaInfoObj = JSON.parse(info.metaInfo);
                    const {restartNow} = metaInfoObj;
                    // 如果需要立即重启，发布的时候metaInfo直接输入：{"restartNow": 1}
                    if (restartNow) {
                        switchVersion(hash);
                    } else {
                        switchVersionLater(hash);
                    }
                } catch (e) {
                    switchVersionLater(hash);
                }
            } else {
                switchVersionLater(hash);
            }
        }).catch(err => {
            if (tryAgain) {
                this._doUpdate(info, false);
            }
        });
    };
     **/
```

- 11月5日凌晨2点22分，审核通过！！！

注：由于忙着上线，就只好选择干脆利落的方式直接去掉`iOS`的热更新了！ 其次，也的确证明苹果这次又开始着重针对**热更新**了，具体原因未知，我前面3个版本都使用热更新，顺利上线！

**Comment by Zefey** [comment]
> @hkwin @Zefey @WangJiaJun8922 @changpk @sunnylqm
> 
> * 10月24日提交
> * 10月25日被拒
> * 10月26日去掉`jenkins+fastlane`自动化打包脚本（以为是这个原因，毕竟之前的版本使用热更新没有被拒）重新打包上传到`App Store Connect`
> * 截止10月29日依然在审核中
> * 10月29日晚上去掉`iOS`的热更新，并再次打包重新上传，去掉热更新的步骤：
> 
> **（1）: 修改AppDelegate为**
> 
> ```
>     NSURL *jsCodeLocation;
> #if DEBUG
>     // 原来的jsCodeLocation保留在这里
>     jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
> #else
>     // 非DEBUG情况下启用热更新
>     jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
> //    jsCodeLocation=[RCTHotUpdate bundleURL];  // 不要热更新
> #endif
> ```
> 
> **（2）删除`Libraries -> RCTHotUpdate.xcodeproj`**
> 
> **（3）注释掉所有热更新的js检测代码**，如下：
> 
> ```
> 
> /****************** hot update *********************/
> /*
> import {
>     isFirstTime,
>     isRolledBack,
>     packageVersion,
>     currentVersion,
>     checkUpdate,
>     downloadUpdate,
>     switchVersion,
>     switchVersionLater,
>     markSuccess,
> } from 'react-native-update';
> **/
> 
> const {appKey} = _updateConfig[Platform.OS];
> 
> export default class rootApp extends Component {
> 
>     componentDidMount() {
>         /*
>             this._checkHotUpdateVersion();
>          */
>     };
> 
>     /**
>     _checkHotUpdateVersion = (tryAgain = true) => {
>         checkUpdate(appKey).then(info => {
>             if (info.expired) {
>                 // do nothing!
>             } else if (info.upToDate) {
>                 // 您的应用版本已是最新
>                 markSuccess();
>             } else {
>                 this._doUpdate(info)
>             }
>         }).catch(() => {
>             if (tryAgain) {
>                 this._checkHotUpdateVersion(false);
>             }
>         });
>     };
> 
>     _doUpdate = (info, tryAgain = true) => {
>         downloadUpdate(info).then(hash => {
>             if (info.metaInfo) {
>                 try {
>                     const metaInfoObj = JSON.parse(info.metaInfo);
>                     const {restartNow} = metaInfoObj;
>                     // 如果需要立即重启，发布的时候metaInfo直接输入：{"restartNow": 1}
>                     if (restartNow) {
>                         switchVersion(hash);
>                     } else {
>                         switchVersionLater(hash);
>                     }
>                 } catch (e) {
>                     switchVersionLater(hash);
>                 }
>             } else {
>                 switchVersionLater(hash);
>             }
>         }).catch(err => {
>             if (tryAgain) {
>                 this._doUpdate(info, false);
>             }
>         });
>     };
>      **/
> ```
> 
> * 11月5日凌晨2点22分，审核通过！！！
> 
> 注：由于忙着上线，就只好选择干脆利落的方式直接去掉`iOS`的热更新了！ 其次，也的确证明苹果这次又开始着重针对**热更新**了，具体原因未知，我前面3个版本都使用热更新，顺利上线！

ios我去掉热更新也审核通过了

**Comment by lchenfox** [comment]
@Zefey 
> ios我去掉热更新也审核通过了

 嗯是的，我觉得后期苹果也会拒绝其他热更，还是想要大家回归原生呢。

**Comment by ghyzx** [comment]
归集一下信息：最近两周，有用了Pushy，也通过审核了的吗？

**Comment by RodgerLai** [comment]
大佬们有没有方案避过苹果的检查？

**Comment by sunnylqm** [comment]
可以改类名方法名试试，我还没有时间尝试



---原始邮件---
发件人: "StriveForGreatness"<notifications@github.com&gt;
发送时间: 2019年11月13日(星期三) 晚上6:59
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Sunny Luo"<sunnylqm@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [reactnativecn/react-native-pushy] 提交审核的时候被拒绝，怎么办？ (#285)



大佬们有没有方案避过苹果的检查？

**Comment by sunnylqm** [comment]
已发布5.4.0，对类名方法名做了修改，有兴趣的朋友可以尝试下

**Comment by masonel** [comment]
现在怎么样了？有人提交成功了没

**Comment by masonel** [comment]
> @DevChenwei 我也静等你的好消息。我现在已经先撤掉了，先上架先。

请问，后来你又发布热更新版本成功了嘛

**Comment by wy6754** [comment]
可以尝试下react-native-code-push

**Comment by sunnylqm** [comment]
有用户汇报使用最新版本（5.5.8）上架ios成功

**Comment by muzi131313** [comment]
现在主应用是webview的，还能提交审核成功么？
