### ISSUE TITLE
s.dependency 'SSZipArchive'  这个pod依赖和项目的一个zip库冲突了

### ISSUE THREAD

**Issue by yuanwy** [reactnativecn/react-native-pushy#286]
s.dependency 'SSZipArchive'  这个pod依赖和项目的一个zip第三方库冲突了。那个zip库里有SSZipArchive里面的所有文件。所以 能不能把podspec里的这个依赖去掉 让开发在项目的podfile文件里去依赖SSZipArchive。

**Comment by sunnylqm** [comment]
据我所知，要么大家都统一用线上的版本，自然可以复用而不冲突，要么自己的本地版本改名。之前碰到过这样的问题所以pushy采用了线上的版本。当然如果有更好的办法欢迎推荐。
