### ISSUE TITLE
iOS  上传.ipa 包错误问题

### ISSUE THREAD

**Issue by a728384698** [reactnativecn/react-native-pushy#287]
![屏幕快照 2019-10-25 下午4 13 15](https://user-images.githubusercontent.com/7380874/67555924-d41cba00-f744-11e9-88e4-d38f065072f0.png)
![屏幕快照 2019-10-25 下午4 13 46](https://user-images.githubusercontent.com/7380874/67555947-e26ad600-f744-11e9-827b-db230209dcd2.png)
node.js 的版本是v10.16.0

**Comment by sunnylqm** [comment]
5.x以下版本我们已不再维护了
