### ISSUE TITLE
关于强制更新的问题

### ISSUE THREAD

**Issue by a728384698** [reactnativecn/react-native-pushy#289]
![屏幕快照 2019-10-27 上午11 54 59](https://user-images.githubusercontent.com/7380874/67629448-9b99ef00-f8b0-11e9-9ec0-1699d554fbc4.png)
 本地打包测试，每次走的都是else里面没有到 if() 里面的前往商店下载。是否是因为没有在应用商店上添加需更新的包。

**Comment by sunnylqm** [comment]
设备上安装的app的原生版本和上传到push的不一致时才是expired，且这个url需要你自己去网页端添加

**Comment by a728384698** [comment]
> 设备上安装的app的原生版本和上传到push的不一致时才是expired，且这个url需要你自己去网页端添加
修改前我打包ipa并装到了手机上，之后我试着修改了version，和注释了appdelegate一些原生的代码，重新编译在重新push提交 还是没有执行到exoired中，不清楚这个不一致是表现在哪一部分。

**Comment by a728384698** [comment]
@sunnylqm 修改前我打包ipa并装到了手机上，之后我试着修改了version，和注释了appdelegate一些原生的代码，重新编译在重新push提交 还是没有执行到exoired中，不清楚这个不一致是表现在哪一部分。

**Comment by sunnylqm** [comment]
准确来说，是设备上的版本在pushy服务器端不存在时（如果你希望触发，那就应该在服务器端删掉这个版本）
