### ISSUE TITLE
isFirstTime，isRolledBack等都是undefined

### ISSUE THREAD

**Issue by xiangfengsu** [reactnativecn/react-native-pushy#29]
你好，问一下，我按照教程把代码复制运行，为什么打印（isFirstTime，isRolledBack）的是undefined ,是因为我的debug 模式吗？

**Comment by sunnylqm** [comment]
请贴代码以及报错截图

**Comment by xiangfengsu** [comment]
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, {
  Component,
} from 'react';

import {
  AppRegistry,
  StyleSheet,
  Platform,
  Text,
  View,
  Alert,
  TouchableOpacity,
  Linking,
} from 'react-native';

import {
  isFirstTime,
  isRolledBack,
  packageVersion,
  currentVersion,
  checkUpdate,
  downloadUpdate,
  switchVersion,
  switchVersionLater,
  markSuccess,
} from 'react-native-update';

import _updateConfig from './update.json';
const {appKey} = _updateConfig[Platform.OS];

class MyProject extends Component {
  componentWillMount(){
    console.log(isFirstTime);
    if (isFirstTime) {
      Alert.alert('提示', '这是当前版本第一次启动,是否要模拟启动失败?失败将回滚到上一版本', [
        {text: '是', onPress: ()=>{throw new Error('模拟启动失败,请重启应用')}},
        {text: '否', onPress: ()=>{markSuccess()}},
      ]);
    } else if (isRolledBack) {
      Alert.alert('提示', '刚刚更新失败了,版本被回滚.');
    }
  }
  doUpdate = info => {
    downloadUpdate(info).then(hash => {
      Alert.alert('提示', '下载完毕,是否重启应用?', [
        {text: '是', onPress: ()=>{switchVersion(hash);}},
        {text: '否',},
        {text: '下次启动时', onPress: ()=>{switchVersionLater(hash);}},
      ]);
    }).catch(err => { 
      Alert.alert('提示', '更新失败.');
    });
  };
  checkUpdate = () => {
    checkUpdate(appKey).then(info => {
      if (info.expired) {
        Alert.alert('提示', '您的应用版本已更新,请前往应用商店下载新的版本', [
          {text: '确定', onPress: ()=>{info.downloadUrl && Linking.openURL(info.downloadUrl)}},
        ]);
      } else if (info.upToDate) {
        Alert.alert('提示', '您的应用版本已是最新.');
      } else {
        Alert.alert('提示', '检查到新的版本'+info.name+',是否下载?\n'+ info.description, [
          {text: '是', onPress: ()=>{this.doUpdate(info)}},
          {text: '否',},
        ]);
      }
    }).catch(err => { 
      Alert.alert('提示', '更新失败.');
    });
  };
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          欢迎使用热更新服务
        </Text>
        <Text style={styles.instructions}>
          这是版本一 {'\n'}
          当前包版本号: {packageVersion}{'\n'}
          当前版本Hash: {currentVersion||'(空)'}{'\n'}
        </Text>
        <TouchableOpacity onPress={this.checkUpdate}>
          <Text style={styles.instructions}>
            点击这里检查更新
          </Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
AppRegistry.registerComponent('test', () => MyProject);
`

就是教程的代码，我打印（isFirstTime，isRolledBack）是undefined，
![image](https://cloud.githubusercontent.com/assets/9291534/17958366/cadfdfac-6acb-11e6-8f35-3a830889cdef.png)

**Comment by tdzl2003** [comment]
应该是原生库没有链接好，你是iOS还是Android？RN版本多少？

**Comment by woshi82** [comment]
@tdzl2003   的是IOS  RN版本是
`"react": "15.3.2",
 "react-native": "^0.37.0",
"react-native-update": "^3.0.3",`

一直的表现就是上面贴的图，  HASH 为空 ，其他（isFirstTime，isRolledBack）是undefined

rnpm link  显示link成功，原生库没有链接好是指什么呢？

**Comment by sunnylqm** [comment]
@woshi82 按照我们的文档修改过jscodelocation的话，如果是在debug模式下，那么热更新的bundle实际上没有调用，因此会是undefined，所以请在release模式下打包和测试

**Comment by woshi82** [comment]
@sunnylqm ，我核对过好多次了
1、这个界面下，我能把配置调成 release模式了 都选了release
![image](https://cloud.githubusercontent.com/assets/11312121/20461647/080b72b2-af3f-11e6-9d16-de279f348806.png)
2、appdelegate.m的配置
![image](https://cloud.githubusercontent.com/assets/11312121/20461669/c6995096-af3f-11e6-8e0d-98ee358813f9.png)
3、就是copy示例代码
`import React, { Component  } from 'react';
import {
  StyleSheet,
  Platform,
  Text,
  View,
  Alert,
  TouchableOpacity,
  Linking
} from 'react-native';

import {
  isFirstTime,
  isRolledBack,
  packageVersion,
  currentVersion,
  checkUpdate,
  downloadUpdate,
  switchVersion,
  switchVersionLater,
  markSuccess,
} from 'react-native-update';

import _updateConfig from '../../update.json';
const {appKey} = _updateConfig[Platform.OS];


export default class Update extends Component {
	componentWillMount(){
    
    console.log(appKey);
    if (isFirstTime) {
      Alert.alert('提示', '这是当前版本第一次启动,是否要模拟启动失败?失败将回滚到上一版本', [
        {text: '是', onPress: ()=>{throw new Error('模拟启动失败,请重启应用')}},
        {text: '否', onPress: ()=>{markSuccess()}},
      ]);
    } else if (isRolledBack) {
      Alert.alert('提示', '刚刚更新失败了,版本被回滚.');
    }
  }
  doUpdate = info => {
    downloadUpdate(info).then(hash => {
      Alert.alert('提示', '下载完毕,是否重启应用?', [
        {text: '是', onPress: ()=>{switchVersion(hash);}},
        {text: '否',},
        {text: '下次启动时', onPress: ()=>{switchVersionLater(hash);}},
      ]);
    }).catch(err => { 
      Alert.alert('提示', '更新失败.');
    });
  };
  checkUpdate = () => {
    console.log(checkUpdate(appKey))
    checkUpdate(appKey).then(info => {
      if (info.expired) {
        Alert.alert('提示', '您的应用版本已更新,请前往应用商店下载新的版本', [
          {text: '确定', onPress: ()=>{info.downloadUrl && Linking.openURL(info.downloadUrl)}},
        ]);
      } else if (info.upToDate) {
        Alert.alert('提示', '您的应用版本已是最新.');
      } else {

        Alert.alert('提示', '检查到新的版本'+info.name+',是否下载?\n'+ info.description, [
          {text: '是', onPress: ()=>{this.doUpdate(info)}},
          {text: '否',},
        ]);
      }
    }).catch(err => { 
      Alert.alert('提示', '更新失败.');
    });
  }
	render() {
		return (
			<View style={styles.container}>
        <Text style={styles.welcome}>
          欢迎使用热更新服务
        </Text>
        <Text style={styles.instructions}>
          这是版本一 {'\n'}
          当前包版本号: {packageVersion}{'\n'}
          当前版本Hash: {currentVersion||'(空)'}{'\n'}
        </Text>
        <TouchableOpacity onPress={this.checkUpdate}>
          <Text style={styles.instructions}>
            点击这里检查更新
          </Text>
        </TouchableOpacity>
      </View>
		);
	}
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});`
4、
![image](https://cloud.githubusercontent.com/assets/11312121/20461752/7c498a3a-af42-11e6-918d-005683eaab04.png)

5、其他的引入lib 的两个包已经引入
6、已经 rnpm link了， 
**求助**  请问我漏了什么吗？  谢谢

**Comment by woshi82** [comment]
也尝试了这样
![image](https://cloud.githubusercontent.com/assets/11312121/20461780/284742fa-af43-11e6-8c75-8f91620ef24d.png)

还是不行……

**Comment by sunnylqm** [comment]
@woshi82 看上去一切正常，有正常发布热更新吗？(pushy bundle)

**Comment by woshi82** [comment]
@sunnylqm  啊～～， 实在抱歉，我今早发现 是我info.plist 没有把reactnative.cn加入例外了
![image](https://cloud.githubusercontent.com/assets/11312121/20468485/2d6c6df2-afd2-11e6-89ce-5d1c061830f4.png)
忘记内部会请求你们的服务了，
