### ISSUE TITLE
https无法访问  导致系统更新功能失败  能否修复  急急！！！！！！！！！

### ISSUE THREAD

**Issue by littleseven007** [reactnativecn/react-native-pushy#291]
https无法访问  导致系统更新功能失败  能否修复  急急！！！！！！！！！

**Comment by sunnylqm** [comment]
抱歉正在处理



---原始邮件---
发件人: "qiyuexi"<notifications@github.com&gt;
发送时间: 2019年11月1日(星期五) 中午12:47
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [reactnativecn/react-native-pushy] https无法访问  导致系统更新功能失败  能否修复  急急！！！！！！！！！ (#291)



https无法访问  导致系统更新功能失败  能否修复  急急！！！！！！！！！

**Comment by sunnylqm** [comment]
已修复
