### ISSUE TITLE
关于ios全量更新覆盖安装的问题

### ISSUE THREAD

**Issue by EwanBerg** [reactnativecn/react-native-pushy#292]
集成过热更新后，jslocation替换为jsCodeLocation = [RCTHotUpdate bundleURL];
但是，在自己不修改版本号，发布了更新包到分发平台，同时删除之前所有的热更新版本及版本基础包，在控制端发布新的版本对比包，用户下载覆盖安装仍是之前的内容，请问，在打包之前是否需要先生成新的离线包然后再发布，用户才能看到更改内容？

**Comment by sunnylqm** [comment]
需要修改原生版本号

**Comment by EwanBerg** [comment]
> 需要修改原生版本号

谢谢您，顺便问下获取下载进度有计划吗？

**Comment by sunnylqm** [comment]
有计划，但优先级比较低
