### ISSUE TITLE
请问可以将用自己的服务器做热更新服务器吗？

### ISSUE THREAD

**Issue by 17554265585** [reactnativecn/react-native-pushy#293]
因为使用贵方提供的下载量有限制，如有可能提供服务端代码将是再好不过了，感恩

**Comment by sunnylqm** [comment]
我们未来会启用商用服务，所以不会提供服务器端代码，抱歉



---原始邮件---
发件人: "17554265585"<notifications@github.com&gt;
发送时间: 2019年11月20日(星期三) 上午9:32
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [reactnativecn/react-native-pushy] 请问可以将用自己的服务器做热更新服务器吗？ (#293)



因为使用贵方提供的下载量有限制，如有可能提供服务端代码将是再好不过了，感恩

**Comment by 17554265585** [comment]
好的，感谢回答

**Comment by 17554265585** [comment]
另外为什么微软的审核不会被拒，如果把这个解决了的话，就算是付费服务，也是有很多人会使用的，毕竟相对于微软的，这个友好太多了，最近集成微软的一直没办法实现增量更新，希望尽快推出吧

**Comment by sunnylqm** [comment]
不清楚，怀疑是代码关键字扫描，我们上了一个新的改名后的版本，有兴趣的话可以试下

**Comment by sunnylqm** [comment]
另外我们有提供付费的私有部署，有兴趣可以联系(QQ:402740419)  @17554265585

**Comment by 17554265585** [comment]
好的，十分感谢
