### ISSUE TITLE
禁用全量更新的通知

### ISSUE THREAD

**Issue by tdzl2003** [reactnativecn/react-native-pushy#294]
最近pushy公开服务遭遇了连续两次因为开发者禁用差异更新而导致流量被严重消耗的事故，对我们造成了一定的经济损失，因此我们关闭了全量更新的功能，要求强制采用差异更新的方式。

具体影响如下：
1. 如果服务端pdiffUrl和diffUrl均没有生成好，服务端会暂时返回upToDate: true，因此新上传的更新在绑定之后可能需要等待一小段时间（取决于整个资源包的大小）才能更新到。
2. 如果pdiffUrl和diffUrl已经生成好，现在不会返回updateUrl字段，因此之前禁用了差异更新的应用会在这里更新失败。

如果您希望继续使用全量更新，可以联系我们(QQ:402740419)申请私有部署，私有部署由开发者自行承担服务器和流量消耗。公开服务变动造成的不便敬请谅解。

**Comment by xxf1110** [comment]
checkUpdate error 
之前热更新是好的，现在执行热更新报错
![qq_pic_merged_1574841513996](https://user-images.githubusercontent.com/31277179/69704667-db155e80-112e-11ea-94b9-c2e66dd016b0.jpg)

**Comment by sunnylqm** [comment]
@xxf1110 请另开issue详细描述

**Comment by xxf1110** [comment]
ok
