### ISSUE TITLE
使用5.3.1-5.4.0版本的无法检查更新，请更新到最新版

### ISSUE THREAD

**Issue by xxf1110** [reactnativecn/react-native-pushy#297]
第一次发包 检查版本结果
![qq_pic_merged_1574841791436](https://user-images.githubusercontent.com/31277179/69704927-74447500-112f-11ea-9740-30fc0608097d.jpg)
第二次执行热更新，绑定第一次的包，检查版本报错
![qq_pic_merged_1574841513996](https://user-images.githubusercontent.com/31277179/69705019-a1912300-112f-11ea-9acc-f04a1e27c303.jpg)
版本信息：
"react-native": "0.61.4"
"react-native-update": "^5.4.0"

请问是什么原因导致的吗？

**Comment by sunnylqm** [comment]
请列出各种版本信息，adb日志输出

**Comment by xxf1110** [comment]
![image](https://user-images.githubusercontent.com/31277179/69705632-eb2e3d80-1130-11ea-9ec1-4b394d5074b2.png)

**Comment by sunnylqm** [comment]
列出package.json中所有的版本信息，以及报错前后的adb日志输出

**Comment by xxf1110** [comment]
{
  "name": "EasstMobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@ant-design/icons-react-native": "^1.0.2",
    "@ant-design/react-native": "^3.2.0",
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/netinfo": "^4.6.0",
    "axios": "^0.19.0",
    "jwt-decode": "^2.2.0",
    "mobx": "^5.15.0",
    "mobx-react": "^6.1.4",
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-elements": "^1.2.7",
    "react-native-elements-input-password": "^1.0.5",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-location": "^2.5.0",
    "react-native-router-flux": "^4.0.6",
    "react-native-update": "^5.4.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^7.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@babel/plugin-proposal-decorators": "^7.7.0",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}


没有报错，热更新日志正常

**Comment by Jasonellen** [comment]
同问，我的项目上周还是好的，现在发布热更新也没有反应了，然后发现是检查热更新的时候就报错了。但是发布热更新绑定package的时候 都是oK的，没有报任何错误，就是 进入app没有反应
"react-native-update": "^5.4.0",
"react-native": "0.61.4",

**Comment by sunnylqm** [comment]
更新到5.5.1 或是 删掉node_modules/react-native-update/lib/index.js中的54行 https://github.com/reactnativecn/react-native-pushy/blob/master/lib/index.js#L54

**Comment by xxf1110** [comment]
非常感谢，我尝试了一下，更新到5.5.1 并且重新上传新包，确实是ok的。
有没有办法引导让安装了久包的客户下载我这次重新上传的新包？

**Comment by sunnylqm** [comment]
在网页端可以给一个下载地址

**Comment by Jasonellen** [comment]
已解决 感谢 @xxf1110 @sunnylqm

**Comment by xxf1110** [comment]
@sunnylqm  非常感谢，已解决

**Comment by playscforever** [comment]
。。。。诶，搞了几天

**Comment by nfq6612** [comment]
我也是还以为本地问题呢
