### ISSUE TITLE
5.5.1热更新后闪退

### ISSUE THREAD

**Issue by xxf1110** [reactnativecn/react-native-pushy#301]
包版本：
"react": "16.9.0",
 "react-native-update": "^5.5.1",
1、之前5.5.1热更新是正常的，今天发布热更新闪退，更新失败，
2、重新打apk包上架热更新是好的，之前的apk包热更细出问题了？

**Comment by sunnylqm** [comment]
请给出闪退的adb logcat日志



---原始邮件---
发件人: "xxf1110"<notifications@github.com&gt;
发送时间: 2019年12月5日(周四) 中午12:53
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [reactnativecn/react-native-pushy] 5.5.1热更新后闪退 (#301)



包版本：
 "react": "16.9.0",
 "react-native-update": "^5.5.1",
 1、之前5.5.1热更新是正常的，今天发布热更新闪退，更新失败，
 2、重新打apk包上架热更新是好的，之前的apk包热更细出问题了？

**Comment by xxf1110** [comment]
![image](https://user-images.githubusercontent.com/31277179/70205472-13382500-175f-11ea-9480-a8be0276d964.png)
log is ok

**Comment by xxf1110** [comment]
![image](https://user-images.githubusercontent.com/31277179/70205670-c3a62900-175f-11ea-955d-6a773e3a25a9.png)
![image](https://user-images.githubusercontent.com/31277179/70205687-d7ea2600-175f-11ea-890b-bdd8072bdfa0.png)
还有最新的包不应该是1.1吗？

**Comment by Jasonellen** [comment]
同样的版本，同样的问题，我还以为是我代码问题，老是更新后就闪退，撤回代码更新安装还是会闪退，然后发现  安装原始 包也不会提示 有新更新，之前安转原始包，刚打开就会提示有更新的！前2天还是好好的呢 
"react-native-update": "^5.5.1",
"react-native": "0.61.4",

**Comment by Jasonellen** [comment]
@sunnylqm 有解决办法么

**Comment by sunnylqm** [comment]
闪退一定在adb logcat里有所体现的，没有日志我无法判断发生了什么事情

**Comment by xxf1110** [comment]
release 版我怎么能拿到日志呢？你知道吗？

**Comment by sunnylqm** [comment]
release拿日志和debug没有区别啊

**Comment by xxf1110** [comment]
还有个问题？我删除1.2 的包，重新安装1.0 的包也不提示我更新了1.1了

**Comment by sunnylqm** [comment]
另外的问题请另外开issue，一个一个问题分开描述

**Comment by xxf1110** [comment]
![image](https://user-images.githubusercontent.com/31277179/70215479-87cb8d80-1778-11ea-9690-e79e1a56d47f.png)
APP更新后最新adb 日志

**Comment by sunnylqm** [comment]
截图请再往上一点

**Comment by xxf1110** [comment]
![image](https://user-images.githubusercontent.com/31277179/70216741-20630d00-177b-11ea-9a81-2ffb311f163b.png)
![image](https://user-images.githubusercontent.com/31277179/70216758-2822b180-177b-11ea-9aca-852afd509183.png)
这是闪退的全部错误日志

**Comment by sunnylqm** [comment]
上面是一个js报错，在某处调用某个叫hide的方法出错了

**Comment by xxf1110** [comment]
好的，我找一下，非常感谢

**Comment by xxf1110** [comment]
问题解决了，非常感谢，新增加的依赖是无法热更新的是吧？

**Comment by sunnylqm** [comment]
任何原生方面的修改无法热更新

**Comment by xxf1110** [comment]
好的，非常感谢
