### ISSUE TITLE
突然不提示热更新新版本

### ISSUE THREAD

**Issue by Jasonellen** [reactnativecn/react-native-pushy#302]
原始包1.0版本，热更新到1.1版本，手机卸载，今天安装原始发现不会提示 有新更新，之前安转原始包，刚打开就会提示有更新的！前2天还是好好的呢
现在好像检测不到了
"react-native-update": "^5.5.1",
"react-native": "0.61.4",

**Comment by sunnylqm** [comment]
试着清除一下app缓存数据？

**Comment by Jasonellen** [comment]
问题是 我把手机 app卸载了，不是覆盖的，等于是新手机 首次安装，没有缓存的呢

**Comment by sunnylqm** [comment]
我明白你的意思，但现在是在排查问题，我能想到的可能是
1、可能（不明原因）有缓存，通过清除缓存排除
2、可能并不是原始包，可以发一个新的热更新试试能否检测到

**Comment by xxf1110** [comment]
我试了一下，发一个新的热更新是能检测到的，但是安装后app 闪退

**Comment by sunnylqm** [comment]
闪退请给出adb logcat的日志

**Comment by Jasonellen** [comment]
你好，
1，我这苹果手机没办法清除缓存，只能卸载app
2，新生产ipa包 上传也是可以 检测到 新的更新，
3，之前的ipa包的新更新检测不到了，前2天是可以检测的，这个原因很奇怪，因为是公司在用，包肯定是原始包，不会错

**Comment by sunnylqm** [comment]
@xxf1110 @Jasonellen  请两位不要混在一个issue里提问，你们一个是android一个是ios，这样完全让我混乱
@Jasonellen 
1. 目前客户端5.5.1开始会检查包的编译时间，如果时间不对应是不会返回结果的（意味着不是原始包）。原始包的定义是`当时`编译完成的那个包，哪怕完全不改代码重新编译一次，也`不是`原始包。
2. 目前ios端热更新有个偶尔出现的闪退的bug（报找不到app.json），仍然在排查

**Comment by Jasonellen** [comment]
好的，多谢
