### ISSUE TITLE
 pushy uploadIpa xxx.ipa 报错 Error: Can not get build time for this app.

### ISSUE THREAD

**Issue by Elderkly** [reactnativecn/react-native-pushy#304]
pod install成功链接了库但还是无法上传ipa包

![image](https://user-images.githubusercontent.com/32736776/70228081-b5233600-178e-11ea-963d-82239411961e.png)

![image](https://user-images.githubusercontent.com/32736776/70228094-ba808080-178e-11ea-9b69-b327003427db.png)

System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 743.64 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.2, 25.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-21 | Android TV ARM EABI v7a, android-21 | Android TV Intel x86 Atom, android-21 | ARM EABI v7a, android-21 | Intel x86 Atom, android-21 | Intel x86 Atom_64, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-23 | Android TV ARM EABI v7a, android-23 | Android TV Intel x86 Atom, android-23 | Android Wear ARM EABI v7a, android-23 | Android Wear Intel x86 Atom, android-23 | ARM EABI v7a, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Android TV Intel x86 Atom, android-24 | ARM 64 v8a, android-24 | ARM EABI v7a, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Android TV Intel x86 Atom, android-26 | China version of Android Wear Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-Q | Android TV Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-asset: 2.0.0
    react-native-cli: 2.0.1
    react-native-update-cli: 0.1.0

**Comment by sunnylqm** [comment]
有重新打包吗



---原始邮件---
发件人: "QZP743"<notifications@github.com&gt;
发送时间: 2019年12月5日(周四) 晚上6:41
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [reactnativecn/react-native-pushy]  pushy uploadIpa xxx.ipa 报错 Error: Can not get build time for this app. (#304)



pod install成功链接了库但还是无法上传ipa包
 

 

 
System:
 OS: macOS Mojave 10.14.6
 CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
 Memory: 743.64 MB / 8.00 GB
 Shell: 3.2.57 - /bin/bash
 Binaries:
 Node: 12.10.0 - /usr/local/bin/node
 Yarn: 1.17.3 - /usr/local/bin/yarn
 npm: 6.10.3 - /usr/local/bin/npm
 Watchman: 4.9.0 - /usr/local/bin/watchman
 SDKs:
 iOS SDK:
 Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
 Android SDK:
 API Levels: 21, 23, 24, 25, 26, 27, 28, 29
 Build Tools: 25.0.2, 25.0.3, 28.0.3, 29.0.0, 29.0.2
 System Images: android-21 | Android TV ARM EABI v7a, android-21 | Android TV Intel x86 Atom, android-21 | ARM EABI v7a, android-21 | Intel x86 Atom, android-21 | Intel x86 Atom_64, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-23 | Android TV ARM EABI v7a, android-23 | Android TV Intel x86 Atom, android-23 | Android Wear ARM EABI v7a, android-23 | Android Wear Intel x86 Atom, android-23 | ARM EABI v7a, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Android TV Intel x86 Atom, android-24 | ARM 64 v8a, android-24 | ARM EABI v7a, android-24 | Intel x86 Atom, android-24 | Intel x86 Atom_64, android-24 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Android TV Intel x86 Atom, android-26 | China version of Android Wear Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-Q | Android TV Intel x86 Atom
 IDEs:
 Android Studio: 3.5 AI-191.8026.42.35.5791312
 Xcode: 11.2/11B52 - /usr/bin/xcodebuild
 npmPackages:
 react: 16.9.0 =&gt; 16.9.0
 react-native: 0.61.1 =&gt; 0.61.1
 npmGlobalPackages:
 react-native-asset: 2.0.0
 react-native-cli: 2.0.1
 react-native-update-cli: 0.1.0

**Comment by Elderkly** [comment]
> 有重新打包吗
> […](#)

有的

**Comment by sunnylqm** [comment]
方便的话加我qq34731408



---原始邮件---
发件人: "QZP743"<notifications@github.com&gt;
发送时间: 2019年12月5日(周四) 晚上9:14
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Sunny Luo"<sunnylqm@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [reactnativecn/react-native-pushy]  pushy uploadIpa xxx.ipa 报错 Error: Can not get build time for this app. (#304)


 
有重新打包吗
 …
  
有的

**Comment by sunnylqm** [comment]
还有看下cocoapods版本是1.4以上吗
