### ISSUE TITLE
pushy uploadIpa xxx.ipa 报错 Error: Can not get build time for this    我手动链接库不行吗  我的pod命令现在有问题

### ISSUE THREAD

**Issue by lwxzks** [reactnativecn/react-native-pushy#306]
"react": "16.6.3",
 "react-native": "0.58.6",
"react-native-update": "^5.5.2",

**Comment by sunnylqm** [comment]
嗯 5.5以上不支持非pod方式，实在不行只能尝试5.3以下（不过那个肯定通不过审核）

**Comment by sunnylqm** [comment]
你可以研究下怎么在打包时执行这个脚本 https://github.com/reactnativecn/react-native-pushy/blob/master/scripts/generateiOSBuildTime.sh  同时把生成的txt文件打包到最终的ipa文件中

**Comment by lwxzks** [comment]
@sunnylqm  怎么把生成的txt文件打包进 ipa中

**Comment by sunnylqm** [comment]
应该是要在build phase里加个copy阶段吧

**Comment by lwxzks** [comment]
@sunnylqm  谢谢 已经解决了这个问题了

**Comment by sunnylqm** [comment]
好的，可以分享下具体做法吗？

**Comment by lwxzks** [comment]
就是先在 xcode 的 build phases 添加一个 run script  运行脚本 
#!/bin/bash
set -x
DEST="../node_modules/react-native-update/ios/"
date +%s > "$DEST/pushy_build_time.txt"

运行项目的时候就会在../node_modules/react-native-update/ios/文件夹下面生成一个pushy_build_time.txt 文件
 
然后在copy bundle resources   把生成的pushy_build_time.txt文件添加进去

**Comment by sunnylqm** [comment]
谢谢
