### ISSUE TITLE
IOS 热更新被拒有新的解决方案没有

### ISSUE THREAD

**Issue by wybztl** [reactnativecn/react-native-pushy#307]
11月底我们的热更新被苹果拒绝后，后面全部删除热更新代码已审核通过，请问后续有什么新的解决方案没有

**Comment by sunnylqm** [comment]
https://github.com/reactnativecn/react-native-pushy/issues/285#issuecomment-554433159

**Comment by wybztl** [comment]
不敢尝试啊，上次被拒过了两次，代码完全删干净才审核通过的，前前后后两个星期，怕了怕了。。。
