### ISSUE TITLE
热更新失效

### ISSUE THREAD

**Issue by xxf1110** [reactnativecn/react-native-pushy#308]
"react": "16.9.0",
"react-native": "0.61.4",
"react-native-update": "^5.5.1",

新打的包，然后发热更新。提示应用已是最新 info.upToDate 返回值为true

**Comment by sunnylqm** [comment]
确定设备上装的包和新打的包是同一个吗

**Comment by xxf1110** [comment]
是同一个，打包后立马装的

**Comment by sunnylqm** [comment]
发的热更新确定有绑到新包上吗

**Comment by xxf1110** [comment]
绑定了，我把新包删掉，会提示我原生包已过期，下载新包 info.expired 返回true

**Comment by xxf1110** [comment]
连续发了两个热更新都没有提示更新

**Comment by xxf1110** [comment]
@sunnylqm 是服务出问题了吗？

**Comment by ss876079056** [comment]
我也遇到这个问题，没有弹框提示更新

**Comment by ss876079056** [comment]
@xxf1110 你解决了吗

**Comment by xxf1110** [comment]
@ss876079056 没有解决，全程没有任何报错，热更新不了

**Comment by DirkForDallas** [comment]
我也出现问题了，检查更新接口直接返回
{
	"upToDate": true,
	"ok": 1
}

**Comment by sunnylqm** [comment]
正在处理，请稍候

**Comment by sunnylqm** [comment]
应该已经恢复了，抱歉昨晚回家就睡觉了没有跟进

**Comment by DirkForDallas** [comment]
@sunnylqm   还是不行额

**Comment by sunnylqm** [comment]
积压了较多任务，请再耐心等一段时间

**Comment by sunnylqm** [comment]
先关了，有问题再开

**Comment by xxf1110** [comment]
等了20分钟还是不行，重新打包测试也不行

**Comment by sunnylqm** [comment]
@xxf1110 加我qq34731408
