### ISSUE TITLE
热更新检测不到 这两天是服务器有问题吗

### ISSUE THREAD

**Issue by bltbbb** [reactnativecn/react-native-pushy#309]
{
"upToDate": true,
"ok": 1
}
前天出现一次
刚刚又出现了
检测不到更新

**Comment by sunnylqm** [comment]
服务器目前正常，还有问题的话加我qq34731408

**Comment by bltbbb** [comment]
> 服务器目前正常，还有问题的话加我qq34731408

已恢复 thanks
