### ISSUE TITLE
android 热更

### ISSUE THREAD

**Issue by hkchkc** [reactnativecn/react-native-pushy#31]
更改apk版本号，上传apk还是1.0，而且不删除原本的apk会体会valilation error，但是IPA就不会出现这个问题

**Comment by lee1994522** [comment]
同样的问题。求助@tdzl2003

**Comment by tdzl2003** [comment]
Validation Error出现这个错误提示都是因为你上传了相同版本号的包。因为我们在热更新的时候使用版本号作为标识，并且你也不可能将相同版本号的包发布到应用市场，所以你应该修改版本号再重新打包。

**Comment by forrest23** [comment]
@tdzl2003 我想发布多个包，然后我修改了VersionCode, VersionName，然后上传之后，还是报Validation error，应该是服务端判断有bug了

**Comment by tdzl2003** [comment]
修改之后重新打包了吗？如果依然有问题的话可以联系我QQ 402740419或者邮箱dy@tdzl.cn发送更详细的信息，譬如无法上传的包、你的应用ID或者appkey，我可以协助排查。

**Comment by forrest23** [comment]
@tdzl2003  不好意思，是我搞错了。我只是修改了AndroidManifest.xml 文件中的VersionCode, VersionName。没有修改android/app/build.gradle 文件中的VersionCode, VersionName。所以打包之后还是没变。
