### ISSUE TITLE
热更新版本升级后，打出的包一直是第一版的，不提示热更新

### ISSUE THREAD

**Issue by ss876079056** [reactnativecn/react-native-pushy#310]

**Comment by sunnylqm** [comment]
没看懂，什么叫打出的包一直是第一版的？

**Comment by ss876079056** [comment]
android第一次打包上传热更新的版本

**Comment by ss876079056** [comment]
后面修改的代码都没有了

**Comment by ss876079056** [comment]
但是模拟器上跑是好的

**Comment by sunnylqm** [comment]
还是看不懂在说什么，就说具体的操作步骤吧

**Comment by ss876079056** [comment]
嗯～～我把热更新版本更新到"^5.5.2"后重新打包发布了个新的热更新版本2.4，
<img width="927" alt="E92D1747-B037-4CB0-B76F-CE434B6D6912" src="https://user-images.githubusercontent.com/32288461/71145322-24ebf300-225c-11ea-99db-71e1871729ea.png">，然后后续进行了升级，没有提示热更新，然后重新andorid进行打包后发现代码还是2.4版本的

**Comment by sunnylqm** [comment]
还是看不懂。请注意区分一个重要概念，打原生包，还是打js更新包。版本也分原生版本和热更新版本。原生包和更新包有一个绑定关系。没有绑定更新包的原生包不会收到更新提示。如果有多个原生包，需要单独分别绑定。

**Comment by ss876079056** [comment]
嗯～～就是我升级热更新版本后，打包了一个原生包A，上传到了热更新平台版本号为2.4，然后修改了一些js代码后再打js更新包后，没有提示热更新，然后我又在打包了个原生包B，发现代码跟原生包A相同，修改的代码未显示

**Comment by sunnylqm** [comment]
加我qq34731408

**Comment by sunnylqm** [comment]
服务器异常波动，已修复
