### ISSUE TITLE
最近热更新检测老是检测不到是什么原因呢

### ISSUE THREAD

**Issue by onelinewalk** [reactnativecn/react-native-pushy#311]

**Comment by sunnylqm** [comment]
请描述具体一点，起码要说个版本什么的啊

**Comment by onelinewalk** [comment]
"react-native-update": "^5.5.1",
 "react-native": "0.60.5",
之前一发热更，客户端过几秒就可以检测到有新版本，最近发了热更后，有时候过几个小时，有时候要隔一天，客户端才检测到有新版本。而且不同的客户端，新版本提示的时间间隔有可能很长

**Comment by sunnylqm** [comment]
加我qq34731408

**Comment by sunnylqm** [comment]
服务器波动
