### ISSUE TITLE
新发布的热更新包检测不到

### ISSUE THREAD

**Issue by xxf1110** [reactnativecn/react-native-pushy#312]
"react-native-update": "^5.5.1",
"react-native": "0.60.4",
三天前发热更，几秒就可以检测到有新版本，今天连续发了三个热更都没检测到？

**Comment by codingDreamForever** [comment]
我昨天测试都是可以的，今天就不行了，连checkUpdate有的时候都会报错，之前的已经删除的历史版本反而会收到大版本更新

**Comment by codingDreamForever** [comment]
现在又可以使用了，谢谢官方的努力
