### ISSUE TITLE
更新后重启APP闪退（找不到bundle文件）

### ISSUE THREAD

**Issue by frankyLHJ** [reactnativecn/react-native-pushy#313]
version:
"react-native": "0.61.4",
"react-native-update": "5.5.1",
compileSdkVersion 28
buildToolsVersion '28.0.3'

error:
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/********/files/_update/Fq4fAR6o61pMliUhgxqhowyrIQkU/index.bundlejs: No such file or directory

**Comment by sunnylqm** [comment]
pushy bundle后生成的.ppk文件发上来看下

**Comment by frankyLHJ** [comment]
已上传
[android.1578367789758.ppk.zip](https://github.com/reactnativecn/react-native-pushy/files/4035068/android.1578367789758.ppk.zip)

**Comment by sunnylqm** [comment]
+我qq 34731408

**Comment by sunnylqm** [comment]
请确保你上传的apk/ipa不是debug版本
