### ISSUE TITLE
ios 热更新后，重启应用版本被回滚

### ISSUE THREAD

**Issue by onelinewalk** [reactnativecn/react-native-pushy#314]
"react-native": "0.60.5",
react-native-update": "^5.5.1  

发布热更后，ios可以检测到热更并可以更新到最新版本，更新完毕重启成功，看到内容变化
可当将APP结束进程，重新打开发现回滚到最初版本
并且检测不到有版本更新

android 则正常

**Comment by Maochengfag** [comment]
@onelinewalk 有没有做过RN0.44 升级适配react-native-update

**Comment by sunnylqm** [comment]
请参考  https://pushy.react-native.cn/docs/faq.html#%E7%83%AD%E6%9B%B4%E6%96%B0%E6%88%90%E5%8A%9F%E5%AE%8C%E6%88%90%EF%BC%8C%E4%BD%86%E6%98%AF%E9%87%8D%E5%90%AF%E5%90%8E%E5%8F%88%E5%9B%9E%E6%BB%9A%E4%BA%86%E6%98%AF%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F

如果还有问题请重开issue
