### ISSUE TITLE
重新createApp后请记得清理编译缓存

### ISSUE THREAD

**Issue by WillCoco** [reactnativecn/react-native-pushy#315]
react-native-update-cli: 0.1.0
react-native-update: 5.5.4
react-native:0.61.5
platform:android

步骤
1.生成release.apk, uploadApk上传
2.bundle包生成热更包并绑定package
![image](https://user-images.githubusercontent.com/20414501/72676153-f36b7f00-3ac8-11ea-88fe-ea96ae7de18e.png)
3.启动release.apk, 调用checkUpdate

adb logcat抓到方法报空指针:
W ReactNativeJS: { [Error: Cannot read property 'id' of null] line: 527, column: 576, sourceURL: 'index.android.bundle' }, '检查失败555'

![image](https://user-images.githubusercontent.com/20414501/72676141-cfa83900-3ac8-11ea-8a61-b2350cddbf81.png)

**Comment by WillCoco** [comment]
是服务端代码bug吗?
![image](https://user-images.githubusercontent.com/20414501/72676673-e8b3e880-3ace-11ea-8a90-a0f815f918e1.png)

**Comment by WillCoco** [comment]
![image](https://user-images.githubusercontent.com/20414501/72676695-14cf6980-3acf-11ea-88e6-4ad0fb8ae7e4.png)

**Comment by WillCoco** [comment]
发现是重新createApp后, appkey重新生成了, 再次打包release.Apk时还是缓存的appKey

**Comment by xxj95719** [comment]
怎么解决

**Comment by sunnylqm** [comment]
cd android && ./gradlew clean
