### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by qiujie8092916** [reactnativecn/react-native-pushy#317]
pod install安装好后，XCode编译的时候报错

`Showing All Messages
/Users/qiujie/Library/Developer/Xcode/DerivedData/ISkyTrip-aigdjylbgqvpuzdgeanybszlesuc/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-update.build/Script-CCA248AA1E9A0309B673D7DC50931B1A.sh: line 2: ../../node_modules/react-native-update/scripts/generateiOSBuildTime.sh: No such file or directory
`

**Comment by sunnylqm** [comment]
试下这样改看行不行
https://github.com/reactnativecn/react-native-pushy/commit/19f060abf5554bad86b73f7d241f7662181d9cac

**Comment by Archer-Programmer** [comment]
你好，@sunnylqm ，我用的react-native-pushy版本是5.5.8，我现在也碰到这个问题，并且react-native-update.podspec这个文件跟 19f060a 这里提到的是完全一样的，但是现在依然报错

**Comment by sunnylqm** [comment]
基本上是路径问题，可以自己尝试调整路径

**Comment by HeMa321** [comment]
一样的问题  "react-native": "0.57.0","react-native-update": "^5.5.8", 
Xcode 11.4 iOS调整路径都测试了,没效果

**Comment by sunnylqm** [comment]
试下5.5.9版本或参照这个试试 https://github.com/reactnativecn/react-native-pushy/commit/5abe7b181b16e126d1ace3b5ada483760809ed11#diff-fb2e2b0fe0a83e2b54fc9b3c990f0f6b

**Comment by sunnylqm** [comment]
先关闭了，有问题再开启
