### ISSUE TITLE
IOS 集成react-native-update 报错啊！！！

### ISSUE THREAD

**Issue by lccxxq** [reactnativecn/react-native-pushy#318]
@sunnylqm @lvbingru @Abreto @geniuslinchao 
ios原生工程集成了RN，然后RN集成了react-native-pushy服务，但是一上来build 就报错！！！下面是报错信息，麻烦大佬们看一下！

/Users/rimatsu/Library/Developer/Xcode/DerivedData/ISkyTrip-eklpbqqpfvaxisdrhryefhgybmnh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-update.build/Script-CCA248AA1E9A0309B673D7DC50931B1A.sh: line 2: ../../node_modules/react-native-update/scripts/generateiOSBuildTime.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by sunnylqm** [comment]
自行集成的话，项目结构未必和默认的rn项目结构一致，所以需要自行调整这里的脚本路径  https://github.com/reactnativecn/react-native-pushy/blob/master/react-native-update.podspec#L21

**Comment by sunnylqm** [comment]
试下这样改看行不行
https://github.com/reactnativecn/react-native-pushy/commit/19f060abf5554bad86b73f7d241f7662181d9cac

**Comment by qiujie8092916** [comment]
原生集成的RN的话，项目结构各不相同，除了修改react-native-update.podspec里的脚本路径，还要修改generateiOSBuildTime.sh脚本里的生成txt的路径。
@sunnylqm 你们能不能动态获取，或者是参数传入，或者把这点在官网里指出，感觉这点比较重要

**Comment by sunnylqm** [comment]
@qiujie8092916 我本人缺乏原生经验，如果有好的方案欢迎赐教

**Comment by sunfan1** [comment]
react-native-update 5.5.8，xcode 11.3.1出现你这个问题了。。
把react-native-update.podspec中的$(SRCROOT)/../换成../../就可以了
莫名其妙的问题

**Comment by sunnylqm** [comment]
试下5.5.9版本或参照这个修改试试  https://github.com/reactnativecn/react-native-pushy/commit/5abe7b181b16e126d1ace3b5ada483760809ed11#diff-fb2e2b0fe0a83e2b54fc9b3c990f0f6b

**Comment by Maochengfag** [comment]
Which version of RN can be support by the  leasted version of  react-native-update ?@@sunnylqm

**Comment by sunnylqm** [comment]
先关闭了，有问题再开启

**Comment by xiaoaren** [comment]
我解决的办法是:  `/ios/bundle`文件夹下，执行下 `pod install` 就可以了
