### ISSUE TITLE
请升级cli后再尝试( npm i -g react-native-update-cli )

### ISSUE THREAD

**Issue by DirkForDallas** [reactnativecn/react-native-pushy#320]
pushy bundle --platform ios
请升级cli后再尝试( npm i -g react-native-update-cli )

**Comment by sunnylqm** [comment]
那就照着做呗？



---原始邮件---
发件人: "yaohengly"<notifications@github.com&gt;
发送时间: 2020年3月10日(周二) 中午1:37
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [reactnativecn/react-native-pushy] 请升级cli后再尝试( npm i -g react-native-update-cli ) (#320)



pushy bundle --platform ios
 请升级cli后再尝试( npm i -g react-native-update-cli )

**Comment by DirkForDallas** [comment]
react-native-update-cli  和 react-native-update 都升级到最新版本了，报同样错误！
还需要升级react-native 版本吗？

**Comment by sunnylqm** [comment]
版本号截图看下



---原始邮件---
发件人: "yaohengly"<notifications@github.com&gt;
发送时间: 2020年3月10日(周二) 中午1:55
收件人: "reactnativecn/react-native-pushy"<react-native-pushy@noreply.github.com&gt;;
抄送: "Sunny Luo"<sunnylqm@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [reactnativecn/react-native-pushy] 请升级cli后再尝试( npm i -g react-native-update-cli ) (#320)



react-native-update-cli  和 react-native-update 都升级到最新版本了，报同样错误！
 还需要升级react-native 版本吗？

**Comment by DirkForDallas** [comment]
升级完后重启终端就好了， 先关闭了

**Comment by DirkForDallas** [comment]
升级完后重启终端就好了， 先关闭了

**Comment by markweng** [comment]
![92561583832855_ pic](https://user-images.githubusercontent.com/7027991/76299062-6210d000-62f5-11ea-897b-eb63c61ed632.jpg)
升级后查看版本还是

**Comment by markweng** [comment]
我也遇到这个问题了 按提示做了升级后react-native-update-cli版本还是0.1.0
![92561583832855_ pic](https://user-images.githubusercontent.com/7027991/76299357-e95e4380-62f5-11ea-9787-d07bf8de5ce6.jpg)

pushy -v
react-native-update-cli: 0.1.0
react-native-update: 5.5.6

**Comment by markweng** [comment]
重启终端也没效果

**Comment by DirkForDallas** [comment]
项目根目录下执行  npm i -g react-native-update-cli
成功后显示  react-native-update-cli  最新版本1.0.8
退出终端，重启

> 重启终端也没效果
