### ISSUE TITLE
Error: 请升级cli后再尝试( npm i -g react-native-update-cli )

### ISSUE THREAD

**Issue by markweng** [reactnativecn/react-native-pushy#321]
pushy uploadIpa xxx.ipa
Error: 请升级cli后再尝试( npm i -g react-native-update-cli )
    at xxx/node_modules/react-native-update/local-cli/lib/api.js:8:27
    at Generator.next (<anonymous>)
    at step (xxx/node_modules/react-native-update/local-cli/lib/api.js:76:191)
    at xxx/node_modules/react-native-update/local-cli/lib/api.js:76:361
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

按提示执行完命令，重启终端执行还是报错

**Comment by sunnylqm** [comment]
请给个执行命令的截图

**Comment by markweng** [comment]
![image](https://user-images.githubusercontent.com/7027991/76304731-d69c3c80-62fe-11ea-9dfd-7506723467a2.png)

**Comment by markweng** [comment]
![image](https://user-images.githubusercontent.com/7027991/76304795-f03d8400-62fe-11ea-8247-0d54e7429c1c.png)

**Comment by sunnylqm** [comment]
npm i 命令呢？

**Comment by markweng** [comment]
![image](https://user-images.githubusercontent.com/7027991/76309074-00f1f800-6307-11ea-8165-66d3463b576b.png)

**Comment by sunnylqm** [comment]
我看到你的全局路径和默认的并不一样，应该是自己做了一些修改，但修改又不完整
我建议你用npm config list命令查看下与.npm-global这个路径有关的配置文件，将这行配置去掉，然后重新安装

**Comment by markweng** [comment]
按照您的思路解决了🙏
