### ISSUE TITLE
Error: 无法获取此包的编译时间戳。请更新react-native-update到最新版本后重新打包上传

### ISSUE THREAD

**Issue by Maochengfag** [reactnativecn/react-native-pushy#322]
RN 0.44.0 react-native-update 4.0.6
之前热更新的时候遇到这样的问题 请问如何进行操作
: edz$ pushy uploadIpa /Users/edz/Documents/HOT1.0.0.1\ 2020-03-11\ 11-02-02/good.ipa 
Error: 无法获取此包的编译时间戳。请更新react-native-update到最新版本后重新打包上传。
    at getIpaInfo (/usr/local/lib/node_modules/react-native-update-cli/lib/utils/index.js:101:11)
    at <anonymous>
192:BTHot edz$

**Comment by sunnylqm** [comment]
抱歉，老版本已不再支持，请更新到最新版本

**Comment by Maochengfag** [comment]
RN 和 react-native-update 都要更新么?

**Comment by sunnylqm** [comment]
目前应该最低要求RN0.46以上版本

**Comment by Maochengfag** [comment]
我的解决方法
https://blog.csdn.net/Coding_Physical/article/details/104803512

**Comment by sunnylqm** [comment]
思路是对的，但我怀疑android版本可能不兼容
而且你们是不准备上架吗？4月底以后必须用ios13 sdk编译了，老版本rn就歇菜了

**Comment by Maochengfag** [comment]
我们app比较特殊




| |
毛成方
|
|
邮箱：maochengfang@126.com
|

签名由 网易邮箱大师 定制

在2020年03月11日 20:14，Sunny Luo 写道：

思路是对的，但我怀疑android版本可能不兼容
而且你们是不准备上架吗？4月底以后必须用ios13 sdk编译了，老版本rn就歇菜了

**Comment by Jhaidi** [comment]
我在
```
"react": "^16.8.6",
"react-native": "0.59.8",
"react-native-update": "^5.5.6",
```
遇到了相同的问题

**Comment by Maochengfag** [comment]
Tanks Sunny Luo




| |
毛成方
|
|
邮箱：maochengfang@126.com
|

签名由 网易邮箱大师 定制

在2020年03月12日 17:35，jhaidi 写道：

我在

"react": "^16.8.6",

"react-native": "0.59.8",

"react-native-update": "^5.5.6",



遇到了相同的问题
