### ISSUE TITLE
升级了react-native-update-cli之后，发布的更新包导致应用闪退

### ISSUE THREAD

**Issue by dompro** [reactnativecn/react-native-pushy#324]
按照往常的操作，执行操作：
`pushy bundle --platform android`
然后出现如下提示：
```
Error: 请升级cli后再尝试( npm i -g react-native-update-cli )
    at /node_modules/react-native-update/local-cli/lib/api.js:8:27
    at Generator.next (<anonymous>)
    at step (/node_modules/react-native-update/local-cli/lib/api.js:76:191)
    at /node_modules/react-native-update/local-cli/lib/api.js:76:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
于是按照提示，进行升级：
`npm i -g react-native-update-cli`
升级成功后，执行：
`pushy bundle --platform android`
像往常一样填写更新信息，然后进行升级测试
APP端也提示了升级，并且也下载成功，重新打开之后就闪退，之后再也打不开。

本次的代码调整非常少，应该不是自身代码引起的闪退，应该是升级了cli之后引起的，这种情况怎么处理？

**Comment by sunnylqm** [comment]
方便提供app我测试下吗

**Comment by dompro** [comment]
给个私人邮箱，可以沟通下配合你这边测试

**Comment by sunnylqm** [comment]
sunnylqm@qq.com  加我qq34731408也可以

**Comment by dompro** [comment]
你好，邮箱和QQ发了之后都没有收到回复

**Comment by sunnylqm** [comment]
没有看到新邮件，垃圾箱也没有，qq也没有收到

**Comment by sunnylqm** [comment]
哦看到邮件了，但是你没有发代码啊，qq没有收到好友请求

**Comment by sunnylqm** [comment]
请确保你上传的apk/ipa不是debug版本
