### ISSUE TITLE
react-native-update-cli 1.0.9版本有bug，请更新到1.1.0

### ISSUE THREAD

**Issue by yuanbolin** [reactnativecn/react-native-pushy#325]
失败原因:no such file or directory
想请教一下这是什么问题导致的

**Comment by sunnylqm** [comment]
可以给个截图吗

**Comment by yuanbolin** [comment]
怎么上传截图

**Comment by yuanbolin** [comment]
完整失败error:"xxx路径"open failed:ENOENT(no such file or directory)

**Comment by sunnylqm** [comment]
直接把图片拖到发言框里

**Comment by yuanbolin** [comment]
![Screenshot_20200318_154634_com xiaofangchezaipad](https://user-images.githubusercontent.com/44077734/76938002-d8828300-6930-11ea-99ad-e041abf46dbd.jpg)

**Comment by yuanbolin** [comment]
![Screenshot_20200318_154634_com xiaofangchezaipad](https://user-images.githubusercontent.com/44077734/76938036-e7693580-6930-11ea-91b3-e62396abe8e7.jpg)

**Comment by yuanbolin** [comment]
![@C D}DV6JR1%7GFV0@XGAYI](https://user-images.githubusercontent.com/44077734/76938396-7bd39800-6931-11ea-9d50-5e0778965b6d.png)

**Comment by sunnylqm** [comment]
嗯，大概知道问题了

**Comment by yuanbolin** [comment]
额,好的.请问具体啥问题呢,是我这边代码问题吗

**Comment by sunnylqm** [comment]
是cli的bug，请更新cli

**Comment by yuanbolin** [comment]
好的 我这就更新试一下
