### ISSUE TITLE
差异更新机制疑问

### ISSUE THREAD

**Issue by yuanbolin** [reactnativecn/react-native-pushy#326]
1.我更改了三行代码，处理了bug。
2.versionCode 由2==>3。
3. versionName "1.1"不变。
上传后并没有提示更新。

**Comment by sunnylqm** [comment]
差异更新仅针对js代码和图片等静态资源，任何原生代码、配置的修改都必须重新发包

**Comment by yuanbolin** [comment]
我十分的确定我改了两行js代码，昨天晚上提交现在依然没有提示。

**Comment by yuanbolin** [comment]
![_AHX@TGGQQEDYVE`M`NF%_H](https://user-images.githubusercontent.com/44077734/77733730-63a2fd80-7042-11ea-8599-70a11de3a97b.png)

**Comment by sunnylqm** [comment]
你是怎么提交的呢

**Comment by yuanbolin** [comment]
pushy bundle --platform android   随后一直Y知道绑定完结束

**Comment by sunnylqm** [comment]
加我qq34731408

**Comment by sunnylqm** [comment]
是因为测试的apk和设备上实际运行的apk不一致
