### ISSUE TITLE
此版本存在但编译时间戳不匹配。请勿以同一版本号重复打包。 

### ISSUE THREAD

**Issue by DirkForDallas** [reactnativecn/react-native-pushy#328]
{
	"packageVersion": "1.3.0",
	"hash": null,
	"buildTime": "26425955"
}

{
	"message": "此版本存在但编译时间戳不匹配。请勿以同一版本号重复打包。"
}

hash值为null

**Comment by sunnylqm** [comment]
表示你安装的包和命令行上传的包不一致
