### ISSUE TITLE
我们正在更换备案主体，主域名update.reactnative.cn暂时访问较慢

### ISSUE THREAD

**Issue by sunnylqm** [reactnativecn/react-native-pushy#330]
我们正在更换备案主体，热更新的主域名 update.reactnative.cn 暂时访问较慢（无法直接解析到国内服务器，只能通过国外服务器中转）
但备用域名 update.react-native.cn 备案已完成， 也正在使用中，可以升级 react-native-update和react-native-update-cli 到最新版本，重新打包上传，重新绑定热更新，以切换到备用域名以提速

我们这段时间正在密集地进行业务的重构迁移等，为的是能提供更稳定的商用服务（现有的免费服务仍然提供）。为大家带来不便，敬请谅解。

**Comment by Maochengfag** [comment]
真的需要商业化 否则生态怎么建立啊

**Comment by Maochengfag** [comment]
https://reactnative.cn/docs/getting-started.html#content 访问404  是在换主体么?

**Comment by sunnylqm** [comment]
是的，备案期间要求停止访问。过渡时期请访问https://www.react-native.cn

**Comment by sunnylqm** [comment]
备案已完成
