### ISSUE TITLE
ios热推完，打开app，检测更新提示错误信息

### ISSUE THREAD

**Issue by wy6754** [reactnativecn/react-native-pushy#331]
![1586238949(1)](https://user-images.githubusercontent.com/34266443/78634963-b9e02e00-78d7-11ea-950d-42b3ab549870.jpg)

**Comment by wy6754** [comment]
请问是什么原因啊

**Comment by sunnylqm** [comment]
请使用真机测试热更新

**Comment by wy6754** [comment]
![image](https://user-images.githubusercontent.com/34266443/78649272-cd978e80-78ef-11ea-9415-88faf8a00d95.png)
![微信图片_20200407165016](https://user-images.githubusercontent.com/34266443/78649344-e1db8b80-78ef-11ea-8706-5c32a4ca0dbd.jpg)
真机测试还是这种情况

**Comment by sunnylqm** [comment]
请提供下各种版本信息， appkey（在update.json里），以及原生包版本号
不方便发这里的话可以加我qq34731408

**Comment by sunnylqm** [comment]
安装的ipa和上传的ipa不一致
