### ISSUE TITLE
什么情况下{expired: true}为true？

### ISSUE THREAD

**Issue by caro-li** [reactnativecn/react-native-pushy#332]

**Comment by sunnylqm** [comment]
原生版本在服务器端不存在（没有上传或删掉了）

**Comment by caro-li** [comment]
删掉这一操作有试过，嫌他太麻烦了；而且如果删掉的话，就再没有办法在这个版本上更新了

**Comment by sunnylqm** [comment]
所以到底是什么需求？

**Comment by caro-li** [comment]
有没有手动去设置这个值，或者在发布的时候设置

**Comment by sunnylqm** [comment]
你可以通过metadata自己实现啊

**Comment by caro-li** [comment]
好像是耶，明明可以操作这个数据，为什么要纠结expired呢！！

谢啦！！

**Comment by caro-li** [comment]
大哥，还有一个需求问题：当前使用的版本号拿不到

**Comment by caro-li** [comment]
不是原生包的版本号

**Comment by sunnylqm** [comment]
当前版本信息还未做记录  将来有空实现  https://github.com/reactnativecn/react-native-pushy/issues/10
