### ISSUE TITLE
上个月 我只是将react-native-pushy升级到5.5.6  操作热更新之后发现真机没有弹出 热更新的提示 

### ISSUE THREAD

**Issue by Maochengfag** [reactnativecn/react-native-pushy#333]
有谁更新后可以完成热更新的同学 可以请教一下
我项目中的信息 
"react-native-update": "^5.5.6",
"react-native": "0.44.0",

我的root目录
import React, { Component } from 'react';

import {
    AppRegistry,
    StyleSheet,
    Platform,
    Text,
    View,
    Alert,
    TouchableOpacity,
    Linking
} from 'react-native';
import {
    isFirstTime,
    isRolledBack,
    packageVersion,
    currentVersion,
    checkUpdate,
    downloadUpdate,
    switchVersion,
    switchVersionLater,
    markSuccess,
  } from 'react-native-update';

import _updateConfig from '../../update.json';
const {appKey} = _updateConfig[Platform.OS];

class update extends Component {

     static checkUpdate(){

        if (isFirstTime) {
            markSuccess()

        }

        checkUpdate(appKey).then(info => {
            
          if (info.expired) {
  
          } else if (info.upToDate) {
  
          } else {

            downloadUpdate(info).then(hash => {

              Alert.alert('提示', '检测到新版本,请点击安装', [

                {text: '安装', onPress: ()=>{switchVersion(hash);}},

              ]);

            }).catch(err => { 
      
            });

          }
        }).catch(err => { 
  
        });
      };

}

module.exports = update

**Comment by sunnylqm** [comment]
印象中5.5.6应该是不支持0.44的吧，最低需要0.46

**Comment by Maochengfag** [comment]
我试试

**Comment by Maochengfag** [comment]
npx react-native init Wallet --version 0.49.5 
新建项目 然后报错 大神sunnylqm  怎么解决啊
<img width="277" alt="image" src="https://user-images.githubusercontent.com/5634505/79334928-bd1c8f00-7f53-11ea-96b5-1f3921908f4b.png">

**Comment by sunnylqm** [comment]
1、不要在任何地方使用中文
2、为什么还要用这么老的版本

**Comment by Maochengfag** [comment]
已经更新到5.0以上 但是报错了




| |
毛成方
|
|
邮箱：maochengfang@126.com
|

签名由 网易邮箱大师 定制

在2020年04月15日 20:52，Sunny Luo 写道：

1、不要在任何地方使用中文
2、为什么还要用这么老的版本

**Comment by sunnylqm** [comment]
报什么错给个截图
