### ISSUE TITLE
Demo testHotUpdate 运行报错 怎么解决啊

### ISSUE THREAD

**Issue by Maochengfag** [reactnativecn/react-native-pushy#336]
@sunnylqm 
<img width="309" alt="image" src="https://user-images.githubusercontent.com/5634505/81162117-3e010080-8fbf-11ea-8fcf-5e30eb8a98a5.png">

**Comment by sunnylqm** [comment]
https://reactnativecn.github.io/react-native-pushy/#/guide?id=%e7%99%bb%e5%bd%95%e4%b8%8e%e5%88%9b%e5%bb%ba%e5%ba%94%e7%94%a8
