### ISSUE TITLE
热更新 平台无法应用删除

### ISSUE THREAD

**Issue by Maochengfag** [reactnativecn/react-native-pushy#338]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/5634505/81245767-713ba200-9048-11ea-8e69-cda26e12ebaa.png">

**Comment by sunnylqm** [comment]
需要先删除所有已有的原生包和热更包

**Comment by Maochengfag** [comment]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/5634505/81246647-b9f45a80-904a-11ea-8eda-1a79c85d3f04.png">
热更新的包我删除了 原始包怎么删除

**Comment by sunnylqm** [comment]
拖动一下可以看到删除按钮
这个界面我们也正在重做中

**Comment by Maochengfag** [comment]
<img width="247" alt="image" src="https://user-images.githubusercontent.com/5634505/81246818-22dbd280-904b-11ea-97bb-52c6a3187558.png">
多谢
