### ISSUE TITLE
屏蔽ios的操作哪去啦,找不到了

### ISSUE THREAD

**Issue by yuanbolin** [reactnativecn/react-native-pushy#340]

**Comment by yuanbolin** [comment]
我记得之前在文档找得到的,但是现在找不到了

**Comment by yuanbolin** [comment]
求助啊

**Comment by sunnylqm** [comment]
https://reactnativecn.github.io/react-native-pushy/#/

目前版本接到的反馈是可以顺利过审，你是被拒了吗？

**Comment by yuanbolin** [comment]
不是的,年初有个项目rn:0.61.5 update:5.5.6被拒绝了我来看过禁用的,昨天刚接手个rn版本0.55.4  update版本5.1.3的担心这问题,习惯性来看看了.

**Comment by yuanbolin** [comment]
update更新到最新的话会报错

**Comment by sunnylqm** [comment]
5.1.3不能按文档步骤屏蔽，把手动link的部分删掉即可
