### ISSUE TITLE
IOS更新提示app.json找不到

### ISSUE THREAD

**Issue by kq2011** [reactnativecn/react-native-pushy#341]
热更新安卓端没问题。苹果端频繁提示app.json找不到，导致热更新在ios上没法使用。公司两部苹果机，每次热更新ios包，必有一台苹果手机正常，那么另外一台苹果手机就报app.json，看以前的lssues也有人说到这个问题，希望解决下。谢谢！

**Comment by sunnylqm** [comment]
请联系我qq34731408

**Comment by sunnylqm** [comment]
应该在5.6.0版本中已修复
