### ISSUE TITLE
请问免费的热更新包体积调小了吗

### ISSUE THREAD

**Issue by yuanbolin** [reactnativecn/react-native-pushy#345]
请问免费的热更新包体积调小了吗,之前4M的行,现在突然是提示3M了

**Comment by yuanbolin** [comment]
我想缩小ppk体积的话,将静态图片资源放入服务器是否可行

**Comment by jingzhiwei0314** [comment]
https://pushy.reactnative.cn/pricing.html
收费标准

**Comment by yuanbolin** [comment]
react-native-update": "^5.1.3",请问热更新完后app闪退是什么原因

**Comment by yuanbolin** [comment]
低包和更新包都是1.0 原生的也没动过

**Comment by yuanbolin** [comment]
压缩和删除了图片资源会导致热更新后闪退吗

**Comment by sunnylqm** [comment]
老版本没有做编译时间校验，必须由用户自己保证apk包完全一致（设备上运行的和uploadApk是同一个文件），否则更新时由于差异包不一致会导致闪退。新版本会做校验，不一致时会提示编译时间戳不一致。
