### ISSUE TITLE
pushy login时pushy无法识别

### ISSUE THREAD

**Issue by youngster-yj** [reactnativecn/react-native-pushy#348]
pushy : 无法将“pushy”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ pushy login
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (pushy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by youngster-yj** [comment]
已解决，由于yarn与cnpm混合使用导致问题出现

**Comment by HongHongPa** [comment]
请问事怎么解决的？

**Comment by HongHongPa** [comment]
>pushy login
Are you at home directory of a react-native project?
`pushy install` is under development, please run `npm install react-native-update` to install pushy manually.

已安装react-native-update，请问怎么解决？

**Comment by sunnylqm** [comment]
可以贴个完整点的截图吗

**Comment by qq2339300630** [comment]
感觉对新手不太友好

**Comment by sunnylqm** [comment]
先关了，后续有问题再开
