### ISSUE TITLE
同一个原生包的第二个热更新包无法检测到

### ISSUE THREAD

**Issue by zjz1993** [reactnativecn/react-native-pushy#349]
同样一个原生包，第一个热更新包能检测到并且成功安装，但是我发布了第二个热更新包后，在手机上检测更新时，始终提示我当前版本已经是最新，即第二个热更新包无法检测到，是我姿势不对么？

**Comment by sunnylqm** [comment]
请加我qq 34731408

**Comment by sunnylqm** [comment]
热更新生成有一定延时（几秒到十几分钟），请先等候一段时间。如超过半个小时仍检测不到更新，请再联系我。
