### ISSUE TITLE
xcode8 编译出来的app在ios 8下闪退

### ISSUE THREAD

**Issue by a289459798** [reactnativecn/react-native-pushy#35]
xcode8 编译出来的app在ios 8下闪退，具体报错代码是

`[session downloadTaskWithURL:url];`

在执行下载热更新的时候。

**Comment by tdzl2003** [comment]
这是因为本工程的iOS Deployment Target设的太高了。对于0.29以上版本的rn工程，可以更新本组件到3.0.2版本再试。对于之前版本的rn工程，可以手动修改此target
