### ISSUE TITLE
RCTPushy.h file not found

### ISSUE THREAD

**Issue by bbx429** [reactnativecn/react-native-pushy#350]
已根据官方文档操作
RN < 0.60且不使用CocoaPods
在XCode中的Project Navigator里,右键点击Libraries ➜ Add Files to [你的工程名]
进入node_modules ➜ react-native-update ➜ ios 并选中RCTPushy.xcodeproj`
在XCode中的project navigator里,选中你的工程,在 Build Phases ➜ Link Binary With Libraries 中添加 libRCTPushy.a、libz.tbd、libbz2.1.0.tbd
继续在Build Settings里搜索Header Search Path，添加$(SRCROOT)/../node_modules/react-native-update/ios
在Build Phases添加一个New Run Script Phase运行脚本，内容如下

#!/bin/bash
set -x
DEST="../node_modules/react-native-update/ios/"
date +%s > "$DEST/pushy_build_time.txt"
编译的时候就会在../node_modules/react-native-update/ios/文件夹下面生成一个pushy_build_time.txt文件。 然后在Copy Bundle Resources里把生成的pushy_build_time.txt文件添加进去。

重新编译

在AppDelegate.m里面
#import "RCTPushy.h"

**Comment by sunnylqm** [comment]
Header search path那里勾选recursive

**Comment by bbx429** [comment]
Xcode: 11.3.1
react-native: 0.55.4
react-native-update: 5.0.0

**Comment by bbx429** [comment]
> 标题搜索路径那里拖动递归

谢谢！
