### ISSUE TITLE
未找到index.bundlejs文件

### ISSUE THREAD

**Issue by lx495707690** [reactnativecn/react-native-pushy#351]
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.yunyouwenhua.yywz/files/_update/_ql6y-ZrPUPkLdta30frpD3MDGsf/index.bundlejs: No such file or directory

目前这个问题不是所有android用户都遇到， 只捕捉到个别用户的异常。

"react-native": "0.61.5",

"react-native-update": "^5.5.9"

**Comment by sunnylqm** [comment]
加我qq34731408

**Comment by sunnylqm** [comment]
请尝试最新版本看是否还有此情况
