### ISSUE TITLE
请问每次更新都要上传ipa包吗，

### ISSUE THREAD

**Issue by wangzidaren** [reactnativecn/react-native-pushy#352]
提示此版本存在但编译时间戳不匹配，请勿以同一版本号重复打包

**Comment by sunnylqm** [comment]
如果有archive发生，则需要导出上传

**Comment by wangzidaren** [comment]
> 如果有archive发生，则需要导出上传。如果只是修改js或者图片，那么只需要pushy bundle，不应该archive

就算只是修改js，也要重新修改版本号，不然就提示  此版本存在但编译时间戳不匹配，请勿以同一版本号重复打包

**Comment by sunnylqm** [comment]
为什么要修改版本号呢，直接pushy bundle就可以了啊

**Comment by wangzidaren** [comment]
> > 如果有archive发生，则需要导出上传。如果只是修改js或者图片，那么只需要pushy bundle，不应该archive
> 
> 就算只是修改js，也要重新修改版本号，不然就提示 此版本存在但编译时间戳不匹配，请勿以同一版本号重复打包

第一次我上传ipa包，然后我修改了js代码，pushy bundle，就提示此版本存在但编译时间戳不匹配，请勿以同一版本号重复打包

**Comment by sunnylqm** [comment]
此版本存在但编译时间戳不匹配，请勿以同一版本号 —— 意味着你至少做过两次archive

**Comment by wangzidaren** [comment]
![image](https://user-images.githubusercontent.com/10472220/88624947-786bcc80-d0da-11ea-88b1-1ca74fd654de.png)
我是按照官方流程来的，第一次打包生成ipa上传，然后修改一点js代码，pushy bundle，就提示请勿以同一版本号重复打包

**Comment by sunnylqm** [comment]
加我qq 34731408

**Comment by wangzidaren** [comment]
> 34731408

可以了，原来是我直接手机上调试的，如果用生成的包安装就正常了，感谢

**Comment by wangzidaren** [comment]
已解决
