### ISSUE TITLE
[25日凌晨已恢复]服务器流量异常

### ISSUE THREAD

**Issue by sunnylqm** [reactnativecn/react-native-pushy#355]

**Comment by HeMa321** [comment]
还没好 吗?

**Comment by DirkForDallas** [comment]
还没好？

**Comment by sunnylqm** [comment]
现在应该恢复正常了，各位查看下
抱歉今天突然遭遇了超大流量DDos

**Comment by hht** [comment]
上传更新包一直提示request to https://update.react-native.cn/api/upload....failed SSL alert number 80

**Comment by sunnylqm** [comment]
@hht
试下更新cli到1.1.15
