### ISSUE TITLE
修改apk文件，热更新失败

### ISSUE THREAD

**Issue by wangzidaren** [reactnativecn/react-native-pushy#356]
打包出来的apk文件，转换成数据流，然后在数据流末尾增加一段数据，生成apk，就是多渠道包，就无法热更新了

**Comment by sunnylqm** [comment]
具体是如何生成多渠道包的？

**Comment by wangzidaren** [comment]
> 具体是如何生成多渠道包的？
![2020-08-31 17 08 52](https://user-images.githubusercontent.com/10472220/91703416-b9a93d80-ebac-11ea-9be6-bf06effb266f.jpg)
在APK文件的注释字段，添加渠道信息。

整个方案包括以下几步：

复制APK
找到EOCD数据块
修改注释长度
添加渠道信息
添加渠道信息长度
添加魔数

**Comment by sunnylqm** [comment]
无法热更新有具体的报错吗

**Comment by wangzidaren** [comment]
> 无法热更新有具体的报错吗
就提示热更新失败

**Comment by sunnylqm** [comment]
建议想办法把error.message打出来，或者截取logcat日志贴出来

**Comment by wangzidaren** [comment]
> 建议想办法把error.message打出来，或者截取日志贴出来
有时候经常更新失败，提示timeout

**Comment by wangzidaren** [comment]
> 建议想办法把error.message打出来，或者截取日志贴出来

更新几次中，总会有一两次更新失败，提示超时

**Comment by sunnylqm** [comment]
就是能更新，但是偶然超时是吗？rn和update的版本多少？

**Comment by wangzidaren** [comment]
> 就是能更新，但是偶然超时是吗？rn和update的版本多少？
Bundling with react-native:  0.61.5
react-native-update-cli: 1.1.13
react-native-update: 5.7.0

**Comment by wangzidaren** [comment]
> 就是能更新，但是偶然超时是吗？rn和update的版本多少？
可以更新，但就是会有一两次更新超时，有时候是秒更新完，有的时候需要更新1点多M，明明只修改了一两句js代码

**Comment by sunnylqm** [comment]
建议更新到最新版本再观察看下
如果还有问题加我qq34731408

**Comment by wangzidaren** [comment]
> 建议更新到最新版本再观察看下
> 如果还有问题加我qq34731408

更新什么到最新版本

**Comment by sunnylqm** [comment]
react-native-update目前最新是5.7.2

**Comment by sunnylqm** [comment]
先关了，后续有问题再开
