### ISSUE TITLE
React/RCTReloadCommand.h' file not found

### ISSUE THREAD

**Issue by KingChow1981** [reactnativecn/react-native-pushy#357]
打包时出错
/projectSource/nfrzzlApp/node_modules/react-native-update/ios/RCTPushy/RCTPushy.m:16:9: fatal error: 'React/RCTReloadCommand.h' file not found
#import <React/RCTReloadCommand.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by sunnylqm** [comment]
rn什么版本

**Comment by sunnylqm** [comment]
试下新的5.8.1版本
