### ISSUE TITLE
热更包文件过大

### ISSUE THREAD

**Issue by lzk19961028** [reactnativecn/react-native-pushy#358]
我只是改动了一小部分js文件，为什么热更包却很大，有20多M，这个热更包的大小和什么有关？

**Comment by sunnylqm** [comment]
你说的热更包是指ppk文件还是diff文件
ppk文件是所有代码和资源文件的打包，大是正常的
服务器端会对ppk文件进行对比生成diff文件供用户下载更新，diff文件一般会非常小。如果diff文件也很大，请检查[是否禁用了android的一个编译选项](https://pushy.reactnative.cn/docs/getting-started#%E7%A6%81%E7%94%A8-android-%E7%9A%84-crunch-%E4%BC%98%E5%8C%96)

**Comment by lzk19961028** [comment]
谢谢你的回复，所以diff文件有什么作用吗，我指的就是用来发布的那个文件，应该是ppk吧，太大了就被限制不能上传了。那如果我把资源文件用url形式传入是不是就会小很多


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Sunny Luo <notifications@github.com&gt;
发送时间: 2020年11月2日 11:57
收件人: reactnativecn/react-native-pushy <react-native-pushy@noreply.github.com&gt;
抄送: lzk19961028 <295076503@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[reactnativecn/react-native-pushy] 热更包文件过大 (#358)





 
你说的热更包是指ppk文件还是diff文件
 ppk文件是所有代码和资源文件的打包，大是正常的
 服务器端会对ppk文件进行对比生成diff文件供用户下载更新，diff文件一般会非常小。如果diff文件也很大，请检查是否禁用了android的一个编译选项

**Comment by sunnylqm** [comment]
diff文件就是用户实际下载的补丁包
资源文件用远程url确实可以减小大小，但是图片就需要网络加载了

**Comment by PDxixiangkeren** [comment]
> 你说的热更包是指ppk文件还是diff文件 ppk文件是所有代码和资源文件的打包，大是正常的 服务器端会对ppk文件进行对比生成diff文件供用户下载更新，diff文件一般会非常小。如果diff文件也很大，请检查[是否禁用了android的一个编译选项](https://pushy.reactnative.cn/docs/getting-started.html#%E7%A6%81%E7%94%A8android%E7%9A%84crunch%E4%BC%98%E5%8C%96)

ppk包11M，更新diff包9M，是个是不是很明显有问题，是需要设置这个crunchPngs false就可以了吗

**Comment by sunnylqm** [comment]
首先是要禁用 crunchPngs，否则每次热更图片都会重新分发（因为原生打包图片经过了压缩而热更打包没有，所以图片比对始终对不上）
其次是尽量更新到最新版本（不过需要走原生更新），最新版本对 hermes 的 diff 有针对性优化

如果还有疑问可加 qq 34731408 联调

**Comment by sunnylqm** [comment]
正常情况如果图片没有变动，那么 diff 包中解包（可以下载下来直接改后缀为 zip 解包查看）就不会看到有图片

**Comment by PDxixiangkeren** [comment]
> 首先是要禁用 crunchPngs，否则每次热更图片都会重新分发（因为原生打包图片经过了压缩而热更打包没有，所以图片比对始终对不上） 其次是尽量更新到最新版本（不过需要走原生更新），最新版本对 hermes 的 diff 有针对性优化
> 
> 如果还有疑问可加 qq 34731408 联调

好的，谢谢
