### ISSUE TITLE
pushy login 无法识别

### ISSUE THREAD

**Issue by Staryixing** [reactnativecn/react-native-pushy#359]
全局安装了 npm i -g react-native-update-cli 但是在项目下输入pushy login 报错：  pushy : 无法将“pushy”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼
写，如果包括路径，请确保路径正确，然后再试一次

**Comment by sunnylqm** [comment]
重装node试下，记得勾选add to path

**Comment by Staryixing** [comment]
好的  我在系统环境变量中配置增加了一个path 可以了
