### ISSUE TITLE
React Native 0.34版本 Android 编译失败

### ISSUE THREAD

**Issue by pamler** [reactnativecn/react-native-pushy#36]
错误如下，cn/reactnative/modules/update/UpdateModule.java

128行：
`JSBundleLoader loader = JSBundleLoader.createFileLoader(application, UpdateContext.getBundleUrl(application));`

0.34版本中，JSBundleLoader的createFileLoader方法只接受一个参数，而不是两个，编译报错。

**Comment by macxie** [comment]
我长级到0.34都这样的问题

**Comment by pamler** [comment]
我暂时把第一个参数自己手动删掉了，还未测试热更新功能是否还正常

**Comment by Darkhorse-Fraternity** [comment]
我用了楼上的方法，希望可以快点修复呀。

**Comment by Rambos** [comment]
+1
这么多天了，都没回应！

**Comment by jinghun1999** [comment]
我也遇到同样的错误呢

**Comment by ForteenC** [comment]
0.35版本也没有修复这个，今天试了一下热更新功能，到这里就编译不通过了，删掉第一个参数也不行，导致热更新功能没有办法使用，希望快点修复吧

**Comment by sunnylqm** [comment]
删掉第一个参数应该是可以的。如果还有问题，请贴出错误截图。

**Comment by sunnylqm** [comment]
已修复 https://github.com/reactnativecn/react-native-pushy/commit/05b98b10bf721200598b27caf03c0be158cca757
