### ISSUE TITLE
与"react-native": "0.63.3"不兼容问题。

### ISSUE THREAD

**Issue by delphp** [reactnativecn/react-native-pushy#362]
依赖
  "dependencies": {
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-update": "^5.9.3"
  },

出问题了
E:\dianShang\ReactNative>react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 975 file(s) to forward-jetify. Using 2 workers...
info JS server already running.
info Installing the app...

> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
10 actionable tasks: 1 executed, 9 up-to-date
有遇到这种情况的吗，如何解决

**Comment by sunnylqm** [comment]
```
cd android && ./gradlew installDebug --debug
```
看下

**Comment by sunnylqm** [comment]
如有更多信息提供，请重开此issue
