### ISSUE TITLE
按照RN中文网写的demo，iOS热更新成功后重启app，app回滚了，判断 isFirstTime 好像并没有效果（没有进入判断内）

### ISSUE THREAD

**Issue by DiamoandDog** [reactnativecn/react-native-pushy#363]
componentDidMount() {
    if (isFirstTime) {
      // 必须调用此更新成功标记方法
      // 否则默认更新失败，下一次启动会自动回滚
      markSuccess();
      console.log('更新完成');
    } else if (isRolledBack) {
      console.log('刚刚更新失败了,版本被回滚.');
    }
  }

如上代码，更新完重启，isFirstTime判断没有进入

**Comment by sunnylqm** [comment]
看下bundle url的配置

**Comment by DiamoandDog** [comment]
![截屏2020-12-07 下午4 49 32](https://user-images.githubusercontent.com/14171367/101329363-46e6e700-38ac-11eb-91ba-1ebd5dc656b0.png)
这是appdelegate中的，另外我是从原生页面跳转rn页面，跳转的代码如下：
![截屏2020-12-07 下午4 52 21](https://user-images.githubusercontent.com/14171367/101329652-9decbc00-38ac-11eb-82a3-8f2bd96800de.png)

**Comment by sunnylqm** [comment]
37行那里的jsCodeLocation并没有热更新介入啊，当然重启就回滚了

**Comment by DiamoandDog** [comment]
> 第二个截图37行那里的jsCodeLocation并没有热更新介入啊，当然重启就回滚了

谢谢！
