### ISSUE TITLE
错误: 程序包android.support.v4.content不存在 import android.support.v4.content.FileProvider;

### ISSUE THREAD

**Issue by windsleaver** [reactnativecn/react-native-pushy#366]
参照文档运行了
# 全局安装命令行工具，每台电脑只用装一次
npm i -g react-native-update-cli

# 在项目中安装热更新模块
npm i react-native-update
后运行安卓项目出现报错
错误: 程序包android.support.v4.content不存在
import android.support.v4.content.FileProvider;
请问有哪位知道如何解决！

**Comment by windsleaver** [comment]
"react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-update": "^5.10.0"

**Comment by sunnylqm** [comment]
https://pushy.reactnative.cn/docs/faq.html#android-%E7%BC%96%E8%AF%91%E6%8A%A5%E9%94%99-%E9%94%99%E8%AF%AF%EF%BC%9A%E7%A8%8B%E5%BA%8F%E5%8C%85-androidsupportv4content-%E4%B8%8D%E5%AD%98%E5%9C%A8



---Original---
