### ISSUE TITLE
请先禁用android的crunchPngs优化，以配置过

### ISSUE THREAD

**Issue by windsleaver** [reactnativecn/react-native-pushy#367]
buildTypes {
            debug {
                signingConfig signingConfigs.debug
                crunchPngs false
            }
            release {
                // Caution! In production, you need to generate your own keystore file.
                // see https://facebook.github.io/react-native/docs/signed-apk-android.
                signingConfig signingConfigs.debug
                minifyEnabled enableProguardInReleaseBuilds
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
                // 添加下面这行以禁用crunch
                crunchPngs false

**Comment by sunnylqm** [comment]
请加我qq34731408
