### ISSUE TITLE
jenkins集成publish交互式命令行

### ISSUE THREAD

**Issue by canghai908** [reactnativecn/react-native-pushy#369]
jenkins集成pushy publish需要进行手动交互，能否提供环境变量或者配置文件加载方式？
![image](https://user-images.githubusercontent.com/1450994/114122998-006dcb80-9924-11eb-8a95-d1541ea17bf3.png)

**Comment by sunnylqm** [comment]
参考下这个  https://github.com/reactnativecn/react-native-pushy/issues/243

**Comment by canghai908** [comment]
多谢，多谢。
