### ISSUE TITLE
Android 编译时间获取错误

### ISSUE THREAD

**Issue by kangfenmao** [reactnativecn/react-native-pushy#373]
![image](https://user-images.githubusercontent.com/8253512/118595154-26b53f80-b7dd-11eb-916c-6aade06bb698.png)

ReactNativeJS: '更新检查失败', [Error: 热更新已暂停，原因：buildTime mismatch。请在"May 19, 2021 1:07:13 AM"之后重试。]

**Comment by kangfenmao** [comment]
这个时间戳有问题

**Comment by sunnylqm** [comment]
https://pushy.reactnative.cn/docs/faq.html#%E7%83%AD%E6%9B%B4%E6%96%B0%E6%8A%A5%E9%94%99%EF%BC%9A%E7%83%AD%E6%9B%B4%E6%96%B0%E5%B7%B2%E6%9A%82%E5%81%9C%EF%BC%8C%E5%8E%9F%E5%9B%A0%EF%BC%9Abuildtime-mismatch%E3%80%82

**Comment by kangfenmao** [comment]
> https://pushy.reactnative.cn/docs/faq.html#%E7%83%AD%E6%9B%B4%E6%96%B0%E6%8A%A5%E9%94%99%EF%BC%9A%E7%83%AD%E6%9B%B4%E6%96%B0%E5%B7%B2%E6%9A%82%E5%81%9C%EF%BC%8C%E5%8E%9F%E5%9B%A0%EF%BC%9Abuildtime-mismatch%E3%80%82

问题在于这个时间是个未来的时间

**Comment by sunnylqm** [comment]
没听懂什么未来的时间？

**Comment by kangfenmao** [comment]
不确定哪一步出错了，我重新上传一遍后成功了，暂时先关闭 issue
