### ISSUE TITLE
热更新包publish后，app第一次打开检测不到

### ISSUE THREAD

**Issue by DuanHejin** [reactnativecn/react-native-pushy#374]
**前提：**
- 按照官网实例集成pushy
https://pushy.reactnative.cn/docs/integration.html#%E5%AE%8C%E6%95%B4%E7%9A%84%E7%A4%BA%E4%BE%8B
- android手机安装的app buildTime 和pushy上硬版本的buildTime一致；
- 项目目录执行`pushy bundle --platform android`，成功publish到pushy服务器，并且bind此次publish为最新版；

 
**版本信息：**
"react-native": "0.63.4",
"react-native-update": "^6.0.2",
"react-native-update-cli": "1.4.1",

**现象：**
成功publish热更新内容到pushy，并且bind本次publish为最新版之后（pushy控制台可见），

1.打开APP，在componentDidMount中调用checkUpdate()，无法检测到有热更新。response为
```
{
   "upToDate": true,
   "ok": 1
}
```
预期是
```
{
    "update": true,
    "hash": "xxxxxxxxxxx",
    "name": "v1.0.10",
    "description": "",
    "metaInfo": "",
    "pdiffUrl": "https://dl.react-native.cn/xxxx-yyyy.phdiff",
    "diffUrl": "https://dl.react-native.cn/xxxx-yyyy-2y-zzzz.hdiff",
    "ok": 1
}
```

2.依旧是step1的打开状态，延迟5s再次调用checkUpdate()依旧检测不到热更新；
3.将APP杀死，再次打开，即可检测到有热更新内容（step3与step1的req 请求体参数相同）；
4.或者不杀死APP，而是将APP放置background，再次唤起，利用`AppState.addEventListener('change', this.appStateChange);`在appStateChange方法里调用checkUpdate()，亦可检测到热更新内容（step4与step1的req 请求体参数相同）
5.只有新publish的热更新内容存在以上问题，在已发布的热更新包之间切换bind，APP首次打开即能检测到热更新

以上

**Comment by sunnylqm** [comment]
你好，请加我qq34731408具体看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月31日(周一) 晚上8:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-pushy] 热更新包publish后，app第一次打开检测不到 (#374)




 
前提：
  
按照官网实例集成pushy
 https://pushy.reactnative.cn/docs/integration.html#%E5%AE%8C%E6%95%B4%E7%9A%84%E7%A4%BA%E4%BE%8B 

android手机安装的app buildTime 和pushy上硬版本的buildTime一致； 

项目目录执行pushy bundle --platform android，成功publish到pushy服务器，并且bind此次publish为最新版； 
 
版本信息：
 "react-native": "0.63.4",
 "react-native-update": "^6.0.2",
 "react-native-update-cli": "1.4.1",
 
现象：
 成功publish热更新内容到pushy，并且bind本次publish为最新版之后（pushy控制台可见），
 
1.打开APP，在componentDidMount中调用checkUpdate()，无法检测到有热更新。response为
 {    "upToDate": true,    "ok": 1 }  
预期是
 {     "update": true,     "hash": "xxxxxxxxxxx",     "name": "v1.0.10",     "description": "",     "metaInfo": "",     "pdiffUrl": "https://dl.react-native.cn/xxxx-yyyy.phdiff",     "diffUrl": "https://dl.react-native.cn/xxxx-yyyy-2y-zzzz.hdiff",     "ok": 1 }  
2.依旧是step1的打开状态，延迟5s再次调用checkUpdate()依旧检测不到热更新；
 3.将APP杀死，再次打开，即可检测到有热更新内容（step3与step1的req 请求体参数相同）；
 4.或者不杀死APP，而是将APP放置background，再次唤起，利用AppState.addEventListener('change', this.appStateChange);在appStateChange方法里调用checkUpdate()，亦可检测到热更新内容（step4与step1的req 请求体参数相同）
 5.只有新publish的热更新内容存在以上问题，在已发布的热更新包之间切换bind，APP首次打开即能检测到热更新
 
以上

**Comment by sunnylqm** [comment]
感谢反馈。已在服务器端修复
