### ISSUE TITLE
pushy uploadApk Error

### ISSUE THREAD

**Issue by waima004** [reactnativecn/react-native-pushy#376]
![微信图片_20210615171824](https://user-images.githubusercontent.com/20202661/122027488-bb6f8500-cdfd-11eb-8834-46d1540b8f87.png)

**Comment by sunnylqm** [comment]
是否有多个pushy账号？

**Comment by waima004** [comment]
> 是否有多个pushy账号？

感谢回复  这个问题已经解决了。应该是当时添加了两个一模一样的  都删掉 重新创建一个新的就可以了。
![微信图片_20210616133512](https://user-images.githubusercontent.com/20202661/122163404-bb2bc400-cea7-11eb-92e1-42fe966d013b.png)
