### ISSUE TITLE
\node_modules\react-native-update\android\src\main\java\cn\reactnative\modules\update\UpdateModule.java:29:

### ISSUE THREAD

**Issue by SoftwareMark** [reactnativecn/react-native-pushy#378]
node_modules\react-native-update\android\src\main\java\cn\reactnative\modules\update\UpdateModule.java:29: 错误: 程序包android.support.v4.content不存在

**Comment by sunnylqm** [comment]
常见问题里有说明


请运行
npx jetify



---Original---
From: "Small ***@***.***&gt;
Date: Tue, Jul 20, 2021 12:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [reactnativecn/react-native-pushy] \node_modules\react-native-update\android\src\main\java\cn\reactnative\modules\update\UpdateModule.java:29: (#378)




 
node_modules\react-native-update\android\src\main\java\cn\reactnative\modules\update\UpdateModule.java:29: 错误: 程序包android.support.v4.content不存在
