### ISSUE TITLE
Entry is not named

### ISSUE THREAD

**Issue by hsvsll** [reactnativecn/react-native-pushy#379]
请问出现这种情况是什么问题，如图：
![1628824166625](https://user-images.githubusercontent.com/8968885/129300316-d582f40b-1050-49de-ae4e-ad9987a4791f.jpg)

**Comment by sunnylqm** [comment]
请重新发图，看不到

**Comment by sunnylqm** [comment]
是否是android 7以下版本？

**Comment by sunnylqm** [comment]
方便的话加下我qq 34731408

**Comment by sunnylqm** [comment]
请升级到 6.2.0-beta0 版本了打包再试试
