### ISSUE TITLE
ios正式版本上架后，发布热更新，提示更新成功，但是点重启就闪退

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [reactnativecn/react-native-pushy#381]
ios正式版本上架后，发布热更新，提示更新成功，但是点重启就闪退，并且版本也回退

**Comment by sunnylqm** [comment]
说明更新的版本有错误，导致无法正常启动



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月4日(周六) 上午9:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-pushy] ios正式版本上架后，发布热更新，提示更新成功，但是点重启就闪退 (#381)




 
ios正式版本上架后，发布热更新，提示更新成功，但是点重启就闪退，并且版本也回退
