### ISSUE TITLE
安卓热更新成功后再次推出app，再次打开时又回到了第一版

### ISSUE THREAD

**Issue by zhangxiaochunxy** [reactnativecn/react-native-pushy#383]
安卓app，热更新成功后，杀掉进程，再次打开时又回到了第一版

**Comment by zhangxiaochunxy** [comment]
是我自己没有好好看文档，更新成功后需要标记一下。否则会会退到最初的版本。如下
`if (isFirstTime) {
      markSuccess()
    }`

**Comment by sunnylqm** [comment]
这里提到的两种情况可以排除吗？


https://pushy.reactnative.cn/docs/faq.html#%E7%83%AD%E6%9B%B4%E6%96%B0%E6%88%90%E5%8A%9F%E5%AE%8C%E6%88%90%EF%BC%8C%E4%BD%86%E6%98%AF%E9%87%8D%E5%90%AF%E5%90%8E%E5%8F%88%E5%9B%9E%E6%BB%9A%E4%BA%86%E6%98%AF%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B%EF%BC%9F


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月22日(周三) 中午12:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-pushy] 安卓热更新成功后再次推出app，再次打开时又回到了第一版 (#383)




 
安卓app，热更新成功后，杀掉进程，再次打开时又回到了第一版
