### ISSUE TITLE
购买了之后发票在哪开？

### ISSUE THREAD

**Issue by corei7qxx** [reactnativecn/react-native-pushy#384]
在官网上找了半天没看到开发票的地方？

**Comment by sunnylqm** [comment]
https://pushy.reactnative.cn/docs/faq.html#%E5%A6%82%E4%BD%95%E5%BC%80%E5%85%B7%E5%8F%91%E7%A5%A8%EF%BC%9F



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月27日(周一) 下午2:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-pushy] 购买了之后发票在哪开？ (#384)




 
在官网上找了半天没看到开发票的地方？
