### ISSUE TITLE
热更新在编译打包出现程序包android.support.v4.content不存在

### ISSUE THREAD

**Issue by Jack-QMY** [reactnativecn/react-native-pushy#385]
![image](https://user-images.githubusercontent.com/57746139/134867278-0f4dd5c9-9e70-4a16-ac4c-1c8a27b6e682.png)

**Comment by sunnylqm** [comment]
https://pushy.reactnative.cn/docs/faq.html#android-%E7%BC%96%E8%AF%91%E6%8A%A5%E9%94%99-%E9%94%99%E8%AF%AF%EF%BC%9A%E7%A8%8B%E5%BA%8F%E5%8C%85-androidsupportv4content-%E4%B8%8D%E5%AD%98%E5%9C%A8



---原始邮件---
发件人: "Jack ***@***.***&gt;
发送时间: 2021年9月27日(周一) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-pushy] 热更新在编译打包出现程序包android.support.v4.content不存在 (#385)
