### ISSUE TITLE
metaInfo 键值类型都必须是字符串类型？

### ISSUE THREAD

**Issue by yyyyq** [reactnativecn/react-native-pushy#386]
![截屏2021-11-08 下午4 04 14](https://user-images.githubusercontent.com/44601473/140706148-67503bb0-83f9-48f4-b752-669fbd19a78e.png)

**Comment by sunnylqm** [comment]
我们对metaInfo没有任何处理和限制

**Comment by sunnylqm** [comment]
建议在录入metaInfo前做一个json校验，parse时候也加个try catch
