### ISSUE TITLE
switchVersionLater ios 重启后无效,switchVersion 重启后又回到原来的版本---急

### ISSUE THREAD

**Issue by kelley-hub** [reactnativecn/react-native-pushy#389]
xcode 13.2
rn 0.64
rn-update 6.4.0

**Comment by sunnylqm** [comment]
请先升级react-native-update到最新版本后再试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月28日(周二) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reactnativecn/react-native-pushy] switchVersionLater ios 重启后无效---急 (Issue #389)




 
xcode 13.2
 rn 0.64
 rn-update 6.4.0

**Comment by sunnylqm** [comment]
自建服务的兼容问题
