### ISSUE TITLE
请问报错咋解决

### ISSUE THREAD

**Issue by hhb19900618** [reactnativecn/react-native-pushy#39]
ios 执行命令  老报错咋办
npm ERR! Error: EACCES: permission denied, open '/Users/huabinhu/.npm/_locks/staging-5dedf5e59c012c8f.lock'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, open '/Users/huabinhu/.npm/_locks/staging-5dedf5e59c012c8f.lock'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/Users/huabinhu/.npm/_locks/staging-5dedf5e59c012c8f.lock' }

**Comment by sunnylqm** [comment]
sudo rm -rf ~/.npm/_locks

**Comment by hhb19900618** [comment]
你好  我加上这句后 执行  npm install -g react-native-cli
也报错呢

**Comment by sunnylqm** [comment]
报什么错

**Comment by hhb19900618** [comment]
你好 已解决 npm install -g react-native-cli前面加个 sudo ok了

**Comment by sunnylqm** [comment]
加sudo不能解决根本问题，会带来后续一系列副作用

**Comment by hhb19900618** [comment]
那应该咋办呀

**Comment by sunnylqm** [comment]
如果是/usr/local目录权限问题，修复权限 
sudo chown -R `whoami` /usr/local

**Comment by hhb19900618** [comment]
我记得这个命令有执行过 没什么卵用呀

**Comment by tdzl2003** [comment]
试试这个：
```bash
sudo chown -R huabinhu /Users/huabinhu/.npm
```
