### ISSUE TITLE
Error: 找不到bundle文件。请确保此apk为release版本，且bundle文件名为默认的index.android.bundle

### ISSUE THREAD

**Issue by catericy** [reactnativecn/react-native-pushy#393]
```
sudo pushy uploadApk android/app/build/outputs/apk/release/app-release.apk 
```
报错信息:
```
Error: 找不到bundle文件。请确保此apk为release版本，且bundle文件名为默认的 index.android.bundle
```
![image](https://user-images.githubusercontent.com/9305070/171306285-baec0f00-0e07-4ca8-956d-84e5b039ae05.png)
查看到 android/app/build/generated/assets 下有 index.android.bundle

**Comment by catericy** [comment]
```
"react-native": "0.67.4",
"react-native-update": "^7.4.2"
```

**Comment by sunnylqm** [comment]
默认路径是  assets/index.android.bundle  多的两个目录是你自己加的吗

**Comment by catericy** [comment]
> 

可能是 Gradle 升级到 7.3.3 的原因，我试一下降级再来反馈

**Comment by catericy** [comment]
降级 Gradle 至 7.0.4 解决此问题 
![image](https://user-images.githubusercontent.com/9305070/171529823-cc4f4836-433f-4beb-9670-66f5d50a3041.png)
