### ISSUE TITLE
pushy发布ppk时，期望支持用户传参控制生成sourcemap

### ISSUE THREAD

**Issue by blacksharksjc** [reactnativecn/react-native-pushy#395]
**问题原因**：我方使用pushy完成app的热更新功能，同时使用sentry对应用异常监控。由于没有sourcemap，sentry监控到的异常不能正常显示源码
**期望结果**：pushy在生成ppk的时候，用户可以传递参数控制sourcemap生成。如果开启，则能在intermedia目录中生成对应源码的sourcemap，便于上传sentry

**Comment by sunnylqm** [comment]
你好，cli 1.11版本已添加此参数 `--sourcemap`
