### ISSUE TITLE
提示您的应用版本已更新，点击确定下载安装新版本；

### ISSUE THREAD

**Issue by sa1utep1z** [reactnativecn/react-native-pushy#396]
下面就只有一个确定选项，点击确定也并没有更新版本。。
![c9542b72b192166c8137d7a0bfd2157](https://user-images.githubusercontent.com/74346590/183325621-a9577952-9a30-472e-9d69-6f373197034f.jpg)
。

**Comment by jingliangapp** [comment]
碰到一样的问题，原生版本更新。

**Comment by sunnylqm** [comment]
原生版本更新需要自己去网页后台配置下载链接
