### ISSUE TITLE
安装包无法更新修改后的文字。

### ISSUE THREAD

**Issue by geasscode** [reactnativecn/react-native-pushy#40]
pushy update --platform <ios|android> 使用这个选择相应打包的版本，用iTunes 安装的ipa 文件并不能看到修改后的一行文字。react-native 版本是0.33

**Comment by sunnylqm** [comment]
描述太模糊

**Comment by tdzl2003** [comment]
检查下jsCodeLocation是否正确修改过吧，另外更新过程是否有闪退等现象发生？
