### ISSUE TITLE
xcode8上无法build的问题

### ISSUE THREAD

**Issue by jiangbophd** [reactnativecn/react-native-pushy#41]
Undefined symbols for architecture x86_64:
  "_BZ2_bzRead", referenced from:
      _bz2_read in libRCTHotUpdate.a(bspatch.o)
  "_BZ2_bzReadClose", referenced from:
      _beginPatch in libRCTHotUpdate.a(bspatch.o)
  "_BZ2_bzReadOpen", referenced from:
      _beginPatch in libRCTHotUpdate.a(bspatch.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tdzl2003** [comment]
您好，您的问题是Build Phases里漏了添加libbz2.tbd，和Xcode8没有什么关系

**Comment by niuniubuniu** [comment]
请问这个问题解决了么 我也遇到了这个问题 加了libbz2.tbd 后没有解决 报错更多了

**Comment by sunnylqm** [comment]
@niuniubuniu 报什么错你就新开个issue截图贴出来

**Comment by songxing10000** [comment]
Build Phases里漏了添加libbz2.tbd 运行成功
