### ISSUE TITLE
Base.h:13:10 'butter/function.h' file not found

### ISSUE THREAD

**Issue by lingstart** [reactnativecn/react-native-pushy#414]
集成pushy的第一步：
npm i react-native-update

第二步：
在iOS工程目录下pod install

然后编译iOS工程，就报错
Base.h:13:10 'butter/function.h' file not found

求解！
1、已经尝试过删除pods文件，重新pod install，不行！
2、尝试npm uninstall react-native-update，然后重新npm install react-native-update，不行！
3、尝试新建iOS工程，再次执行上面的第一步和第二步，再次编译，还是不行！

啥情况啊，帮帮忙，我是m1笔记本，跟这个有没有关系啊，为什么google也搜不到这个问题

**Comment by sunnylqm** [comment]
看下package.json 这不像是我们引用的模块
