### ISSUE TITLE
后台崩了 

### ISSUE THREAD

**Issue by dokodream** [reactnativecn/react-native-pushy#416]
https://pushy-admin.reactnative.cn/#/user
![image](https://github.com/reactnativecn/react-native-pushy/assets/41332133/43beedd8-bbbc-4dc4-b421-bac166e7a6b4)

**Comment by sunnylqm** [comment]
是哪个接口？具体操作上有什么问题吗？

**Comment by dokodream** [comment]
接口没问题，命令行操作也可以，是访问 #/user 这个前端页面加载不出来

**Comment by sunnylqm** [comment]
清缓存试下？我这边可以加载

**Comment by dokodream** [comment]
![image](https://github.com/reactnativecn/react-native-pushy/assets/41332133/56f83e8b-f75b-4972-83e4-d26f5f0df897)
感谢回复，我尝试了清除缓存并更换不同浏览器和使用同事电脑，均发现此问题（未科学上网），浙江电信网段

**Comment by sunnylqm** [comment]
看起来是部分cdn节点缓存问题，已刷新cdn，请重试
