### ISSUE TITLE
react-native-update-cli@1.20.5无法安装，切换为1.20.0版本可以

### ISSUE THREAD

**Issue by Better-XKF** [reactnativecn/react-native-pushy#429]
<img width="1225" alt="Snipaste_2024-03-07_10-13-55" src="https://github.com/reactnativecn/react-native-pushy/assets/55829491/352928cc-1d4b-4c99-becb-c68d2d081882">

**Comment by Better-XKF** [comment]
![Uploading Snipaste_2024-03-07_10-15-18.png…]()

**Comment by Better-XKF** [comment]
![Uploading Snipaste_2024-03-07_10-15-18.png…]()

**Comment by Better-XKF** [comment]
![Snipaste_2024-03-07_10-15-18](https://github.com/reactnativecn/react-native-pushy/assets/55829491/8b2b74ff-1797-439e-b6e4-21ba23bddec2)

**Comment by Better-XKF** [comment]
> 请尝试安装1.20.6
<img width="1018" alt="Snipaste_2024-03-07_14-03-00" src="https://github.com/reactnativecn/react-native-pushy/assets/55829491/b883d887-f56d-4896-87d0-b416687ed9df">

1.20.6可以安装成功，但出现了其他问题

**Comment by sunnylqm** [comment]
1.21.0

**Comment by Better-XKF** [comment]
感谢，已解决
