### ISSUE TITLE
0.73 React Native ios 下载成功后，会回滚

### ISSUE THREAD

**Issue by Surile** [reactnativecn/react-native-pushy#431]

**Comment by sunnylqm** [comment]
https://pushy.reactnative.cn/docs/faq#%E7%83%AD%E6%9B%B4%E6%96%B0%E6%88%90%E5%8A%9F%E5%AE%8C%E6%88%90%E4%BD%86%E6%98%AF%E9%87%8D%E5%90%AF%E5%90%8E%E5%8F%88%E5%9B%9E%E6%BB%9A%E4%BA%86%E6%98%AF%E6%80%8E%E4%B9%88%E5%9B%9E%E4%BA%8B

**Comment by Surile** [comment]
正确集成了，使用 v10 的话， 也会出现回滚

**Comment by Surile** [comment]
![image](https://github.com/reactnativecn/react-native-pushy/assets/28652894/4ef5b86f-6080-419a-b7c5-c136a7db2e3e)

**Comment by sunnylqm** [comment]
确定打包的是release的ipa吗？

**Comment by Surile** [comment]
是的。我判断了__DEV__不让使用

**Comment by sunnylqm** [comment]
加我 qq 34731408 详细看下吧

**Comment by fgy888** [comment]
请问如何解决的？
