### ISSUE TITLE
cn.reactnative.modules.update 不存在

### ISSUE THREAD

**Issue by Jimmylxue** [reactnativecn/react-native-pushy#432]
求大佬讲解一下 为啥安卓构建会报这个错，依赖有安装

"react-native": "^0.64.4",
"react-native-update": "^10.3.1",
    "react-native-update-cli": "^1.22.0",
    
  
<img width="800" alt="image" src="https://github.com/reactnativecn/react-native-pushy/assets/65758455/21cec2f7-b11e-44e9-baf8-397abdd9c8c6">

**Comment by sunnylqm** [comment]
是monorepo结构吗，其他第三方包能找到吗？

**Comment by Jimmylxue** [comment]
是monorepo 其他的能找到，就咱这个找不到
<img width="991" alt="image" src="https://github.com/reactnativecn/react-native-pushy/assets/65758455/3479c2bb-eabe-45fe-a13a-87aa91e3d151">

**Comment by sunnylqm** [comment]
cli并不是项目依赖，不需要添加，
android/app/build.gradle里的implementation添加了吗

**Comment by Jimmylxue** [comment]
感谢您的回复~  现在加上了 但是报了一个库的   lambda 表达式的错误。
我的java版本是 11，项目比较老， 您知道这种情况应该如何解决吗（RN新人，问的可能会比较呆）
![img_v3_029r_9f915a84-6516-4278-acb9-965f70d8767g](https://github.com/reactnativecn/react-native-pushy/assets/65758455/3586bb81-1b19-4910-9891-eeb70be54612)

**Comment by Jimmylxue** [comment]
万分感谢您的回复，顺便附上我的一些配置
android {
  ...
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}
我的这两个设置都是 8的版本 不懂为啥会报这个  7 的版本问题

**Comment by sunnylqm** [comment]
因为你的rn版本比较老，上面这个配置可能也要加到pushy的android/build.gradle里

**Comment by Jimmylxue** [comment]
感谢，按照您的指示，我在react-native-update的包中加了如下配置，应用编译成功，后续我打个补丁，如果旧版本rn的同学也可以尝试这样
<img width="821" alt="image" src="https://github.com/reactnativecn/react-native-pushy/assets/65758455/5f421648-15fc-4950-9b91-ba26e09e2eee">
