### ISSUE TITLE
react-native-update模块无法加载，请对照安装文档检查配置

### ISSUE THREAD

**Issue by Jimmylxue** [reactnativecn/react-native-pushy#433]
麻烦大家有空帮忙看看，我肯定已经按照官网进行配置了
<img width="680" alt="image" src="https://github.com/reactnativecn/react-native-pushy/assets/65758455/b1528e54-9236-4fef-857c-4c322406fce7">
<img width="779" alt="image" src="https://github.com/reactnativecn/react-native-pushy/assets/65758455/c1d6d24e-ab46-4c98-9b54-bb62a6fe62d4">

当我执行：
const pushyClient = new Pushy({
  appKey,
})
之后会报一个错误：react-native-update模块无法加载，请对照安装文档检查配置

"react-native": "^0.64.4",
"react-native-update": "^10.3.1",

**Comment by Jimmylxue** [comment]
<img width="629" alt="image" src="https://github.com/reactnativecn/react-native-pushy/assets/65758455/a2d3fa4f-6179-4440-b2f6-d5995e482238">

**Comment by sunnylqm** [comment]
getpackages里缺了

![image](https://github.com/reactnativecn/react-native-pushy/assets/615282/b90c336e-046f-4af0-aeb8-375743eb6099)

**Comment by Jimmylxue** [comment]
已解决 谢谢大佬

**Comment by Jimmylxue** [comment]
因为我rn版本比较低 使用的是 所以react-native-update 使用的是 8.x的版本 可以解决这个问题

**Comment by Jimmylxue** [comment]
那是否是文档有一点错误呢~
<img width="771" alt="image" src="https://github.com/reactnativecn/react-native-pushy/assets/65758455/ded33cc1-afc2-4a9b-ba86-18bb94dee098">
这个写的是小于0.60 但是我是0.64 所以其实我没有看这块的配置

**Comment by Jimmylxue** [comment]
咱们是否有群呢~  有些问题想再请教请教 可能会方便点儿~

**Comment by sunnylqm** [comment]
![image](https://github.com/reactnativecn/react-native-pushy/assets/615282/01fb0921-7410-4f07-bddb-f456500fc20f)
![image](https://github.com/reactnativecn/react-native-pushy/assets/615282/02ec2498-d3cc-448d-9cee-6b6b7a9de6c4)

你的情况等同于混编rn项目（或由于任何其他原因导致不能自动link的情况）
![image](https://github.com/reactnativecn/react-native-pushy/assets/615282/288ff7d1-5ccd-451c-add9-371ae96f6f0e)
