### ISSUE TITLE
reactnative更新到35，编译出错啦

### ISSUE THREAD

**Issue by jinghun1999** [reactnativecn/react-native-pushy#44]
``
:react-native-update:compileReleaseJavaWithJavac
D:\Work\GitHub\Tuorui\node_modules\react-native-update\android\src\main\java\cn\reactnative\modules\update\UpdateModule.java:128: 错误: 无法将类 JSBundleLoader 中的方法 createFileLoader应用到给定类型;
                        JSBundleLoader loader = JSBundleLoader.createFileLoader(application, UpdateContext.getBundleUrl(application));
                                                              ^
  需要: String
  找到: Application,String
  原因: 实际参数列表和形式参数列表长度不同
1 个错误
:react-native-update:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':react-native-update:compileReleaseJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  ``

**Comment by ForteenC** [comment]
@jinghun1999 我也遇到了这个问题，请问你解决了吗？

**Comment by sunnylqm** [comment]
暂时先删掉第一个参数即可

**Comment by movetosun** [comment]
我也是遇到了这个问题,

**Comment by sunnylqm** [comment]
已修复 https://github.com/reactnativecn/react-native-pushy/commit/05b98b10bf721200598b27caf03c0be158cca757

**Comment by susan-github** [comment]
@sunnylqm 能同步到npm上么，现在安装的还是上一个版本，有application参数的代码

**Comment by sunnylqm** [comment]
@susan-github 请安装4.x版本

**Comment by susan-github** [comment]
@sunnylqm thx
