### ISSUE TITLE
monorepo 安装最新10.10.1 版本失败，请问是我配置问题吗

### ISSUE THREAD

**Issue by Jimmylxue** [reactnativecn/react-native-pushy#442]
pod install 报错了 请问应该如何解决 项目有点老  
react-native 0.64.4
<img width="1256" alt="image" src="https://github.com/user-attachments/assets/cb3f224e-f984-4692-a70f-9c8e6fc27e6d">

**Comment by sunnylqm** [comment]
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/8c819bbb-61f0-4e07-9b93-7ef18b74c5d8">
目前最低要求11

**Comment by Jimmylxue** [comment]
好的   感谢您 回复的太快了  本人ios小白  不太懂这块  这个更改一般会影响其他东西吗   还是有旧版本的react-native-update  不限制这个版本

**Comment by sunnylqm** [comment]
影响无法预测，只能碰到问题再解决问题
旧版本的react-native-update已不再维护

**Comment by Jimmylxue** [comment]
好的 感谢大佬  目前看下来平稳运行 没什么问题
