### ISSUE TITLE
pushy 现在是差分方案吗？我看了一下代码，好像不是整包下发是吗？

### ISSUE THREAD

**Issue by amy123shy** [reactnativecn/react-native-pushy#443]
![image](https://github.com/user-attachments/assets/c7c30384-e452-4694-85fd-a14f1acdebe0)
![2641722494048_ pic](https://github.com/user-attachments/assets/04f0dd29-e67e-4794-8f90-6b4b15e2def6)
看图片只有PushyTypePatchFromPackage 和PushyTypePatchFromPpk 没有差分代码，是这样吗？

**Comment by sunnylqm** [comment]
一直都是差分方案，patch就是调用差分
