### ISSUE TITLE
release error

### ISSUE THREAD

**Issue by awoshiwu** [reactnativecn/react-native-pushy#446]
当插件版本是com.android.tools.build:gradle:4.0.1的时候，打包提示/Users/apple/Documents/MacProjects/mankeApp/node_modules/react-native-update/android/src/main/java/cn/reactnative/modules/update/UpdatePackage.java:28: 错误: -source 7 中不支持 lambda 表达式

当插件版本是com.android.tools.build:gradle:4.2.0的时候，可以打包，但提示Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release这个。

gradle 6.7.1            
 buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 33

**Comment by sunnylqm** [comment]
rn版本多少？

**Comment by awoshiwu** [comment]
"react-native": "0.62.2",
好像这个版本和gradle插件冲突，gradle插件4.2.0的时候就提示这个Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release

**Comment by awoshiwu** [comment]
> rn版本多少？

"react-native": "0.62.2",
好像这个版本和gradle插件冲突，gradle插件4.2.0的时候就提示这个Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release

**Comment by sunnylqm** [comment]
在pushy的build.gradle里加入
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

**Comment by awoshiwu** [comment]
> 在pushy的build.gradle里加入
> 
> ```
> android {
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> }
> ```

这个好用了，下个版本会优化这块么
