### ISSUE TITLE
android  回滚

### ISSUE THREAD

**Issue by wooter-s** [reactnativecn/react-native-pushy#45]
安卓，应用管理强制关闭应用就回滚了，是因为markSuccess()没有成功吗？
  componentDidMount() {
      this.addEventListenerBack()
        this.getPosition()
        //更新
        this.checkUpdate()
        if (isFirstTime) {
          markSuccess()
        } else if (isRolledBack) {
          Alert.alert('提示', '刚刚更新失败了,版本被回滚.');
        }
    }

**Comment by zijing07** [comment]
我也是这样的情况，你有解决吗？

**Comment by DesignerTime** [comment]
+1

**Comment by DesignerTime** [comment]
@zijing07  @wooter-s  问题解决了吗，有提示  版本被回滚  吗，我没有提示，但版本也回滚了

**Comment by yuanmao5200** [comment]
同样问题 有解决办法吗

**Comment by DesignerTime** [comment]
@yuanmao5200  Android的要单独配置好原生的代码，如果没有按照项目主页说明的步骤配置，就很有可能出现这样的情况

**Comment by 289420843** [comment]
同样出现此问题

**Comment by meihuabo** [comment]
同样出现此问题

**Comment by peterfei** [comment]
同样出现此问题+1

**Comment by tdzl2003** [comment]
Android的要单独配置好原生的代码，如果没有按照项目主页说明的步骤配置，就很有可能出现这样的情况
