### ISSUE TITLE
Android 热更新后SVG图标丢失, PNG图标正常

### ISSUE THREAD

**Issue by ahjsrhj** [reactnativecn/react-native-pushy#452]
Android 热更新后 SVG 图标丢失, PNG 图标正常
IOS 热更新后正常

项目为基于Taro的跨端项目, React Native版本号为: 0.73.5

react-native-update版本号为: 10.15.0

请问可能是什么原因?

**Comment by sunnylqm** [comment]
再次重启后是否能显示

**Comment by ahjsrhj** [comment]
> 再次重启后是否能显示

多次重启表现都相同, svg图标不能显示, 现在尝试将svg资源转为js代码内存储看能否正常

**Comment by sunnylqm** [comment]
之前是如何存储的？

**Comment by ahjsrhj** [comment]
> 之前是如何存储以及如何使用的？
和PNG图片一样, 存储为单独的svg文件, 然后import进代码里使用

现在改为了将svg字符串保存到JS代码里, 当做字符串处理,  使用改为 <SvgXml xml={svgXml} /> 
修改后热更新正常了
