### ISSUE TITLE
Android编译不通过，让我安装并配置NDK，是必须要这样吗

### ISSUE THREAD

**Issue by doubleruis** [reactnativecn/react-native-pushy#46]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-update:compileReleaseNdk'.
> NDK not configured.
  Download the NDK from http://developer.android.com/tools/sdk/ndk/.Then add ndk.dir=path/to/ndk in local.properties.
  (On Windows, make sure you escape backslashes, e.g. C:\\ndk rather than C:\ndk)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by sunnylqm** [comment]
是的

**Comment by doubleruis** [comment]
@sunnylqm 能不能贴个ndk的安装教程啊，我用的是webstorm，不会配置，O(∩_∩)O谢谢

**Comment by sunnylqm** [comment]
这不就是安装教程吗
Download the NDK from http://developer.android.com/tools/sdk/ndk/.Then add ndk.dir=path/to/ndk in local.properties.

**Comment by doubleruis** [comment]
@sunnylqm 不会断句😢

**Comment by sunnylqm** [comment]
1、从http://developer.android.com/tools/sdk/ndk/ 下载并安装ndk
2、在项目根目录的local.properties文件中（没有就新建一个）添加
```
ndk.dir=你安装的ndk的路径
```
3、完

**Comment by doubleruis** [comment]
@sunnylqm 太感谢您啦

**Comment by America-first-melon** [comment]
根目录？ 哪个目录？ndk.dir=/Users/admin/Library/Android/android-ndk-r8

**Comment by America-first-melon** [comment]
根目录？直接放到initmulu下吗？

**Comment by sunnylqm** [comment]
应该是android目录？。。。
