### ISSUE TITLE
IOS编译通过，但是却无法获取检查更新的结果

### ISSUE THREAD

**Issue by doubleruis** [reactnativecn/react-native-pushy#47]
checkUpdate方法抛异
checkUpdate(appKey).then(info => {
      if (info.expired) {
        ……
      } else if (info.upToDate) {
        ……
      } else {
        ……
      }
    }).catch(err => {
     //直接就到这里了，异常是 network request failed网络请求失败
    });

**Comment by sunnylqm** [comment]
请检查ats配置 
https://github.com/reactnativecn/react-native-pushy/blob/master/docs/guide.md#ios的ats例外配置

**Comment by doubleruis** [comment]
@sunnylqm 再次感谢，解决啦。
