### ISSUE TITLE
Execution failed for task ':react-native-update:compileReleaseNdk'.

### ISSUE THREAD

**Issue by yuqirong** [reactnativecn/react-native-pushy#49]
Error:Execution failed for task ':react-native-update:compileReleaseNdk'.

com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android-sdk\ndk-bundle\ndk-build.cmd'' finished with non-zero exit value 2

我使用 react-native run-android 运行程序，结果报如上的错误。应该要怎么解决？

**Comment by sunnylqm** [comment]
某些版本的ndk可能有问题

**Comment by doubleruis** [comment]
我什么都配置好了，还是报原来的错，是我配置的不对吗？
bash_profile:
export PATH=${PATH}:/Users/doubleruis/Downloads/android-ndk-r13
A_NDK_ROOT=/Users/doubleruis/Downloads/android-ndk-r13
export A_NDK_ROOT

local.properties:
sdk.dir=/Users/doubleruis/Library/Android/sdk
ndk.dir=/Users/doubleruis/Downloads/android-ndk-r13
结果还是报错：NDK not configured

**Comment by xiaoqian9** [comment]
同样的问题~

**Comment by phonebird** [comment]
楼主解决了吗

**Comment by yuqirong** [comment]
@phonebird 没有解决，后来使用 Code Push 了

**Comment by xnllc** [comment]
哪个ndk版本没有问题呢？ 我去替换能用的版本

**Comment by sunnylqm** [comment]
r10e确定可以

**Comment by xiaoqian9** [comment]
@sunnylqm 我现在试过了 ndk r10d、r10e和r12b 三个版本，都不行~

**Comment by phonebird** [comment]
@xiaoqian9 你是不是在windows上出现的？路径太长了，试着改短一点就可以了

**Comment by xiaoqian9** [comment]
@phonebird 确实是这个问题，困扰了我好久！！非常感谢

**Comment by wangpengzong** [comment]
请问我这个是什么原因

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-update:compileReleaseNdk'.
> Error: Your project contains C++ files but it is not using a supported native build system.
Consider using CMake or ndk-build integration with the stable Android Gradle plugin:
 https://developer.android.com/studio/projects/add-native-code.html
or use the experimental plugin:
 http://tools.android.com/tech-docs/new-build-system/gradle-experimental.`

**Comment by basilbai** [comment]
@wangpengzong 我现在和你遇到一样的问题了

**Comment by xinwanggit** [comment]
请问有人解决吗?
Warning: Deprecated NDK integration enabled by useDeprecatedNdk flag in gradle.properties will be removed from Android Gradle plugin soon.
Consider using CMake or ndk-build integration with the stable Android Gradle plugin:
 https://developer.android.com/studio/projects/add-native-code.html
or use the experimental plugin:
 http://tools.android.com/tech-docs/new-build-system/gradle-experimental.

:react-native-update:compileReleaseNdk FAILED

FAILURE: Build failed with an exception.

**Comment by xinwanggit** [comment]
已解决 需要配置NDK
