### ISSUE TITLE
Android编译通过，引用react-native-update就报错

### ISSUE THREAD

**Issue by doubleruis** [reactnativecn/react-native-pushy#51]
只要引用了
import {
    currentVersion,
} from 'react-native-update';
就会报错
MainActivity：
public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
     protected String getJSBundleFile() {
             return UpdateContext.getBundleUrl(this);
         }
    @Override
    protected String getMainComponentName() {
        return "GodatripTools";
    }
}
MainApplication：
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected String getJSBundleFile() {
      return UpdateContext.getBundleUrl(MainApplication.this);
    }
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
          , new VectorIconsPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
![image](https://cloud.githubusercontent.com/assets/22313611/19848636/babb6522-9f89-11e6-9806-f4ba0595d886.png)

**Comment by sunnylqm** [comment]
这个错误一般是因为link步骤不正确

**Comment by doubleruis** [comment]
@sunnylqm link结果:
![image](https://cloud.githubusercontent.com/assets/22313611/19849370/d73eeecc-9f8d-11e6-9fcf-996ac8b5f0c3.png)

**Comment by sunnylqm** [comment]
由于版本迭代很快，自动link未必可靠。建议再手动link走一遍。

**Comment by doubleruis** [comment]
@sunnylqm 好了，O(∩_∩)O谢谢
