### ISSUE TITLE
When downloadUpdate, we caught en error, code: EUNSPECIFIED

### ISSUE THREAD

**Issue by jiangsumadai** [reactnativecn/react-native-pushy#55]
downloadUpdate(info).then(hash => {
    ...
}).catch(err => {
    Alert.alert('提示', '更新失败');
});

**Comment by tdzl2003** [comment]
Platform? iOS or Android?
Any more logs or screenshot?

Try on another network environment?

**Comment by jiangsumadai** [comment]
IOS
detail as accessory
![screenshot_2016-11-08-20-07-58](https://cloud.githubusercontent.com/assets/8002482/20661599/9a5ad210-b58a-11e6-882b-1690f1ac9232.png)

**Comment by jiangsumadai** [comment]
android @tdzl2003 
![screenshot_2016-11-08-20-07-58](https://cloud.githubusercontent.com/assets/8002482/20665524/fc7106c6-b59a-11e6-94ef-3f4f1a2f8a74.png)

**Comment by sunnylqm** [comment]
你底部有黄色警告，是在debug环境中调试吗？热更新只能在release环境下调试
