### ISSUE TITLE
[Android] 划掉应用后，再次打开更新消失

### ISSUE THREAD

**Issue by zijing07** [reactnativecn/react-native-pushy#56]
如题，更新应用成功后，我再将应用进程关掉，再次打开的时候，app就又恢复到原始状态了。

据同事说，iOS上也一样的表现，即如果应用进程关闭，再次打开，则会回到原来状态。

谢谢！

**Comment by zijing07** [comment]
我又看了一下文档，是不是一定要调用 markSuccess 才行？

**Comment by zijing07** [comment]
明白了，是我文档看的不仔细

**Comment by sunnylqm** [comment]
componentWillMount() { if (isFirstTime) markSuccess() } 
这个应该是行得通的

**Comment by zijing07** [comment]
我决定RIP

**Comment by GaaPill** [comment]
@zijing07 hhhh,我也遇到这个问题!  你们最后搞清楚是啥原因么QAQ

**Comment by kala888** [comment]
@zijing07  同样问题，RIP是啥？

**Comment by zijing07** [comment]
@kala888 我们后来使用微软的了，没再跟这边的问题了

**Comment by kala888** [comment]
@zijing07  各种调，现在可以用了，codepush 稳定性如何，之前集成了，后来它做了个大升级就又去掉了。
