### ISSUE TITLE
pushy diff获取不到差异patch

### ISSUE THREAD

**Issue by geniuslinchao** [reactnativecn/react-native-pushy#58]
执行pushy diff 1.ppk 2.ppk 之后获得的diff文件大小为0KB，rn版本0.31.0。但是linux下使用bsdiff工具比较2个ppk提取的bundle文件可以得到差分包

**Comment by geniuslinchao** [comment]
另外，pushy diffFromApk获取的aptch大小为1KB，但是里面也只有几个资源空目录

**Comment by geniuslinchao** [comment]
原因找到了，是因为diff函数引入问题导致的，我提交一下commit吧

**Comment by sunnylqm** [comment]
Fixed in https://github.com/reactnativecn/react-native-pushy/pull/59
