### ISSUE TITLE
更新包图片等静态资源打包问题

### ISSUE THREAD

**Issue by swb2016** [reactnativecn/react-native-pushy#60]
请问，如果我在js代码里是直接使用本地路径，类似file:///android_asset...这类的路径来引用图片，在增加了新图片时，通过打包操作能将图片达到ppk中吗？如果不能，那能否通过对命令进行改进来实现吗？

**Comment by sunnylqm** [comment]
目前只能是通过require引用的资源可以热更新

**Comment by swb2016** [comment]
diff打差异包也是只有require引用的资源才能被打进差异包吗？

**Comment by tdzl2003** [comment]
Android assets中的文件不能通过热更新更新。热更新下来的文件也并非保存在assets中。

针对require引用的资源，因为方式比较明确，本插件提供了成型的方法去更新。对于你说的这种情形，你只能自行去管理，在更新后去访问新的地址。
