### ISSUE TITLE
服务器挂了？

### ISSUE THREAD

**Issue by forrest23** [reactnativecn/react-native-pushy#62]

**Comment by forrest23** [comment]
@sunnylqm  @tdzl2003    服务器挂了？  http://reactnative.cn/ 也无法访问了

**Comment by sunnylqm** [comment]
流量过大，现已恢复

**Comment by forrest23** [comment]
好担心 如果APP正式上线，热更新服务能不能撑住啊 @sunnylqm

**Comment by tdzl2003** [comment]
因为更新是在客户端本地基于差异更新，即使热更新服务器出现故障，也应当不会影响您的应用运行。

不过要更可靠及时的更新，可以考虑搭建私有更新服务，详情请联系QQ:402740419
