### ISSUE TITLE
编译报blocksort.o.d: No such file or directory

### ISSUE THREAD

**Issue by phonebird** [reactnativecn/react-native-pushy#64]
你好，我使用的ndk版本是10，
gradle.properties配置了android.useDeprecatedNdk=true，
local.properties配置sdk和ndk的路径都是对的。
，编译报以下错误，是在想不通什么原因。
Error:(1089, 1) opening dependency file D:\ASProject\phonebird.fr.20161128.ForYouDun\node_modules\react-native-update\android\build\intermediates\ndk\release\obj/local/armeabi-v7a/objs/rnupdate/D_\ASProject\phonebird.fr.20161128.ForYouDun\node_modules\react-native-update\android\src\main\jni\blocksort.o.d: No such file or directory

Error:Execution failed for task ':react-native-update:compileReleaseNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\ProgramFiles\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2

**Comment by xiaoqian9** [comment]
亲，可以结贴了~

**Comment by kenvies** [comment]
楼主有没有解决这个问题？求分享

**Comment by sunnylqm** [comment]
@kenvies 可能与项目路径过长有关

**Comment by sunnylqm** [comment]
@kenvies 你试下这两个方案，一是把项目放到根目录（缩短路径），二是据说在jni目录中放一个空的.c文件也可以解决

**Comment by chriiess** [comment]
环境MAC出现过这个问题
用以下方法解决了
使用Android Studio->Preferences->Appearance & Behavior->System Settings->Android SDK->SDK Tools
勾选NDK
apply
ok,解决！
