### ISSUE TITLE
检查更新结果为expired: true

### ISSUE THREAD

**Issue by phonebird** [reactnativecn/react-native-pushy#66]
我Android打了个包，通过pushy uploadApk上传，然后pushy bundle打包发布到该版本上，为什么检查更新提示{ expired: true, downloadUrl: null, ok: 1 }？
这个是什么意思？

**Comment by phonebird** [comment]
我确认这个包和我发到市场上的是同一个包，你们是通过什么判断这个原生应用已过期的？

**Comment by lengguoxing** [comment]
http://bbs.reactnative.cn/topic/4493/关于多个版本设置关联更新问题-求助
你有碰到这个问题吗@phonebird

**Comment by tdzl2003** [comment]
以AndroidManifest中包的版本号(打包的时候用build.gradle，可以用各种第三方工具查看包的版本)为准，确认你在web端能否看到相同的版本号。如果没有，就会出现expired:true。
