### ISSUE TITLE
Android检查更新慢

### ISSUE THREAD

**Issue by pamler** [reactnativecn/react-native-pushy#67]
目前在android环境下，如果没有最新版本，检查更新结果返回很快。但是一旦上传了一个新版本，检查更新的结果返回的不稳定，有时特别慢，而且可能会超时失败等等。猜测是不是后端服务在查询新版本的时候，有索引性能的问题。。。IOS环境倒是没有发现这个问题。不知道其他人有没有遇到这个问题。
RN: 0.37.0
react-native-update: 4.0.0

**Comment by 289420843** [comment]
有这个问题，android更新读取apk资源文件性能问题，非常慢

**Comment by CrazyStoneJy** [comment]
这个问题解决了吗？

**Comment by tdzl2003** [comment]
检查更新还是执行更新慢？检查这块和iOS应该是没有差异的，执行更新目前执行pdiff更新的时候确实会慢，可以考虑若资源较多，可以删除pdiffUrl来绕过基于包的差异更新，这样在这种情况下会执行一次完整更新。

我们也在内部实验相应的优化方案，可以联系QQ:402740419提前试用。

**Comment by pamler** [comment]
我提的问题只是android会经常出现，很奇怪。现在我这边的确是检查更新慢，不是执行更新慢，假如属于{expired: true} 或者 {upToDate: true} 这两种情况，检查更新的返回总是很快的。但是如果是{update: true}，checkUpdate却总是返回的很慢。都是在同样的网络情况下测试的。

**Comment by pamler** [comment]
后面又复查了一下，的确很多情况下，android执行更新很慢。期待后面的优化 @tdzl2003

**Comment by susliang** [comment]
执行更新慢的问题，解决了么？@tdzl2003

**Comment by susan-github** [comment]
@tdzl2003 怎么删除pdiffUrl来绕过基于包的差异更新？

**Comment by sunnylqm** [comment]
@susan-github 参考 https://segmentfault.com/a/1190000008005637

**Comment by tdzl2003** [comment]
5.1.0版本已经解决了这个问题
