### ISSUE TITLE
升级包大小问题

### ISSUE THREAD

**Issue by lesliesam** [reactnativecn/react-native-pushy#7]
我查看了一下升级包大小和内容，发现并没有介绍说的超小更新包，我只是修改了一个数字而已，结果更新包要150k。
请问是如何生成一个超小更新包？

**Comment by tdzl2003** [comment]
您检查的是否ppk的尺寸？ppk会包含完整的脚本和资源，所以会相对较大，但实际客户端更新时，并不会下载完整的ppk，而是会下载一个diff文件，具体的下载路径你可以checkUpdate异步返回的info中找到，其中存在三个地址：

1. 完整下载ppk（最大）
2. 下载从apk/ipa到最新ppk的更新包（较小）
3. 如果之前更新过，下载从上一ppk到最新ppk的更新包（通常最小）

其中2和3提供的才是差异更新的下载地址，小到几百字节。downloadUpdate会按照从3到1的顺序逐个尝试。

**Comment by tdzl2003** [comment]
补充一下，还有一种可能性，如果你从debug版本的bundleUrl升级到release的，那二者差异会很大，可能也会有几百字节大小。如果你的包包含的是dev=true版本的bundle，那么pushy bundle的时候也需要带上 --dev 参数

**Comment by lesliesam** [comment]
我没有检查ppk的尺寸，我是用Fiddler截获了更新的http请求，查看了response，发现下载的包是150k左右。

**Comment by tdzl2003** [comment]
线上看了一下，昨天自动生成差异包的服务出现了一次卡死，有可能当时刚好没有生成您的差异包，为了确保功能正常，就进行了完整更新。我们会进一步提高服务的可用性，感谢试用和汇报，有任何紧急问题也可以联络QQ:402740419 或者通过网站首页关于的电话联系我们：）

**Comment by tdzl2003** [comment]
[热更新服务20160621-20160622差异包故障公告](http://bbs.reactnative.cn/topic/898/)

**Comment by lesliesam** [comment]
我运气够好的啊！那我今天再试试看。
