### ISSUE TITLE
请问如何安装ndk呢？

### ISSUE THREAD

**Issue by daffy6537** [reactnativecn/react-native-pushy#71]
官网没有任何安装方法的说明，其他地方的都说的是执行
./android-ndk-r10e-darwin-x86_64.bin文件 

但我从官网下载的是 zip 格式的文件 android-ndk-r10e-darwin-x86_64.zip 安装不了

**Comment by the-ant** [comment]
@daffy6537 解压后，然后将环境变量指向解压后的目录
