### ISSUE TITLE
用pod 引入RN，然后添加RCTHotUpdate一直提示 文件RCTBridgeModule.h等React里的类找不到

### ISSUE THREAD

**Issue by Alvin365** [reactnativecn/react-native-pushy#73]
用pod 引入RN，然后添加RCTHotUpdate一直提示 文件RCTBridgeModule.h等React里的类找不到，求解

**Comment by sunnylqm** [comment]
path对得上吗

**Comment by HarrisLee** [comment]
我也是这个情况。 你解决了么？

**Comment by leeshuangai** [comment]
解决了吗 我也是这种情况

**Comment by a728384698** [comment]
![90b99bb3-bf9e-4721-93c2-4b2e563e0688](https://user-images.githubusercontent.com/7380874/34715186-b38c0f8e-f566-11e7-85ac-443df79be743.png)
