### ISSUE TITLE
加入热更新JS代码后安卓运行显示undefined is not an object (evaluating 'HotUpdate.downloadRootDir')

### ISSUE THREAD

**Issue by chen236310** [reactnativecn/react-native-pushy#74]
我加入热更新JS代码后安卓出现这个错误，我也是照着这个例子写的，而且我写的代码里面没有这个HotUpdate.downloadRoot,我在这个第三方里面找到了这个，而且link也是正确的，这个问题该如何解决，有人能回答下吗？非常感谢~

**Comment by sunnylqm** [comment]
请尝试照着文档手动link并重新编译

**Comment by chen236310** [comment]
可以，我移除后再重新安装，再更新RNMPM ,再link之后就可以了~谢谢！！！
