### ISSUE TITLE
增加 JSBundleFile 获取的途径

### ISSUE THREAD

**Issue by alighters** [reactnativecn/react-native-pushy#76]
在 bundle 热更新的时候，代码中是通过获取 application，强转为 ReactApplication，进而修改 bundleFile 的路径。

但是，如果我就没有使用 ReactApplication，相应的设置逻辑 reactInstanceManager 都在 Activity 中呢？项目是原生项目，只是通过一个界面来集成 RN 的逻辑，这种情况漏考虑了。

建议：提供一个接口出来，我相应的 activity 来实现这个接口，在更新 bundleFile 路径的时候，判断这个 activity 实现了这个接口，直接进行调用来更新。

**Comment by sunnylqm** [comment]
5.5.8版本开始提供了setCustomInstanceManager方法，可以尝试下
https://github.com/reactnativecn/react-native-pushy/blob/v5.5.8/android/src/main/java/cn/reactnative/modules/update/UpdateContext.java#L166
