### ISSUE TITLE
如何静默更新呢？

### ISSUE THREAD

**Issue by chichengjunma** [reactnativecn/react-native-pushy#77]
一般的用户体验都是不需要太繁杂的操作，需要后台静默更新，pushy可否支持静默更新呢？是通过Meta Info吗？

**Comment by sunnylqm** [comment]
对的，通过metainfo设定一个标志，自行判断

**Comment by chichengjunma** [comment]
@sunnylqm   标志是什么呢{"silent":true}不生效呢？

**Comment by sunnylqm** [comment]
metainfo只是一个字符串而已，任何功能都需要你自己实现
你自己在metainfo里设定一个标志，自己去做JSON解析和if判断

**Comment by chichengjunma** [comment]
@sunnylqm 1、metainfo在什么字段里可以获取到呢？
2、官方热更新的demo Hash都不为空了，但是其他View的状态和值不变，仍是旧的，这是什么原因呢？

**Comment by sunnylqm** [comment]
1. 请看文档
2. release版本才能正确热更新
