### ISSUE TITLE
集成React Native Pushy获取bundleUrl为null

### ISSUE THREAD

**Issue by moreFine** [reactnativecn/react-native-pushy#78]
jsCodeLocation = [RCTHotUpdate bundleURL];的值是null,请问问题可能出现在哪里?

**Comment by moreFine** [comment]
紧急求助.各位哥

**Comment by sunnylqm** [comment]
请给出具体的操作步骤

**Comment by moreFine** [comment]
@sunnylqm 目前查出的问题打包ipa的时候并没有自动打离线包main.jsbundle......你了解这种错误原因么

**Comment by moreFine** [comment]
为什么不自动打离线包现在问题还没找到,但是我手动打了离线包main.jsbundle导入到工程,,然后打包ipa热更新功能可以使用....

**Comment by sunnylqm** [comment]
可能集成过程中缺少一些自动打包的脚本

**Comment by moreFine** [comment]
@sunnylqm 自动打包的脚本都RN项目的哪些文件中,,,我是否可以手动copy到相应路径中.是不是我用用cocoapod导入的问题

**Comment by sunnylqm** [comment]
你可能得对比一下init的纯rn项目，具体我不了解

**Comment by HarrisLee** [comment]
能问下你是用什么命令打包的？   然后是把打包好的jsbundle加入到项目里面么？  我现在卡在这一步了。

**Comment by moreFine** [comment]
@HarrisLee 我现在用的codePush热更新框架；打包命令是：react-native bundle --entry-file index.ios.js --bundle-output ./ios/bundle/main.jsbundle --platform ios --assets-dest ./ios/bundle --dev false  ；这还是iOS的打包命令 ；安卓的打包命令：react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

**Comment by HarrisLee** [comment]
@moreFine  好的。   热更新问题我已经解决了。   用的就是pushy。  谢谢了。

**Comment by watermelon520** [comment]
@moreFine  请问你是把bundle放到哪里，放到react的根目录吗？我之前都是在react根目录创一个bundle文件夹再拖入项目里的。
