### ISSUE TITLE
pushy是通过何种方式来判断应用是否需要更新的呢？

### ISSUE THREAD

**Issue by wh469012917** [reactnativecn/react-native-pushy#79]
不知道方便说吗？我有碰到这样一个问题：
1.修复了bug并且通过pushy提交一个新版
2.把修复后的代码重新打包成apk，并且发布到商店

这是很常见的两个步骤，可以让已经安装的用户直接更新，未安装的用户可以安装最新版。但是，这时未安装的用户安装后却提示要更新（实际上这已经是最新版，不应该提示），是何原因？

在此期间我做过这个操作：
登录到pushy的web后台，修改了最新提交的版本号和description，是否是和这个有关系？

**Comment by sunnylqm** [comment]
第2步应该修改版本号再上传（同时提交到pushy）

**Comment by wh469012917** [comment]
@sunnyIqm 也就是说，pushy到服务端之后，不能再做任何修改了(包括pushy控制台的应用版本号和版本描述)，如果有修改就必须重新打包和pushy对吧？如果是这样的话，那就建议web端(pushy控制台)的版本号和描述设置为不能修改才对，你觉得呢？

我还有遇见这样的一个问题：
1. 发过一个版本(该apk版本也提交到了pushy，以供后续版本比对之用)，并且提交到了商店(假设为版本A)
2. 新增了功能，并且pushy提交后，打包再次发布到了商店(假设为版本B)
3. 用户首次下载版本B
4. 新增了功能，并且pushy提交后，打包再次发布到了商店(假设为版本C)
5. 用户端提示版本需要重新下载(无法通过pushy更新到版本C)
6. 点击确定闪退(实际应该打开一个url，该url是应用的下载地址，在pushy控制台设置的)

也就是说，要通过pushy热更新，用户首次下载的版本必须是首次上传到pushy的apk(在这里是版本A)，如果用户首次下载的不是版本A，那么热更新功能就无法使用，这么理解对吗？

以上所有的都是在IOS下测试过的实际情况。

**Comment by sunnylqm** [comment]
你可以针对不同的原生包生成不同的ppk，然后分别绑定。web端界面目前确实不够友好，感谢你的建议。

**Comment by daffy6537** [comment]
@wh469012917 CodePush有这方面的问题吗？

**Comment by lengguoxing** [comment]
http://bbs.reactnative.cn/topic/4493/关于多个版本设置关联更新问题-求助
你有碰到这个问题吗@sunnylqm
