### ISSUE TITLE
ios  AppDelegate.m的写法 问题请教

### ISSUE THREAD

**Issue by 52myu** [reactnativecn/react-native-pushy#8]
#if DEBUG
    // 原来的jsCodeLocation
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
  #else
    jsCodeLocation=[RCTHotUpdate bundleURL];
  #endif

//  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];  //注释 的此段代码需要注释么  

是否  需要写成
#if DEBUG
    // 原来的jsCodeLocation
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
  #else
    jsCodeLocation=[RCTHotUpdate bundleURL];
    jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  #endif

**Comment by sunnylqm** [comment]
同一赋值语句肯定后者覆盖前者。所以如果你这样写，  [RCTHotUpdate bundleURL]就等于没写，等于没有引入热更新，只使用本地离线bundle

**Comment by 52myu** [comment]
那意思是这样写才是正确的是不
#if DEBUG
// 原来的jsCodeLocation
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
#else
jsCodeLocation=[RCTHotUpdate bundleURL];
#endif

// jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

**Comment by sunnylqm** [comment]
对的
