### ISSUE TITLE
部分安卓机型上，开始执行更新后，会影响APP原有的request

### ISSUE THREAD

**Issue by susliang** [reactnativecn/react-native-pushy#80]
重现步骤：
1. 检查热更新，选择【是】，doUpdate
2. 在执行更新的过程中，继续操作APP
3. 应用的请求返回，都是不成功的。
机型：
多种安卓机型都有这个问题，例如魅族MX4，华为P8。
不知道是否是在请求diff的过程中，应用的请求被拦截了还是其他什么原因，不知道有没有人遇到相同的问题？

**Comment by sunnylqm** [comment]
需要有对应的日志分析

**Comment by susan-github** [comment]
设备： 魅族MX4 
系统：4.4.2
今天抓包看了一下，只要点击更新，发了http://update-packages.reactnative.cn， 应用的cookie就set不了，导致所有请求校验不了，返回都是401，所以想请教一下，是不是pushy在diff merge文件的时候，将原有的文件 锁住了，不让写文件。

第一张图是点击更新以后的，cookie的值，没写成功，所以导致下一次请求的请求头携带的Cookie, 不是最新的。

第二张图是没有点击更新的，Cookie一致。

<img width="600" alt="1" src="https://cloud.githubusercontent.com/assets/9947305/21890643/9ae7a12a-d909-11e6-94a6-2f4b4b219bdf.png">
<img width="300" alt="2" src="https://cloud.githubusercontent.com/assets/9947305/21890646/9d5eb600-d909-11e6-9100-021bbf173c85.png">

**Comment by sunnylqm** [comment]
@susan-github 请另外开个issue，谢谢

**Comment by susliang** [comment]
是同一个问题，这个issue是我提的 @sunnylqm

**Comment by susliang** [comment]
不好意思，手机和PC登了不同的git账号。

**Comment by sunnylqm** [comment]
试试绕过差异更新呢？

**Comment by susan-github** [comment]
@sunnylqm 试了一下，绕过差量更新，采用全量更新的方式，更新速度很快，但是下一次请求的请求头直接就没有Cookie了，整个APP，请求还是验证失败，只能重启应用，采用更新下来的bundle。
有没有可能是执行更新的时候，Cookie文件已经被替换掉了？

**Comment by TrustTheBoy** [comment]
@susan-github @sunnylqm 请问解决了吗，跟你同样的问题，开发模式时本地图片可以显示，但是打包之后只要是request引入的图片都不显示

**Comment by wufeng3** [comment]
我也遇到了同样的问题，请问解决了吗？ @susliang @sunnylqm

**Comment by susan-github** [comment]
原先是改成使用全量更新的方式，现在没在用pushy了@wufeng

**Comment by tdzl2003** [comment]
这个问题在最新版本(5.1.0)中解决了。
