### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by HaloWang** [reactnativecn/react-native-pushy#82]
将 RN 嵌入现有项目时，使用 `react-native link react-native-update` 会报错（react-native init 不会），没有像 CodePush 那样使用 CocoaPods 的方式来安装的吗？

**Comment by baileidmm** [comment]
在node_modules/react-native-update 新建 react-native-update.podspec 文件贴入以下内容 ，就可以在podfile中使用` pod 'react-native-update' , :path => './RnCom/node_modules/react-native-update'` 来配置了


`
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "react-native-update"
  s.version      = package["version"]
  s.summary      = "hot update for react-native"
  s.author       = "author (https://github.com/reactnativecn)"

  s.homepage     = "https://github.com/reactnativecn/react-native-pushy"

  s.license      = "MIT"
  s.platform     = :ios, "7.0"

  s.source       = { :git => "https://github.com/reactnativecn/react-native-pushy.git", :tag => "#{s.version}" }

  s.source_files  = "ios/**/*.{h,m,c}"

  s.libraries     = "bz2"

  s.dependency "React"
end
`

**Comment by tdzl2003** [comment]
@baileidmm 如果可以的话，能否关于podspec提供一个Pull-Request？感激不尽

**Comment by watermelon520** [comment]
react-native-update.podspec 文件 中的这行   package = JSON.parse(File.read(File.join(dir, "package.json")))   应该改为  package = JSON.parse(File.read(File.join(__dir__, 'package.json')))   要不然会报错

**Comment by chuyik** [comment]
@watermelon520 大哥，你这两行没区别吧。
应该是把 dir 改成 __dir__。

**Comment by chuyik** [comment]
我贴一个 CodePush+BSDiff 完整的 podspec:

```ruby
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|

  s.name           = 'CodePush'
  s.version        = package['version'].gsub(/v|-beta/, '')
  s.summary        = package['description']
  s.author         = package['author']
  s.license        = package['license']
  s.homepage       = package['homepage']
  s.source         = { :git => 'https://github.com/Microsoft/react-native-code-push.git', :tag => "v#{s.version}-beta"}
  s.platform       = :ios, '7.0'
  s.preserve_paths = '*.js'
  s.library        = 'bz2', 'z'

  s.dependency 'React'

  s.subspec 'Core' do |ss|
    ss.source_files = 'ios/CodePush/*.{h,m}'
    ss.public_header_files = ['ios/CodePush/CodePush.h']
  end

  s.subspec 'SSZipArchive' do |ss|
    ss.source_files = 'ios/CodePush/SSZipArchive/*.{h,m}', 'ios/CodePush/SSZipArchive/aes/*.{h,c}', 'ios/CodePush/SSZipArchive/minizip/*.{h,c}'
    ss.private_header_files = 'ios/CodePush/SSZipArchive/*.h', 'ios/CodePush/SSZipArchive/aes/*.h', 'ios/CodePush/SSZipArchive/minizip/*.h'
  end

  s.subspec 'BSDiff' do |ss|
    ss.source_files = 'ios/CodePush/BSDiff/*.{h,m,c}'
    ss.private_header_files = 'ios/CodePush/BSDiff/*.h'
  end

end
```

`react-native-pushy` 对着改一下就可以了。

**Comment by watermelon520** [comment]
@chuyik   　😂发完就没注意了
