### ISSUE TITLE
安卓机型上，开始执行更新后，APP原有的request引入的图片不显示

### ISSUE THREAD

**Issue by TrustTheBoy** [reactnativecn/react-native-pushy#89]
安卓不论更新前后，request引入的本地图片都不显示，未使用react-native-pushy一切正常

**Comment by susan-github** [comment]
@TrustTheBoy 问题不算完全解决，我目前采用的是全量更新，就是更改[react-native-update](https://segmentfault.com/a/1190000008005637)的代码，但是其实也是有问题的，就是在没更新完成的时候，请求头cookie都不能被覆盖，导致有些请求不通过。
至于图片不显示的问题，之前差量更新的时候，偶有出现。

**Comment by sunnylqm** [comment]
历史问题，如新版本有问题请重开issue
