### ISSUE TITLE
iphone  5s update 报错

### ISSUE THREAD

**Issue by 52myu** [reactnativecn/react-native-pushy#9]
系统版本  8.1(12B411)
报错信息  为
        dyld: Symbol not found: ___NSDictionary0__         
查找问题添加        CoreFoundation.framework 并修改 link  CoreFoundation.framework 为option 
依旧报错  RCTHotUpdate.m
    NSMutableDictionary *ret = [@{} mutableCopy];   EXC_BAD_ACCESS 

i6就没事   就 i5s报错

**Comment by wooilung** [comment]
里面有两处声明NSMutableDictionary的地方，把声明改成
NSMutableDictionary *newInfo = [ [NSMutableDictionary alloc] init];
就可以

**Comment by tdzl2003** [comment]
@lvbingru
