### ISSUE TITLE
使用範例正常更新後，APP內容沒有變化

### ISSUE THREAD

**Issue by HFYEH** [reactnativecn/react-native-pushy#91]
react-native-update version: 2.0.1
react-native version: 0.28
platform: android

我依照文件說明，和文件中的示例做了一個熱更新的範本，之後我加了一些text，但点更新後，版本Hash那一欄有更變成我新update的版本，但是剛剛新增或改變的text都沒有出現，跟熱更新前一樣，也就是說全部有改變的只有hash值，請問可能的原因是什麽？

**Comment by sunnylqm** [comment]
可能是使用了debug版本？

**Comment by HFYEH** [comment]
我手機是裝debug版本沒錯

我手機上要裝release版本才有作用嗎？

**Comment by sunnylqm** [comment]
是的

**Comment by HFYEH** [comment]
成功了，感謝！！
