### ISSUE TITLE
ios   'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by mamie42** [reactnativecn/react-native-pushy#93]
把react-native 嵌入原有项目，用CocoaPods 导入React库，添加了RCTUpdate.xcodeproj，Build Phases加了 libRCTUpdate.a库，Header Search Paths 也设置了路径，但是报 'React/RCTDefines.h' file not found错误。

**Comment by tdzl2003** [comment]
请明确您的React Native版本。使用CocoaPods安装的情况下，React Native 0.40+需要单独设置引用的路径，具体参考React Native中文网中的更新日志(0.40)

**Comment by iriswe** [comment]
请问一下这个最后是怎么解决的？

**Comment by iriswe** [comment]
**请问一下这个最后是怎么解决的？**

**Comment by iriswe** [comment]
@mamie42 请问一下这个最后是怎么解决的？
