### ISSUE TITLE
使用switchVersionLater(hash)方法后，每次重新打开应用都提示有更新。

### ISSUE THREAD

**Issue by denzw** [reactnativecn/react-native-pushy#95]
downloadUpdate(info).then(hash => {
            let metaInfo = info.metaInfo ? JSON.parse(info.metaInfo) : undefined;
            if (metaInfo && metaInfo.silent) {
                switchVersionLater(hash);
            }
            else if (metaInfo && metaInfo.force) {
                ANDROID_BACK_EVENT = undefined;
                LOADMODAL.hide();
                Alert.alert('提示', '更新下载完毕，应用必须重新启动！', [
                    {text: '我知道了', onPress: () => {switchVersion(hash);}},
                ]);
            }
            else {
                Alert.alert('提示', '更新下载完毕，是否重启应用?', [
                    {text: '是', onPress: () => {switchVersion(hash);}},
                    {text: '下次启动时', onPress: () => {switchVersionLater(hash);}},

                ]);
            }
        }).catch(err => {
            console.log('update on error', info, err);
            Alert.alert('提示', '更新失败.');
        });

问题：每次关闭应用，再重新打开后都提示有更新。
期望：在下一次启动应用的时候加载已经下载完毕的版本。
Platform: android
React Native version:  0.41.2

**Comment by sunnylqm** [comment]
debug版本？

**Comment by luoshuai5** [comment]
那是因为Application没有被销毁

**Comment by tdzl2003** [comment]
可以监听AppState或BackPressed，当BackPressed最终产生效果 或AppState变化时再次调用switchVersion

**Comment by lihao410** [comment]
问题解决了吗，今天我的也是这个问题
