### ISSUE TITLE
switchVersion(hash)方法在android系统环境下，不会立即重启

### ISSUE THREAD

**Issue by shiyingxyl** [reactnativecn/react-native-pushy#96]
rt.
版本：
     "react-native": "0.42.0",
    "react-native-update": "^4.0.4"

**Comment by tonylinyy** [comment]
我这边也是，有什么解决方案吗
 版本："react-native": "0.32.0",
            "react-native-update": "^3.0.3"

**Comment by hehe2015** [comment]
还没有解决方案吗？

**Comment by tonylinyy** [comment]
@tdzl2003 请问这个问题是否有一些进展呢,需要我们提供更明确的信息或者协助一起排查吗

**Comment by coutliuxing** [comment]
版本："react-native": "0.43.2",
"react-native-update": "^4.0.4"
还是无法重启...
还有一个问题是加载的时候会报错：
Got JS Exception: SyntaxError: Unexpected identifier 'U'....的问题，release模式下出现的

**Comment by hehe2015** [comment]
"react-native": "0.41.0",
"react-native-update": "4.0.4"

**Comment by liuchen066** [comment]
我这里也遇到同样的问题。

**Comment by speaklesstfn** [comment]
同样遇到不能重启的问题，已放弃使用该方案。。

**Comment by hehe2015** [comment]
pushy也不出来说说是什么原因，不靠谱。有条件的最好不要用这个，估计这个都没有人维护

**Comment by tdzl2003** [comment]
此问题已经在4.0.5版本中修复，请各位更新。

**Comment by tonylinyy** [comment]
赞一个👍

**Comment by yangsamuellu** [comment]
"react": "16.6.3",
    "react-mixin": "^4.0.0",
    "react-native": "^0.58.4",
    "react-native-update": "^5.1.6",
又重现了啊。。。

**Comment by huqiangqaq** [comment]
我这现在也出现了这个问题。。。
