### ISSUE TITLE
xcode 新工程 按照命令集成后编译报错

### ISSUE THREAD

**Issue by ChuckyThh** [reactnativecn/react-native-pushy#97]
![Uploading 屏幕快照 2017-03-23 下午4.36.19.png…]()

**Comment by ChuckyThh** [comment]
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      _zipWriteInFileInZip in libRCTHotUpdate.a(zip.o)
      _zipCloseFileInZipRaw64 in libRCTHotUpdate.a(zip.o)
  "_deflateInit2_", referenced from:
      _zipOpenNewFileInZip4_64 in libRCTHotUpdate.a(zip.o)
  "_crc32", referenced from:
      _unzReadCurrentFile in libRCTHotUpdate.a(unzip.o)
      _zipWriteInFileInZip in libRCTHotUpdate.a(zip.o)
  "_inflateEnd", referenced from:
      _unzCloseCurrentFile in libRCTHotUpdate.a(unzip.o)
  "_deflateEnd", referenced from:
      _zipCloseFileInZipRaw64 in libRCTHotUpdate.a(zip.o)
  "_inflateInit2_", referenced from:
      _unzOpenCurrentFile3 in libRCTHotUpdate.a(unzip.o)
  "_BZ2_bzRead", referenced from:
      _bz2_read in libRCTHotUpdate.a(bspatch.o)
  "_BZ2_bzReadClose", referenced from:
      _beginPatch in libRCTHotUpdate.a(bspatch.o)
  "_BZ2_bzReadOpen", referenced from:
      _beginPatch in libRCTHotUpdate.a(bspatch.o)
  "_inflate", referenced from:
      _unzReadCurrentFile in libRCTHotUpdate.a(unzip.o)
  "_get_crc_table", referenced from:
      _unzOpenCurrentFile3 in libRCTHotUpdate.a(unzip.o)
      _zipOpenNewFileInZip4_64 in libRCTHotUpdate.a(zip.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sunnylqm** [comment]
在工程target的Build Phases->Link Binary with Libraries中加入libz.tbd、libbz2.1.0.tbd
