### ISSUE TITLE
集成到OC中的beginPatch方法是否可以单独使用？

### ISSUE THREAD

**Issue by ChuckyThh** [reactnativecn/react-native-pushy#98]
想单独使用bspatch合并，但是在//     Check for appropriate magic 
    if (memcmp(header, "ENDSLEY/BSDIFF43", 16) != 0) {
        //        errx(1, "Corrupt patch\n");
        return -1;
    }
    返回，没法合并，请问应该怎么使用？

**Comment by ChuckyThh** [comment]
我知道了，bspatch做了处理，需要配合命令使用

**Comment by wangjx3** [comment]
怎么解决的，大佬，我也碰到了
