### ISSUE TITLE
android 报错 set canOverrideExistingModule=true

### ISSUE THREAD

**Issue by luoshuai5** [reactnativecn/react-native-pushy#99]
Native module UpdateModule tried to override UpdateModule for module name RCTHotUpdate. If this was your intention, set canOverrideExistingModule=true

这是怎么回事？？

**Comment by luoshuai5** [comment]
react-native 0.4.2
react-native-pushy 4.0.4

**Comment by tdzl2003** [comment]
请检查您的MainApplication.java或MainActivity.java，其中是否出现了两次 UpdatePackage。
